### PR TITLE
Develop acl

### PR DESCRIPTION
**Pull request by githublaohu**
## What is the purpose of the change
Many users provide feedback that RocketMQ can't manage or protect RocketMQ resources effectively in complex development , testing,text
许多用户反馈RocketMQ在复杂的开发，测试等环境中无法有效的管理并且保护好RocketMQ资源。十分盼望RocketMQ拥有ACL体系

## Brief changelog
Look at the acl-plug module.
Look at the rocketmq\distribution\conf\transport.yml file.

## Verifying this change
1. broker configuration files Join the 
aclPlug=true
2. change distribution\conf\transport.yml file
onlyNetAddress is no password required 。Forward compatibility

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [y] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [y ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by duhengforever** [comment]
@githublaohu could you describe your design in this pr and resolve errors occurred during the CI process?

**Comment by githublaohu** [comment]
## 用户使用文档
#### 启动ACL流程
1. RocketMQ5.0版本才支持ACL
2. 启动ACL功能
在borker.conf加入下面配置
```
aclPlug=true
```
3. 在broker.conf文件目录下，创建transport.yml文件并且配置账户与权限


#### transport.yml配置详解
案例
```
onlyNetAddress:
  netaddress: 10.10.103.*
  noPermitPullTopic:
  - broker-a

list:
- account: laohu
  password: 123456
  netaddress: 192.0.0.*
  permitSendTopic:
  - test1
  - test2
- account: laohu
  password: 123456
  netaddress: 192.0.2.1
  permitSendTopic:
  - test3
  - test4
```
1. onlyNetAddress是为了向前兼容。比如client不支持acl功能，为了不支持acl功能client能正常使用acl功能，设定了onlyNetAddress，不需要账户与密码。只要设定netaddress就可以使用了。可能在以后的版本废弃。
2. list是用户与权限列表，可以设定N个用户对应不同选线
3. 属性详解
	1. accoutnt 用户名
	2. password 密码
	3. netaddress： 绑定的IP表达式
	4. permitSendTopic 用户允许send那些Topic
	5. noPermitSendTopic 用户不允许send那些Topic
	6. permitPullTopic 用户允许pull那些Topic
	7. noPermitPullTopic 用户不pull发送那些Topic
4. accoutnt与netaddress组成唯一标示。可以存在多个accoutnt，只要netaddress不同即可
5. accoutnt与password不能为null且长度必须大于6
6. netaddress支持的表达式如下
	1. 简单
	    2. 127.0.0.1 
	2. 多个IP 
	    2. 127.0.0.{1,2,3}
	    2. 127.0.0.1,127.0.0.2,127.0.0.3
	3. 范围
	    1. 127.0.0.*
	    2. 127.0.0.1-200
	    3. 127.0.1-200.*
7. 有相同的topic情况下，permitSendTopic权限优先与noPermitSendTopic，permitPullTopic权限优先于noPermitPullTopic
8. 当设定了permitSendTopic与permitPullTopic的Topic，不在集合内的topic都没有权限
9. 目前不支持topic表达式

**Comment by githublaohu** [comment]
### 目录结构与类基本说明

<html>
acl-plug/src/main/java/org/apache/rocketmq/acl/plug</br>
├── engine</br>
│   ├── AclPlugEngine.java</br>
│   ├── AuthenticationInfoManagementAclPlugEngine.java</br>
│   ├── LoginInfoAclPlugEngine.java</br>
│   └── PlainAclPlugEngine.java</br>
├── entity</br>
│   ├── AccessControl.java</br>
│   ├── AuthenticationInfo.java</br>
│   ├── AuthenticationResult.java</br>
│   ├── BorkerAccessControl.java</br>
│   ├── BorkerAccessControlTransport.java</br>	
│   ├── ControllerParameters.java</br>
│   └── LoginInfo.java</br>
├── exception</br>
│   └── AclPlugRuntimeException.java</br>
├── strategy</br>
│   ├── NetaddressStrategy.java</br>
│   └── NetaddressStrategyFactory.java</br>
├── AccessContralAnalysis.java</br>
├── AclPlugController.java</br>
├── AclRemotingService.java</br>
├── AclUtils.java</br>
├── Authentication.java</br>
└── DefaultAclRemotingServiceImpl.java</br>
</html>
 
### AccessControl
> 权限系统基本分为用户，角色，功能这三点。BorkerAccessControl就是borker角色。
1. 基类AccessControl等于用户
2. AccessControl的实现是角色。
3. 实现类的每个全局变量是这个角色可以用用的所有功能。

比如扩张nameServer的acl-plug的权限功能，只需要写一个NameServerAccessContorl类，里面的变量包含nameServer所有网络请求就可以了。


### NetaddressStrategy
> NetaddressStrategy的功能是校验登陆ip地址与账户IP表达式是否匹配。AccessControl类的netaddress变量就是账户IP表达式

netaddress支持的表达式如下
1. OneNetaddressStrategy处理简单的IP表达式
    2. 127.0.0.1 
2. MultipleNetaddressStrategy处理多个IP表达式
    2. 127.0.0.{1,2,3}
    2. 127.0.0.1,127.0.0.2,127.0.0.3
3. 范围 RangeNetaddressStrategy处理范围IP表达
    1. 127.0.0.*
    2. 127.0.0.1-200
    3. 127.0.1-200.*
4. NullNetaddressStrategy处理所有IP表达式
    1. \* 或者没设值



BrokerAccessControlTransport
> BrokerAccessControlTransport是用来把yml里面的数据序列化称java对象的接收类。没有其他功能

AuthenticationInfo
> 是为了解决acl-plug鉴权的特性（需要进行IP鉴权），保证AccessControl干净与耦合与扩展而设计的。

```java
private AccessControl accessControl;

/*
 *  AccessControl中IP表达式中对应的NetaddressStrategy
*/
private NetaddressStrategy netaddressStrategy;

/*remoting 是通过 code（Integer）识别调用接口的。
 *而accessControl字段名是字符串，需要进行一次解析与识别。把解析与识别的结果保存到authority里面。
 *解析与识别对象为AccessContralAnalysis
*/
private Map<Integer, Boolean> authority;

```

 
### AclPlugEngine类关系图
> AclPlugEngine是核心体系，一套简单鉴权的权限体系与校验，登陆功能等。提供了完整的扩张功能。

AuthenticationInfoManagementAclPlugEngine
>  负责AuthenticationInfo的生成管理，重要细节请看下面端代码。

```java
AuthenticationInfo authenticationInfo = new AuthenticationInfo(accessContralAnalysis.analysis(accessControl), accessControl, netaddressStrategyFactory.getNetaddressStrategy(accessControl));
```

LoginInfoAclPlugEngine
> 负责登陆，注销等操作

PlainAclPlugEngine
> 通过Palin方法获得acl-plug需要的账户信息。也可以通过网络的方法获得。只需要继承LoginInfoAclPlugEngine即可

AccessContralAnalysis
> 负责AccessContral解析与识别对象

Authentication
> 负责鉴权



### AclPlugController与AclRemotingService
> 目前的需求在某种程度上可以认为AclPlugController与AclRemotingService的设计可以放到AclPlugEngine里面。但是为了管理，扩张与维护，解耦分开了。 
AclPlugController负责整个acl-plug的管理，比如决定AclRemotingService与AclPlugEngine实现。不用PlainAclPlugEngine的方式，同过自定义的方法获取账户信息
AclRemotingService负责对外接口请求  
如果要在RocketMQ里面找到对应的设计。AclPlugController相当于broker，AclPlugEngine相当于store，AclRemotingService相当于remoting。


### 初始化流程

### 登陆与鉴权流程

**Comment by githublaohu** [comment]
### 初始化流程

### 登陆与鉴权流程

**Comment by jayden88** [comment]
@githublaohu RocketMQ5.0计划什么时候release？

**Pull request merged**
