### PR TITLE
[ISSUE #3031] Upgrade netty-all dependency version to 4.1.65.Final

### PR DESCRIPTION
**Pull request by messense**
## What is the purpose of the change

Fix https://github.com/apache/rocketmq/issues/3031

## Brief changelog

Upgrade netty-all dependency version to 4.1.65.Final

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by ltamber** [comment]
@messense thanks for the pr, and do you have any performance test (like produce/consume tps) to evaluate performance impact due to upgrade netty from 4.0.42 to 4.1.65 ?

**Comment by ltamber** [comment]
In addition, Should the shell script `runServer` be modified ?  can we contribute back to rocketmq community from [this pr](https://github.com/Homebrew/homebrew-core/pull/79875) ? @messense

**Comment by messense** [comment]
> @messense thanks for the pr, and do you have any performance test (like produce/consume tps) to evaluate performance impact due to upgrade netty from 4.0.42 to 4.1.65 ?

No, I don't know how to benchmark it nor do I have the time and energy to do that.

> In addition, Should the shell script `runServer` be modified ? can we contribute back to rocketmq community from [this pr](https://github.com/Homebrew/homebrew-core/pull/79875) ? @messense

I'm not sure, it may not be suitable for both JDK 8 and later versions.

**Comment by ltamber** [comment]
@RongtongJin Can you help review this pull request ?

**Review by ltamber — APPROVED** [review]

**Comment by RongtongJin** [comment]
I ran quick-start on the computer without problems.

**Review by RongtongJin — APPROVED** [review]

**Comment by guyinyou** [comment]
IMO，the netty component is too important, it is recommended to do more verification before merging

**Review by caigy — APPROVED** [review]

**Review by duhenglucky — APPROVED** [review]

**Pull request merged**
