### PR TITLE
[ISSUE #5147] Fix ClassNotFoundException

### LINKED ISSUE #5147: java.lang.NoClassDefFoundError: io/opentracing/Tracer
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

When I test OpenTracing (e.g. OpenTracingProducer)

it throws exception 

> 
               Error: A JNI error has occurred, please check your installation and try again
          Exception in thread "main" java.lang.NoClassDefFoundError: io/opentracing/Tracer
	          at java.lang.Class.getDeclaredMethods0(Native Method)
	          at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	          at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	          at java.lang.Class.getMethod0(Class.java:3018)
	          at java.lang.Class.getMethod(Class.java:1784)
	          at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	          at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
          Caused by: java.lang.ClassNotFoundException: io.opentracing.Tracer
	          at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	          at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	          at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	          at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	          ... 7 more

I notice that the scope of opentracing-api is provided

- What is expected to see?

the scope of opentracing-api is compile

- What did you see instead?

2. Please tell us about your environment:

develop

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Close #5147 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by caigy — APPROVED** [review]
LGTM

**Comment by drpmma** [comment]
The opentracing should not be explicitly introduced in maven, otherwise, it may cause version conflict. Instead, you should introduce it in your own project.

**Comment by ShadowySpirits** [comment]
> The opentracing should not be explicitly introduced in maven, otherwise, it may cause version conflict. Instead, you should introduce it in your own project.

agree with

**Comment by aaron-ai** [comment]
Actually OpenTracing is archived, you can see more details from [here](https://opentracing.io/), we may remove the dependency of OpenTracing in the near future.

**Review by drpmma — CHANGES_REQUESTED** [review]
The opentracing should not be explicitly introduced in maven, otherwise, it may cause version conflict. Instead, you should introduce it in your own project.

**Comment by Oliverwqcwrw** [comment]
Hello @caigy ,  @drpmma , @ShadowySpirits , @aaron-ai 
thx for your reply, get it
I will manually add `opentracing-api` to the classpath

**Pull request closed without merging**
