### PR TITLE
[ISSUE #4531] fix unreachable statement, redundant code and code style 

### PR DESCRIPTION
**Pull request by PansonPanson**
I'm reading the sourcecode of store module and there are some cpde snippets  in class org.apache.rocketmq.store.DefaultMessageStore that I think need to be fixed.

- **code snippet 1**: redundant code  and  unreachable statement (`match`   is always true)

Screen Shot 2022-06-29 at 21 34 38

- code snippet 2 : replacing with `enhanced for` to Improve code readability
image

### CODE REVIEW

**Comment by PansonPanson** [comment]
linked [issue : 4531](https://github.com/apache/rocketmq/issues/4531)

**Review by hzh0425 — APPROVED** [review]

**Review by guyinyou — APPROVED** [review]

**Comment by guyinyou** [comment]
lgtm

**Review by tsunghanjacktsai — APPROVED** [review]
Pretty thoughtful change. I believe there are still a lot of similar issues in our code. Please could you help us improve them in the future? Really appreciate it.

**Comment by PansonPanson** [comment]
> Pretty thoughtful change. I believe there are still a lot of similar issues in our code. Please could you help us improve them in the future? Really appreciate it.

sure, I’m going to read the source code in the next few months.

**Review by tianliuliu — APPROVED** [review]

**Review by caigy — APPROVED** [review]

**Pull request merged**
