### PR TITLE
[ISSUE #5075] Remove useless method

### LINKED ISSUE #5075: There exist useless method in Message.class
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

`org.apache.rocketmq.common.message.Message#setDelayTimeMs` is useless

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Close #5075 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by tsunghanjacktsai — DISMISSED** [review]

**Comment by ni-ze** [comment]
IMO, This method is invoked by users, and the fellow property is used to check whether the message is a timer message in HookUtils.
```java
public static final String PROPERTY_TIMER_DELAY_MS = "TIMER_DELAY_MS";
```

**Comment by Oliverwqcwrw** [comment]
> IMO, This method is invoked by users, and the fellow property is used to check whether the message is a timer message in HookUtils.
> 
> ```java
> public static final String PROPERTY_TIMER_DELAY_MS = "TIMER_DELAY_MS";
> ```
Hello @ni-ze ,
I think these two parameters (PROPERTY_TIMER_DELAY_MS and PROPERTY_TIMER_DELIVER_MS)express the same effect, whether we can remove the redundant parameters related to the logic. Please help review  @RongtongJin

**Comment by zhiliatom** [comment]
user send delay messge by three ways: 1. message.setDelayTimeSec(10); 2. message.setDelayTimeMs(10_000L); 3. message.setDeliverTimeMs(System.currentTimeMillis() + 10_000L). so I think the property `PROPERTY_TIMER_DELAY_MS ` is not redundant.

**Review by caigy — CHANGES_REQUESTED** [review]
`PROPERTY_TIMER_DELAY_MS` is just similar, but not equal, to `PROPERTY_TIMER_DELAY_SEC`, so IMO it should not be removed, especially for a public field exposed and maybe used by users.

**Pull request closed without merging**
