### PR TITLE
[ROCKETMQ-72] DefaultMessageStore cannot be properly shutdown when fa…

### PR DESCRIPTION
**Pull request by shroman**
…iled in the middle of start()

JIRA issue: https://issues.apache.org/jira/browse/ROCKETMQ-72

Setting `shutdown` to `false` doesn't seem semantically very correct to me, but without it, message store cannot be properly shutdown.
Please review.

### CODE REVIEW

**Comment by zhouxinyu** [comment]
Hi, @shroman , your worry make sense, but if there are some exceptions in `start` process, the JVM will exit.

**Comment by shroman** [comment]
@zhouxinyu I guess you are talking about a shutdown hook that calls `shutdown()`. But the problem remains -- imagine `start()` fails in the middle and even if `shutdown()` is called, no proper termination is done because `this.shutdown` is `true`.

**Comment by vongosling** [comment]
What's going on this pr ?

**Comment by shroman** [comment]
It needs a review.

**Comment by vongosling** [comment]
@shroman I close the pr, if we happened to the same problem next time, please let me know :-)

**Pull request closed without merging**
