### PR TITLE
[ISSUE #8463] Some statistical items should also be deleted to prevent memory leakage when a topic or group is deleted

### LINKED ISSUE #8463: [Bug] Some statistical items should also be deleted to prevent memory leakage when a topic or group is deleted
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

All platform

### RocketMQ version

5.x

### JDK Version

All JDK version

### Describe the Bug

The previous issue is #8432, but after enabling autoDeleteUnusedStats, a small number of metrics still experienced leaks. It was eventually discovered that some metric items were overlooked during the deletion of Topics or Groups.

### Steps to Reproduce

The frequent creation and deletion of topics and groups, while also sending and receiving messages.

### What Did You Expect to See?

No memory leakage

### What Did You See Instead?

Memory leakage

### Additional Context

No

### PR DESCRIPTION
**Pull request by RongtongJin**
### Which Issue(s) This PR Fixes

Fixes #8463

### Brief Description

Some statistical items should also be deleted to prevent memory leakage when a topic or group is deleted

### CODE REVIEW

**Review by fuyou001 — APPROVED** [review]
LGTM

**Review by cserwen — APPROVED** [review]

**Review by GenerousMan — APPROVED** [review]
LGTM

**Review by tsunghanjacktsai — APPROVED** [review]
LGTM

**Review by Focus-rth — APPROVED** [review]
LGTM

**Review by caigy — APPROVED** [review]

**Comment by ni-ze** [comment]
LGTM～

**Review by ShannonDing — APPROVED** [review]

**Pull request merged**
