### PR TITLE
[ISSUE #5358]Fix error core-concept url

### PR DESCRIPTION
**Pull request by GOODBOY008**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Fix error core-concept url. Link issue https://github.com/apache/rocketmq/issues/5358 .

## Brief changelog

Fix error core-concept url.

## Verifying this change

Fix error core-concept url.

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@ShannonDing Pls cc. If you are available. Thank you!

**Review by lizhanhui — CHANGES_REQUESTED** [review]
The website should have some 301 if necessary. The current website is under frequent changes. I don't think having Chinese characters among URL path segments is advisable.

**Review by duhenglucky — APPROVED** [review]

**Comment by Oliverwqcwrw** [comment]
agree with @lizhanhui ,

Would it be better to change Chinese characters to English? @GOODBOY008 

[rocketmq-site](https://github.com/apache/rocketmq-site)

**Comment by GOODBOY008** [comment]
@lizhanhui @Oliverwqcwrw  I will fix rocketmq-site fist and fix this pr. Thanks for your tips.

**Comment by GOODBOY008** [comment]
Branch had be updated.Pls cc.

**Comment by caigy** [comment]
@GOODBOY008 Please add an issue and link this pr to it, as instructions in pr template.

**Review by caigy — DISMISSED** [review]

**Review by Oliverwqcwrw — APPROVED** [review]

**Comment by GOODBOY008** [comment]
> @GOODBOY008 Please add an issue and link this pr to it, as instructions in pr template.

@caigy  Issue had created https://github.com/apache/rocketmq/issues/5358  and linked to this pr. Thanks for your remind.

**Review by tsunghanjacktsai — APPROVED** [review]

**Review by ShannonDing — APPROVED** [review]

**Review by lizhanhui — APPROVED** [review]

**Pull request merged**
