### PR TITLE
[FIX] Travis-CI Java 8 building environments

### PR DESCRIPTION
**Pull request by zihengCat**
## What is the purpose of the change

Fix Travis-CI `Java 8` building environments.

Bug
> Figure: bugs in `.travis.yml`

## Brief changelog

...

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by zihengCat** [comment]
@duhenglucky 
> https://github.com/travis-ci/travis-ci/issues/10428

**Comment by ShannonDing** [comment]
Could you please move this PR to the develop branch?

**Comment by zihengCat** [comment]
Fine! @ShannonDing

**Comment by duhenglucky** [comment]
@zihengCat good job！Could you please split this PR  into two separate ones? One is about the document, the other aims to modify the CI and the copyright time.

**Comment by zihengCat** [comment]
@duhenglucky @ShannonDing 

The error occurred because Travis-CI using an `OpenJDK 11.0.2` building environment, `jdk_switcher` is no longer exists in this building environment. Specify an `Oracle JDK 8` building environment could fix that.

I only fixed Travis-CI Java 8 building environments in `.travis.yml` at b567f35, other changes like modify documents or update `README.md` were completed by Alibaba Group staff.

It's better to **merge this pull request to `master` branch**. After that, merge branch`master` into `develop` to get latest changes.

**Comment by ShannonDing** [comment]
> @duhenglucky @ShannonDing
> 
> The error occurred because Travis-CI using an `OpenJDK 11.0.2` building environment, `jdk_switcher` is no longer exists in this building environment. Specify an `Oracle JDK 8` building environment could fix that.
> 
> I only fixed Travis-CI Java 8 building environments in `.travis.yml` at [b567f35](https://github.com/apache/rocketmq/commit/b567f3533475bda3f4bae74c1f4df4844737e3f3), other changes like modify documents or update `README.md` were completed by Alibaba Group staff.
> 
> It's better to merge this pull request to `master` branch. After that, merge branch`master` into `develop` to get the latest changes.

 Thanks for your good job. To keeping the master clear and as same code as the release version, as usual, it 's forbidden to merge PR into master directly. all PRs will be merged into develop branch, then merge into master after tests. Could you please move this PR to the develop branch?

**Comment by ShannonDing** [comment]
This pr have many commit logs that pushed by other contributors. Could you please rebase it first?  maybe a new pr will be much more better.

**Pull request closed without merging**
