### PR TITLE
[#2870] delete useless shuffle before sort in pickOneAtLeast()

### PR DESCRIPTION
**Pull request by ferrirW**
It seem have not fix in 4.9.3. #2870

### CODE REVIEW

**Comment by ferrirW** [comment]
#2870

**Comment by Git-Yang** [comment]
It will be fixed in a PR #2871

**Comment by Git-Yang** [comment]
It will be fixed in a PR #2871

**Comment by ferrirW** [comment]
> It will be fixed in a PR #2871

ok, i have not found this pr. I will closed my pr.

And why this pr not merged yet?

**Comment by ferrirW** [comment]
> It will be fixed in a PR #2871

ok, i have not found this pr. I will closed my pr.

And why this pr not merged yet?

**Pull request closed without merging**
