### PR TITLE
[ISSUE #6516] Remove redundant code from ThreadLocalIndex

### PR DESCRIPTION
**Pull request by xuziyang**
fix https://github.com/apache/rocketmq/issues/6516

### CODE REVIEW

**Review by mxsm — APPROVED** [review]

**Review by tsunghanjacktsai — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by caigy — APPROVED** [review]
LGTM

**Review by HScarb — APPROVED** [review]
LGTM

**Comment by xuziyang** [comment]
Why did the unit test fail? It has nothing to do with my changes.

**Review by Oliverwqcwrw — APPROVED** [review]

**Comment by Oliverwqcwrw** [comment]
@xuziyang ,The pr can be merged after the required checks have been passed,

Please rebase develop

**Comment by xuziyang** [comment]
> @xuziyang ,The pr can be merged after the required checks have been passed,
> 
> Please rebase develop
Already rebased, please execute workflows.

**Comment by xuziyang** [comment]
Already rebased, please execute workflows.

**Pull request merged**
