### PR TITLE
[ISSUE #5122] Enable checkstyle for test code

### LINKED ISSUE #5122: Enable checkstyle for test code
To improve the quality of test code, checkstyle should be enabled.

```xml
  <executions>
      <execution>
          <id>verify</id>
          <phase>verify</phase>
          <configuration>
              <configLocation>style/rmq_checkstyle.xml</configLocation>
              <encoding>UTF-8</encoding>
              <consoleOutput>true</consoleOutput>
              <failsOnError>true</failsOnError>
              <!-- test checkstyle is disabled here -->
              <includeTestSourceDirectory>false</includeTestSourceDirectory>
          </configuration>
          <goals>
              <goal>check</goal>
          </goals>
      </execution>
  </executions>
```

### PR DESCRIPTION
**Pull request by nowinkeyy**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

fix #5122 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by aaron-ai** [comment]
Could you fix the test of `DefaultMQAdminExtTest#fetchAllTopicList` to pass the CI pipeline? @nowinkeyy 

image

**Comment by nowinkeyy** [comment]
> Could you fix the test of `DefaultMQAdminExtTest#fetchAllTopicList` to pass the CI pipeline? @nowinkeyy
> 
> image

After i git reset the branch, i also saw other test errors. I try to fix it all.

**Comment by lizhanhui** [comment]
+1 to enable style check for test assets.

**Comment by nowinkeyy** [comment]
> +1 to enable style check for test assets.

Bro are you gonna fix the test code to. Seems like I found a lot of test code that didn't work? (i'm not sure)

**Comment by nowinkeyy** [comment]
> Could you fix the test of `DefaultMQAdminExtTest#fetchAllTopicList` to pass the CI pipeline? @nowinkeyy
> 
> image

> image

After i change 2 to 1, an error occurs. It seems 2 is correct?

**Comment by aaron-ai** [comment]
@nowinkeyy This is a huge pull request. If you are not sure about if your modifications affected the CI result which is required to pass, it maybe a good idea to split it by the module. I am pleased to see this feature could be merge as soon as possible.

**Comment by nowinkeyy** [comment]
> @nowinkeyy This is a huge pull request. If you are not sure about if your modifications affected the CI result which is required to pass, it maybe a good idea to split it by the module. I am pleased to see this feature could be merge as soon as possible.

Do you mean to submit PR according to module? If so, i will do so.

**Comment by lizhanhui** [comment]
> Do you mean to submit PR according to module? If so, i will do so.

If the changes are too large, it is OK and advised to split into multiple pull requests. This way, we may have quality reviews and quick merge for those that are simple, and obvious enough.

**Comment by nowinkeyy** [comment]
> > Do you mean to submit PR according to module? If so, i will do so.
> 
> If the changes are too large, it is OK and advised to split into multiple pull requests. This way, we may have quality reviews and quick merge for those that are simple, and obvious enough.

I got it!

**Comment by nowinkeyy** [comment]
Hi @aaron-ai , My new PR #5193.

**Comment by tsunghanjacktsai** [comment]
Maybe close this PR and refer it to the issue itself?

**Pull request closed without merging**
