### PR TITLE
[ROCKETMQ-202] Using the native transport

### PR DESCRIPTION
**Pull request by lizhanhui**
Since 4.0.16, Netty provides the native socket transport for Linux using JNI. This transport has higher performance and produces less garbage, so you might want to give it a try.

See [Netty native transportation docs](http://netty.io/wiki/native-transports.html)

### CODE REVIEW

**Comment by lizhanhui** [comment]
@shroman @Jaskey @dongeforever @zhouxinyu Guys, please review this minor improvement pull request.

**Comment by lindzh** [comment]
Is there any performance data when change to Epoll?

**Comment by lizhanhui** [comment]
@lindzh Checkout this lecture presented by author of Netty, https://www.youtube.com/watch?v=DKJ0w30M0vg

**Comment by shroman** [comment]
@lizhanhui Looks good. Can we have some tests?

**Comment by lizhanhui** [comment]
@shroman What kind of tests, in you mind, should we have for this PR? Benchmark tests to profile performances between java NIO transport and native transport?

**Comment by shroman** [comment]
@lizhanhui I was thinking about platform dependent tests, but performance profiling would be nice too. Sorry for being vague.

**Comment by vongosling** [comment]
Associate with #195  @lizhanhui @shroman I close this pr, we could make a collaborative search for native AIO transport polish :-)

**Pull request closed without merging**
