### PR TITLE
Problem of recording hash slot increment error

### PR DESCRIPTION
**Pull request by jianglianggithub**
slotValue=0 代表第一次命中这个哈希槽。

### CODE REVIEW

**Comment by duhenglucky** [comment]
@jianglianggithub could you change the target branch to develop branch and change this issue title as other guys do?

**Comment by jianglianggithub** [comment]
我好像合并到了master 正确 应该 commit 到 apache:develop 我现在是撤回这个提交 从新 commit一次吗

**Comment by jianglianggithub** [comment]
> @jianglianggithub could you change the target branch to develop branch and change this issue title as other guys do?

我好像合并到了master 正确 应该 commit 到 apache:develop 我现在是撤回这个提交 从新 commit一次吗

**Comment by zongtanghu** [comment]
Please give an English description of this pr and related issues' content.  @jianglianggithub

**Comment by xiangwangcheng** [comment]
> > @jianglianggithub could you change the target branch to develop branch and change this issue title as other guys do?
> 
> 我好像合并到了master 正确 应该 commit 到 apache:develop 我现在是撤回这个提交 从新 commit一次吗

@jianglianggithub  You can modify to develop branch.

**Pull request closed without merging**
