### PR TITLE
[ISSUE #8519] Add test case for rocketmq acl module.

### LINKED ISSUE #8262: [Enhancement] Increase the code test coverage of the project to more than 50% with the help of Tongyi Lingma's capabilities.
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

提交的PR中包含众多的新功能的实现、旧功能更新迭代、以及代码的优化和接口的变更，新的PR合入后不能影响整体代码的健壮性。

### Motivation

目前整体项目的代码覆盖率在46%左右，增加原模块的单测代码覆盖率，新合入的代码可以被单测覆盖。

### Describe the Solution You'd Like

借助通义灵码的能力，补充项目各个模块的代码测试覆盖率全部达到50%以上。

### Describe Alternatives You've Considered

null

### Additional Context

_No response_

### LINKED ISSUE #8519: [Enhancement] Add some test cases for org.apache.rocketmq.acl
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add test for:

org.apache.rocketmq.acl.common.AuthorizationHeader
org.apache.rocketmq.acl.plain.PlainPermissionChecker

### Motivation

for issue #8262 , add test cases for acl module

### Describe the Solution You'd Like

This modification is assisted by the Tongyi Lingcode
356165609-c7933630-2385-4d0f-91bb-2ed6623c1224

### Describe Alternatives You've Considered

NULL

### Additional Context

The test cases have all passed
356165448-e766c43b-9125-4c23-84a3-728c7e059217
356165457-8ff513be-970a-4437-b217-03816e0cff0c

### PR DESCRIPTION
**Pull request by HardX8**
### Motivation

Fixes #8519 

### Summary

Add test for:
1. org.apache.rocketmq.acl.common.AuthorizationHeader
2. org.apache.rocketmq.acl.plain.PlainPermissionChecker

### CheckList
测试用例已经全部通过

### CODE REVIEW

**Comment by yx9o** [comment]
Hi @HardX8 , it's better to create a new issue for this PR.

**Comment by HardX8** [comment]
> Hi @HardX8 , it's better to create a new issue for this PR.

Thank you for reminding me!

**Comment by ShannonDing** [comment]
link #8262

**Review by ShannonDing — CHANGES_REQUESTED** [review]
lack of license header.

**Comment by HardX8** [comment]
> lack of license header.

I have finished adding the license header.

**Review by ShannonDing — DISMISSED** [review]

**Comment by HardX8** [comment]
Could you please let me know what additional changes I need to make to this PR in order for it to be approved for merging? @ShannonDing

**Review by ShannonDing — APPROVED** [review]

**Comment by HardX8** [comment]
All checks have passed,could you please merge this PR so that I can submit my results? @ShannonDing

**Pull request merged**
