### PR TITLE
[ISSUE #2289] Serverless schedule support builtin core

### PR DESCRIPTION
**Pull request by Aaron-He**
## What is the purpose of the change

In order to meet the requirements of flexible time delay messages

## Brief changelog

redesign the architecture of delay messages(different from the current delay message, the delay message here refers to the message delivered at a specific time or delayed a period time) and introduce Time Wheel.
自定义定时延时消息实现

## Verifying this change

Yes

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by zongtanghu** [comment]
Please help to review this pr, thanks. @RongtongJin @duhengforever @vongosling

**Comment by vongosling** [comment]
Great, I would like to follow it.

**Comment by zongtanghu** [comment]
Can you write some test cases and their results which you have already tested in this pr's link? @Aaron-He

**Comment by shudo1219** [comment]
The approach is obvious and vivid,  here are some suggestions(maybe I don't have a thorough graspt of code):
1) Besides DelayMsgCheckPoint file is persisted on master node, the checkpoint should also be synchronized to slave node periodly; otherewise, if master node crashes down and fails to restart, slave node does not know the timestamp the message can be delivered from;

2) In method putKey() of file DelayMsgIndexFile.java, if the method is used in multi threads, we will need to lock before operating the index file; otherwise, we might not need to release the file lock since we never use it;

3) For the message delivered, we'd better keep its physical commitlog offset to a log let's call it deliveryLog,
if master node restarts, we need to find out all the the undelivered messages between deliveryLog and index file, it can try to reduce the number of duplicated messages on the server side.
Whether or not to sync the deliveryLog to slave node? Maybe we need to discuss it later.

4)  If a large mount of delay messages fall into lots of commitlog files randomly,  the speed of delivering delay messages will be slow because of random reading. From our internal tests, the speed is about 200-300 tps on normal disk(15K Rounds Per Minute). Shall we need to limit produce rate?

Let's work together to build open source community better.

**Comment by shudo1219** [comment]
I found another problem needed to discuss:
if timewheel deliveries the delay messages  a little later than excepted, assuming now is 9:00 but the timewheel is deleverying the message at 8:30, meanwhile, the system begins to remove the commitlog, the message between 8:30 and 9:00 in the commitlog(going to be removed soon) might be lost forever. 

Sometimes it is useless to deliver the delay message much later than excepted,  maybe we need to rebalance how late the message we can remove directly.

**Comment by Aaron-He** [comment]
> The approach is obvious and vivid, here are some suggestions(maybe I don't have a thorough graspt of code):
> 
> 1. Besides DelayMsgCheckPoint file is persisted on master node, the checkpoint should also be synchronized to slave node periodly; otherewise, if master node crashes down and fails to restart, slave node does not know the timestamp the message can be delivered from;
> 2. In method putKey() of file DelayMsgIndexFile.java, if the method is used in multi threads, we will need to lock before operating the index file; otherwise, we might not need to release the file lock since we never use it;
> 3. For the message delivered, we'd better keep its physical commitlog offset to a log let's call it deliveryLog,
>    if master node restarts, we need to find out all the the undelivered messages between deliveryLog and index file, it can try to reduce the number of duplicated messages on the server side.
>    Whether or not to sync the deliveryLog to slave node? Maybe we need to discuss it later.
> 4. If a large mount of delay messages fall into lots of commitlog files randomly,  the speed of delivering delay messages will be slow because of random reading. From our internal tests, the speed is about 200-300 tps on normal disk(15K Rounds Per Minute). Shall we need to limit produce rate?
> 
> Let's work together to build open source community better.

1. Good suggestion
2. putKey() is used by reputService, which is single thread. yeah, we can remove the release code block.
3. Good suggestion. As current implementation, user identifies duplicate messages. 
4. It may not work to limit produce rate, because the delayMsgs delivery is up to its startDeliverTime. We can use more memory to make performance better. There may be other better solutions.

Let's work together to build open source community better. ^_^

**Comment by Aaron-He** [comment]
> I found another problem needed to discuss:
> if timewheel deliveries the delay messages a little later than excepted, assuming now is 9:00 but the timewheel is deleverying the message at 8:30, meanwhile, the system begins to remove the commitlog, the message between 8:30 and 9:00 in the commitlog(going to be removed soon) might be lost forever.
> 
> Sometimes it is useless to deliver the delay message much later than excepted, maybe we need to rebalance how late the message we can remove directly.

We can separate the commitlog of delayMsg from the normal messages commitlog in the next version.  we can work together.

**Comment by vongosling** [comment]
Any process for this pr?

**Comment by zongtanghu** [comment]
@vongosling We have already tested by ourselves, and deploy in my production enviroments, but no one review this codes in commnunity.

**Comment by vongosling** [comment]
There are many versions in the community. we could figure out how to integrate them. I would like to help your process.

**Comment by shudo1219** [comment]
> > I found another problem needed to discuss:
> > if timewheel deliveries the delay messages a little later than excepted, assuming now is 9:00 but the timewheel is deleverying the message at 8:30, meanwhile, the system begins to remove the commitlog, the message between 8:30 and 9:00 in the commitlog(going to be removed soon) might be lost forever.
> > Sometimes it is useless to deliver the delay message much later than excepted, maybe we need to rebalance how late the message we can remove directly.
> 
> We can separate the commitlog of delayMsg from the normal messages commitlog in the next version. we can work together.

Looking forward to working together.
In our internal test cases, if there are a large number of delay messages located in one second, it will cause io utils much higher than usual and take a long time to finish deliver these messages. We'd better suggest max delay messages per second and monitor them in backgroud manage system.

**Comment by Aaron-He** [comment]
> > > I found another problem needed to discuss:
> > > if timewheel deliveries the delay messages a little later than excepted, assuming now is 9:00 but the timewheel is deleverying the message at 8:30, meanwhile, the system begins to remove the commitlog, the message between 8:30 and 9:00 in the commitlog(going to be removed soon) might be lost forever.
> > > Sometimes it is useless to deliver the delay message much later than excepted, maybe we need to rebalance how late the message we can remove directly.
> > 
> > 
> > We can separate the commitlog of delayMsg from the normal messages commitlog in the next version. we can work together.
> 
> Looking forward to working together.
> In our internal test cases, if there are a large number of delay messages located in one second, it will cause io utils much higher than usual and take a long time to finish deliver these messages. We'd better suggest max delay messages per second and monitor them in backgroud manage system.

Good suggestion. Setting the max number of delay messages per second ensures that the broker can provide normal messaging services. Also, the user and topic should be considered to ensure fair delivery.

**Comment by vongosling** [comment]
https://github.com/airbnb/dynein, These guys have open-source its delay service on top of the SQS. That is the real pattern I've always think about. Messaging is only used to improve the scalability of queues, scheduling, and concrete workers as an external component. I'd like to see what you're thinking about. There are many restrictions on the current implementation,

**Comment by cserwen** [comment]
This way of implementation is intuitive and can achieve this feature without relying on other components. But as @shudo1219  said, it has some limitations. I also have another problem. If there is someone who want to support messages with a large time span, he must extend the save time of commitLog because the delayed messages are saved together with the normal messages. But this means that we will save normal messages for a long time. It seems to be useless to do this.

**Comment by cserwen** [comment]
@vongosling 
Based on this implementation, we have a better optimization plan. We can use [RocksDB](https://github.com/facebook/rocksdb) to save delayed messages. 

delay-msg


**This has the following advantages:**
- Delay messages can be stored separately from normal messages
- Save the message with the delivery time as the key, which can serve as an index
- When the message is delivered, the commitLog will not be read randomly
- It is also necessary to record the messages that have been delivered to avoid the problem of repeated message delivery caused by master-slave switching

**Of course it has the following disadvantages:**
- RocksDB will be added to RocketMQ, resulting in an increase in RocketMQ dependency

**Comment by maixiaohai** [comment]
Any process？

**Comment by Jason918** [comment]
> We can use [RocksDB](https://github.com/facebook/rocksdb) to save delayed messages.

@cserwen we have done this in https://github.com/didi/DDMQ/tree/master/carrera-chronos.
One of the problems in this way is that Rocksdb needs heavy maintenance when instance get large. Compaction will consume quite a mount of IO and interfere with message writing. So we have to make it an external service, and causing more maintenance work.

**Comment by Git-Yang** [comment]
> > I found another problem needed to discuss:
> > if timewheel deliveries the delay messages a little later than excepted, assuming now is 9:00 but the timewheel is deleverying the message at 8:30, meanwhile, the system begins to remove the commitlog, the message between 8:30 and 9:00 in the commitlog(going to be removed soon) might be lost forever.
> > Sometimes it is useless to deliver the delay message much later than excepted, maybe we need to rebalance how late the message we can remove directly.
> 
> We can separate the commitlog of delayMsg from the normal messages commitlog in the next version. we can work together.

Is the separate storage of delayed messages and normal messages realized now?

**Comment by Aaron-He** [comment]
> > > I found another problem needed to discuss:
> > > if timewheel deliveries the delay messages a little later than excepted, assuming now is 9:00 but the timewheel is deleverying the message at 8:30, meanwhile, the system begins to remove the commitlog, the message between 8:30 and 9:00 in the commitlog(going to be removed soon) might be lost forever.
> > > Sometimes it is useless to deliver the delay message much later than excepted, maybe we need to rebalance how late the message we can remove directly.
> > 
> > 
> > We can separate the commitlog of delayMsg from the normal messages commitlog in the next version. we can work together.
> 
> Is the separate storage of delayed messages and normal messages realized now?


 A new architectural implementation (still based on time wheels) will be released in the future, making timing delay message configuration more flexible, more efficient to send and receive, and less impact on “normal messages”.

**Review by Jeff-Lv — APPROVED** [review]
nice

**Comment by rushsky518** [comment]
If 2 different schedule-times have the same hash value, there may be a problem in `org.apache.rocketmq.store.index.DelayMsgIndexFile#selectPhyOffset` method

**Comment by rushsky518** [comment]
It will be better to partition DelayMsgIndex files by time range

**Pull request closed without merging**
