### PR TITLE
fix code bug & optimize the memory usage in DefaultMappedFile

### PR DESCRIPTION
**Pull request by SeaItFover**
**Make sure set the target branch to develop**

**What is the purpose of the change**
MappedFileQueue: if the initial cursor of listIterator equals zero,the previous element will always null.
MappedFile: use AtomicIntegerFieldUpdater instead of AtomicInteger.

**Brief changelog**

**Verifying this change**
DefaultMappedFile class

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR.

 

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.

- [x] Format the pull request title like [ISSUE #123] Fix UnknownException when host config not exist. Each commit in the pull request should have a meaningful subject line and body.

- [x]  Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x]  Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).

 

- [x] Run mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle to make sure basic checks pass. Run mvn clean install -DskipITs to make sure unit-test pass. Run mvn clean test-compile failsafe:integration-test to make sure integration-test pass.
- [ ]  If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by Oliverwqcwrw** [comment]
Hello @SeaItFover 

Thank you very much for taking the time to contribute to the community, your observation is very keen, I noticed that CI did not pass, please check it first, by the way, you can first create an issue to describe the problem, and then your PR can associate this issue :)

**Comment by Oliverwqcwrw** [comment]
image
You can click Details to see the Details of the error

**Comment by SeaItFover** [comment]
Thanks very much. Hope that my first pr can be merged.

**Comment by SeaItFover** [comment]
I see that all checks have been approved, when to be merged.

**Comment by Oliverwqcwrw** [comment]
Hello, @SeaItFover 
First of all, we  can't timely merger your pr, because all the PMC and Commiters has his own work, everyone is using their free time to contribute to the community, so the review of pr is not certain, as you can see, there are a lot of pr is waiting for review, so I hope you can wait patiently, The community very welcomes contributions from developers

**Review by guyinyou — APPROVED** [review]

**Review by lizhanhui — APPROVED** [review]

**Pull request merged**
