### PR TITLE
[ISSUE #5484] Replace Logging Module with Shaded Logback

### LINKED ISSUE #5484: [RIP-56] Replace Logging Module with Shaded Logback
This issue aims to track [RIP-56: Replace Logging Module with Shaded Logback](https://github.com/apache/rocketmq/wiki/RIP-56-Replace-Logging-Module-with-Shaded-Logback)

### PR DESCRIPTION
**Pull request by aaron-ai**
Fixes #5484

### CODE REVIEW

**Review by lizhanhui — APPROVED** [review]

**Comment by zhouxinyu** [comment]
Consider replacing the current logging module with a simple new module containing a `logback` dependency and customized configurators. We could shade the lagback in the compile stage.

**Comment by lizhanhui** [comment]
@zhouxinyu 
> Consider replacing the current logging module with a simple new module containing a logback dependency and customized configurators. We could shade the lagback in the compile stage.

Shading slf4j and logback is not of core concern and their release cycles match their own upstream vendors...I think it is best to externalize it to its own repository.

**Review by lizhanhui — APPROVED** [review]

**Comment by zhouxinyu** [comment]
> @zhouxinyu
> 
> > Consider replacing the current logging module with a simple new module containing a logback dependency and customized configurators. We could shade the lagback in the compile stage.
> 
> Shading slf4j and logback is not of core concern and their release cycles match their own upstream vendors...I think it is best to externalize it to its own repository.

But we indeed do the shading work, hiding this work in another repo[[rocketmq-logging](https://github.com/aliyun-mq/rocketmq-logging)] doesn't change this truth.

Furthermore, we have some customized [configurators](https://github.com/aliyun-mq/rocketmq-logging/blob/master/rocketmq-logback-extensions/src/main/java/io/github/aliyunmq/logback/extensions/DefaultJoranConfiguratorWrapper.java) should belong to rocketmq repo.

I think there is no one who wants to maintain the new repo rocketmq-logging in aliyun-mq organization.

**Comment by zhouxinyu** [comment]
@lizhanhui Let's revert this merge and try get some feedbacks from the author @aaron-ai

**Comment by aaron-ai** [comment]
> @lizhanhui Let's revert this merge and try get some feedbacks from the author @aaron-ai

OK, I will refine the shading part.

**Pull request merged**
