### PR TITLE
[Issue #4437]Possible alternative solution to get flow control capability without changing the RPCHook Interface

### LINKED ISSUE #4437: [DISCUSS] Optimize design of RpcHook
RocketMQ attempts to implement [Intercepting Filter](https://www.oracle.com/technetwork/java/interceptingfilter-142169.html), providing flexibility of executing the hook pipeline before and after each RPC request. See https://github.com/apache/rocketmq/blob/73b9ac82bcd14b2a40ba31888a96e62d06d42d92/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java#L169

https://github.com/apache/rocketmq/blob/73b9ac82bcd14b2a40ba31888a96e62d06d42d92/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java#L177

The overall pattern is awesome while the implementation is pretty limited.

```java

public interface RPCHook {
    void doBeforeRequest(final String remoteAddr, final RemotingCommand request);

    void doAfterResponse(final String remoteAddr, final RemotingCommand request,
        final RemotingCommand response);
}

```

Comparing similar yet better implementation in Netty: https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/transport/src/main/java/io/netty/channel/ChannelPipeline.java#L32

Current RocketMQ implementation is incapable of stopping processing at premature stages.  This limitation results in ugly implementation of features like Authentication, Authorization. Assume a request is found forbidden in the RpcHook implementation, It can only interrupt the execution through throwing exceptions. [Exceptions are not intended for flow control](https://dzone.com/articles/exceptions-as-controlflow-in-java) and handling of the exception in the NettyRemotingServer is also challenging, additionally, this may also impose risks of flooding our logging files.

### PR DESCRIPTION
**Pull request by dongeforever**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Fix #4437 without changing the RPC hook interface.

The rpchook has been widely used for almost 10 years. Without strong reason, we should not change it to involve incompatibility or complexity.

This PR is an alternative to https://github.com/apache/rocketmq/pull/4446

## Brief changelog

Add a context to the rpchook 

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by lizhanhui** [comment]
Duplicated

**Comment by dongeforever** [comment]
@lizhanhui This PR needs a discussion before closing it.

**Comment by lizhanhui** [comment]
Please discuss on the issue thread or the original PR before creating an 'alternative' one.

**Comment by dongeforever** [comment]
@lizhanhui Yeah. it is intended to discuss it in the original PR. 

In fact, this PR is based on the original PR and just a show.

**Comment by dongeforever** [comment]
@duhengforever @zhouxinyu  Since the original PR is closed, now it is this PR's responsibility to solve the original issue. 
I have added some tests. please help a review.

**Comment by lizhanhui** [comment]
> Since the original PR is closed,  now it is this PR's responsibility to solve the original issue

I closed the original and much better solution because I do NOT see a chance where we can reach an agreement. As pointed out in the original pull request, this pull request suffers multiple drawbacks. I suggest NOT to merge it stealthily before an agreement is reached.

**Pull request closed without merging**
