### PR TITLE
[ISSUE #66] duplicate compress message body if retry to send msg when…

### PR DESCRIPTION
**Pull request by ShannonDing**
…  exception occurs in async sending.

Please do not create a Pull Request without creating an issue first. 

## What is the purpose of the change

Fix issue : duplicate compress message body if retry to send msg when  exception occurs in async sending.

## Brief changelog
reset msg body in sendKernelImpl if body compressed  when async sending;
Add new parameter byte[] msgBody for sendMassage() method in MQClientAPIImpl.

## Verifying this change

Issue is fixed.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by ShannonDing** [comment]
Modify Code Style.

**Comment by lizhanhui** [comment]
Now +1

**Comment by ShannonDing** [comment]
Add UnitTest Case For Body Commpressed when Producer Sending message

**Comment by lollipopjin** [comment]
LGTM +1

**Comment by xpyzh** [comment]
不太理解DefaultMQProducerImpl.sendKernelImpl在异步发送逻辑单独resetbody的原因，在大的try,catch,finally中不是已经resetbody，在异步发送的callback回调里再次使用该msg，应该不会是压缩后的吧

**Pull request merged**
