### PR TITLE
fix: litepull consumer send trace data failed

### LINKED ISSUE #6809: [Bug] DefaultLitePullConsumer send trace data failed
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos7

### RocketMQ version

4.9.0+

### JDK Version

jdk8

### Describe the Bug

Fail to send trace data when use DefaultLitePullConsumer, with trace and acl enabled. 
image

The message consumption is ok.

### Steps to Reproduce

Enable broker acl.
Send some messages to a topic.
Start a DefaultLitePullConsumer to consume, with trace enabled.
Check the client WARN logs.

### What Did You Expect to See?

Succeed to send consumption trace data.

### What Did You See Instead?

Fail to send consumption trace data.

### Additional Context

The cause is:
image

We should use the custom rpchook, not hardcoding null.

### PR DESCRIPTION
**Pull request by redlsz**
Fixes #6809

### CODE REVIEW

**Review by echooymxq — CHANGES_REQUESTED** [review]
Maybe we should refactor it to like ` DefaultMQPushConsumer`, initialize the `TraceDispatcher` on the constructor.

**Comment by redlsz** [comment]
> Maybe we should refactor it to like ` DefaultMQPushConsumer`, initialize the `TraceDispatcher` on the constructor.

It was before the [commit](https://github.com/apache/rocketmq/commit/2dc75d32099cf12e3caff0b32c7fa5fd1ce66a4c).

And bug in this issue is also introduced by the commit above.

**Comment by leizhiyuan** [comment]
any update?

**Comment by yuz10** [comment]
fixed in #7988

**Pull request closed without merging**
