### PR TITLE
Corrected the incorrect description of the Producer module

### PR DESCRIPTION
**Pull request by b1n90**
## What is the purpose of the change

Corrected the incorrect description of the Producer module in this picture (Incorrectly introduced Consumer in the Producer module)

## Brief changelog

Graphic correction

## Verifying this change

https://github.com/apache/rocketmq/issues/2855#issue-873498812

### CODE REVIEW

**Comment by vongosling** [comment]
Pls make your pr  request to develop branch.

**Comment by duhenglucky** [comment]
@b1n90 ping

**Comment by b1n90** [comment]
on it.



发自我的iPhone


------------------ Original ------------------
From: Heng Du ***@***.***&gt;
Date: Fri,May 21,2021 9:35 AM
To: apache/rocketmq ***@***.***&gt;
Cc: b1n90 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/rocketmq] Corrected the incorrect description of the Producer module (#2856)





 
@b1n90 ping

**Comment by ShannonDing** [comment]
see #2857

**Comment by vongosling** [comment]
It seems two different pr.

**Pull request merged**
