### PR TITLE
[Issue #4427] Implement transaction message escape of RIP 32 

### PR DESCRIPTION
**Pull request by 6U-U9**
**Make sure set the target branch to `develop`**
**PS: Target branch is 5.0.0-beta cause there is no EscapeBridge in develop branch** 

## What is the purpose of the change

Implement transaction message escape of RIP  32
Issue #4427 

## Brief changelog

Design can be found in Issue #4427 .

## Verifying this change

Test TransactionSlaveActingMasterIT added to Test Module.

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by hzh0425** [comment]
Good job, But does your contribution overlap with this issue? https://github.com/apache/rocketmq/issues/4408

**Comment by hzh0425** [comment]
image
Pls check why the test failed.

**Comment by 6U-U9** [comment]
> image
> 
> Pls check why the test failed.

image
I didn't meet this error when running test. And also you can find the test passed in the Travis CI - Pull Request build detail, line 3086.
[https://app.travis-ci.com/github/apache/rocketmq/jobs/572672220](url)

**Comment by hzh0425** [comment]
yep, you can re trigger the ci

**Review by caigy — CHANGES_REQUESTED** [review]
It's a bit puzzling to process message escape when processing messages that should be discarded. Hopefully you could provide more details about your design.

**Comment by 6U-U9** [comment]
> It's a bit puzzling to process message escape when processing messages that should be discarded. Hopefully you could provide more details about your design.

Actually it's like the remote message escape mechanism. When discarding messages, Rocket MQ puts messages into **RMQ_SYS_TRANS_CHECK_MAX_TIME_TOPIC**, which is a not allowed to send topic in topic validator. For the remote escape of these messages, first wrap them in their origin topic with **transaction check time**, and send it to other master broker. As messages bring **PROPERTY_TRANSACTION_CHECK_TIMES** with them, master broker received these message first put them into half topic queue and discard them in next check.
应丢弃的消息逃逸机制和正常消息的逃逸机制相似。为了避免**RMQ_SYS_TRANS_CHECK_MAX_TIME_TOPIC**远程不可写的限制，首先将半消息用原Topic包装，此时消息仍携带**PROPERTY_TRANSACTION_CHECK_TIMES**属性，然后再投递到远程主节点上。收到消息的主节点将消息放入半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**等待检查，在下一次检查中，将消息丢弃。

**Comment by caigy** [comment]
`org.apache.rocketmq.broker.transaction.queue.DefaultTransactionalMessageCheckListener#resolveDiscardMsg` handles transactional messages that should not be processed any more, what about normal transactional messages on the slave broker in acting master mode? 
Furthermore, what happened if the broken master recovered?

**Comment by 6U-U9** [comment]
> `org.apache.rocketmq.broker.transaction.queue.DefaultTransactionalMessageCheckListener#resolveDiscardMsg` handles transactional messages that should not be processed any more, what about normal transactional messages on the slave broker in acting master mode? Furthermore, what happened if the broken master recovered?

When dealing with transaction message normally, **transactionalMessageCheckService** checks half messages in **RMQ_SYS_TRANS_HALF_TOPIC**,  calls **putBackHalfMsgQueue** to rewrite messages still need to check back to message queue of **RMQ_SYS_TRANS_HALF_TOPIC** , and updates consume offset.
When slave acts master, its **transactionalMessageCheckService** will start, but its **EndTransactionProcessor** will not accept any message tries to end a transaction such as commit or rollback. The running **transactionalMessageCheckService** will check transaction message and send any message needs check to a living master. **RMQ_SYS_TRANS_HALF_TOPIC** is also a topic not allowed to send in topic validator.So first wrap them in their origin topic with transaction check time, and send it to other master broker. Messages will bring its properties, such as **PROPERTY_TRANSACTION_CHECK_TIMES** , so master broker received these message is not going to check the transaction message for another **TRANS_CHECK_MAX_TIME**.
When the master broker recovers, it will be in pre-online progress before it is launched. It reversely obtains the metadata of the slave, especially the consumer offset of **RMQ_SYS_TRANS_HALF_TOPIC**. Thus the recovered master broker will not check the message which has escaped.
在正常处理事务消息时，**transactionalMessageCheckService**检查半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**中的半消息，并调用**putBackHalfMsgQueue**将检查到的并且仍需进行检查的消息写入半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**中，并更新消费位置。
Slave代理Master时，**transactionalMessageCheckService**将启动。**transactionalMessageCheckService**将检查到的事务消息通过EscapeBridge向其他的Master逃逸。逃逸过程中为了避免半消息**RMQ_SYS_TRANS_HALF_TOPIC**不可写的限制，首先将半消息用原Topic包装，此时消息仍携带**PROPERTY_TRANSACTION_CHECK_TIMES**等属性，然后再投递到远程主节点上。收到消息的主节点将消息放入半消息队列**RMQ_SYS_TRANS_HALF_TOPIC**等待检查。
在主节点恢复后，通过预上线机制获取从节点的**RMQ_SYS_TRANS_HALF_TOPIC**队列的消费位点，更新主节点自己的**RMQ_SYS_TRANS_HALF_TOPIC**队列的消费位点，将不再检查已经逃逸的事务消息。

**Pull request closed without merging**
