### PR TITLE
[ISSUE #8046] Fix authentication context build for no extFields

### LINKED ISSUE #8046: [Bug] Fix authentication context build for no extFields
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

develop

### JDK Version

Java8

### Describe the Bug

HEAT_BEAT api has not extFields, but then authentication has a check

### Steps to Reproduce

start producer/consumer without ak/sk

### What Did You Expect to See?

If an api has not extFields, then authentication context builder will pass

### What Did You See Instead?

If an api has not extFields, then authentication context builder will pass

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dingshuangxi888**
### Which Issue(s) This PR Fixes

Fixes #8046

### Brief Description

Fix authentication context build for no extFields

### How Did You Test This Change?

start producer/consumer without ak/sk

### CODE REVIEW

**Comment by cserwen** [comment]
If the client sets ak/sk, then all request headers will have ak/sk information, including heartbeats.
And if ak/sk is not set on the client, those configurations should also be turned off on the server. Maybe this is not a bug @dingshuangxi888 
```
authenticationEnabled=false
authorizationEnabled=false
```

**Comment by dingshuangxi888** [comment]
> If the client sets ak/sk, then all request headers will have ak/sk information, including heartbeats. And if ak/sk is not set on the client, those configurations should also be turned off on the server. Maybe this is not a bug @dingshuangxi888
> 
> ```
> authenticationEnabled=false
> authorizationEnabled=false
> ```

The old client has no ReqeustHeader, such as Heartbeat api, if the ak/sk is not set, it will get NPE error.

**Comment by cserwen** [comment]
> > If the client sets ak/sk, then all request headers will have ak/sk information, including heartbeats. And if ak/sk is not set on the client, those configurations should also be turned off on the server. Maybe this is not a bug @dingshuangxi888
> > ```
> > authenticationEnabled=false
> > authorizationEnabled=false
> > ```
> 
> The old client may has no ReqeustHeader, such as Heartbeat api, if the ak/sk is not set, the extFields will be null and it will get NPE error.

OK

**Comment by cserwen** [comment]
@dingshuangxi888  Some unit-tests maybe need to be resolved.

**Review by lizhimins — APPROVED** [review]

**Pull request merged**
