### PR TITLE
[ISSUE #5373]output namesrv bindaddress when starting

### LINKED ISSUE #5373: NameSrv does not output the bindaddress when starting
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
When start the NameSrv process ,the output in the console does not include the bind address

- What is expected to see?

- What did you see instead?
"The Name Server boot success. serializeType=JSON"

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

expected result :
the NameSrv can output the bindaddress for investigation .

### PR DESCRIPTION
**Pull request by xiaoyifang**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

add extra output infomation when start the namesrv 
Fixes #5373 

## Verifying this change

before the changes,the output is "The Name Server boot success. serializeType=JSON"
after:
The Name Server boot success. serializeType=JSON, address 0.0.0.0:9876

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by Oliverwqcwrw — APPROVED** [review]
IMO,  it would be a good idea to see the bound port at startup, Could you please create an issue and associate it with the current pr?

**Comment by xiaoyifang** [comment]
https://github.com/apache/rocketmq/issues/5373

**Review by mxsm — APPROVED** [review]
LGTM~~

**Review by tsunghanjacktsai — APPROVED** [review]

**Review by lizhanhui — APPROVED** [review]
Looks good

**Review by lizhimins — APPROVED** [review]

**Pull request merged**
