### PR TITLE
[ISSUE #4239] Use function computeIfAbsent replace if

### PR DESCRIPTION
**Pull request by xyj1209**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

use function computeIfAbsent replace if

## Brief changelog

use function computeIfAbsent replace if

### CODE REVIEW

**Review by li-xiao-shuang — APPROVED** [review]

**Review by hzh0425 — APPROVED** [review]

**Review by RongtongJin — APPROVED** [review]

**Comment by RongtongJin** [comment]
@xyj1209 Is there a relevant issue associated with this pull request？

**Comment by xyj1209** [comment]
> @xyj1209是否存在与此拉取请求相关的相关问题？

There are no issue associated with this pull request.

**Comment by RongtongJin** [comment]
> > @RongtongJin
> 
> There are no issue associated with this pull request.

Could you create an issue associated with this pull request？

**Comment by xyj1209** [comment]
@RongtongJin [ISSUE #4239 ]

**Pull request merged**
