### PR TITLE
[ISSUE #4130] Remove the exception which will never be thrown by method from method signature

### PR DESCRIPTION
**Pull request by dugenkui03**
## What is the purpose of the change
#4130

### CODE REVIEW

**Review by yuz10 — APPROVED** [review]

**Review by RongtongJin — APPROVED** [review]

**Review by RongtongJin — CHANGES_REQUESTED** [review]
/home/travis/build/apache/rocketmq/srvutil/src/main/java/org/apache/rocketmq/srvutil/FileWatchService.java:26:8: error: Unused import - java.security.NoSuchAlgorithmException.
Audit done.

Hi, CI not pass

**Comment by dugenkui03** [comment]
> /home/travis/build/apache/rocketmq/srvutil/src/main/java/org/apache/rocketmq/srvutil/FileWatchService.java:26:8: error: Unused import - java.security.NoSuchAlgorithmException. Audit done.
> 
> Hi, CI not pass

Thanks for your review, CI error is updated.

**Review by RongtongJin — APPROVED** [review]

**Review by odbozhou — APPROVED** [review]

**Review by ni-ze — APPROVED** [review]

**Comment by tianliuliu** [comment]
Some businesses that use the old MQ client have caught these exceptions. When they are deleted in this new client, the business compile will fail, resulting in incompatible client versions.

**Comment by dugenkui03** [comment]
> Some businesses that use the old MQ client have caught these exceptions. When they are deleted in this new client, the business compile will fail, resulting in incompatible client versions.

Yes, you are right. I think it is nessary to correct the method signature as soon as possible to avoid more technical debt. This pr should be a breaking change.

# Describe in Chinese
你是对的。但是我认为仍然有必要修正这个错误以避免更多的技术债务，这对于相关方法算是 重大更新(beaking change)。

在提交此 PR 的过程中也考虑到了尽可能合理的向前兼容，例如 1处调用 永远不会抛出 2异常`MQBrokerException`、但鉴于该类实现的接口方法定义抛出了`deletePlainAccessConfig`、此处没有去掉`MQBrokerException`。
image

**Comment by tianliuliu** [comment]
> > Some businesses that use the old MQ client have caught these exceptions. When they are deleted in this new client, the business compile will fail, resulting in incompatible client versions.
> 
> Yes, you are right. I think it is nessary to correct the method signature as soon as possible to avoid more technical debt. This pr should be a breaking change.
> 
> # Describe in Chinese
> 你是对的。但是我认为仍然有必要修正这个错误以避免更多的技术债务，这对于相关方法算是 重大更新(beaking change)。
> 
> 在提交此 PR 的过程中也考虑到了尽可能合理的向前兼容，例如 1处调用 永远不会抛出 2异常`MQBrokerException`、但鉴于该类实现的接口方法定义抛出了`deletePlainAccessConfig`、此处没有去掉`MQBrokerException`。 image

link @RongtongJin

**Review by tianliuliu — APPROVED** [review]

**Pull request merged**
