### PR TITLE
[Infra Improvement] Build And Run Unit Tests in Parallel

### PR DESCRIPTION
**Pull request by lizhanhui**
**Make sure to set the target branch to `develop`**

## What is the purpose of the change

The purpose of this pull request is to mitigate the time required to see CI results. At present, it takes some 40 minutes for travis CI or github action to build and run tests. This is a blocking issue for work efficiency. 

This is to follow [practice and philosophy of Google Build ](https://abseil.io/resources/swe-book/html/ch18.html). The first 
is to bring distributed remote build and execution(RBE hereafter) through Bazel.

Through the introduction of RBE, we are expecting to see a major CI running time reduction, from some 40 minutes to 2 or 3 minutes. 

## Brief changelog

This PR looks big at the first sight. But it actually contains two major changes
1. Bazel Build System files, including .bzl, .bazel, and WORKSPACE that make Bazel work;
2. Fixes to existing test cases and some main source files, allowing execution of test cases in parallel;

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by aaron-ai — APPROVED** [review]

**Comment by fuyou001** [comment]
Great Job.

**Review by zhouxinyu — APPROVED** [review]
Great job

**Comment by hill007299** [comment]
Great for improving efficiency

**Review by lollipopjin — APPROVED** [review]

**Review by lizhimins — APPROVED** [review]

**Review by hill007299 — APPROVED** [review]
Great Job

**Comment by lizhanhui** [comment]
The coverage pipeline experiences timeouts while downloading resources or uploading results. It's not related to changes in this pull request and will be resolved in a dedicated issue/pull-request pair [here](https://github.com/apache/rocketmq/issues/4879)

**Pull request merged**
