### PR TITLE
[ISSUE #4226] msg length exceeds the maximum length when sendback

### PR DESCRIPTION
**Pull request by ni-ze**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

 fix bug:
msg length exceeds the maximum length when sendback

## Brief changelog

 fix bug:
msg length exceeds the maximum length when sendback

## Verifying this change

 fix bug:
msg length exceeds the maximum length when sendback

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by 912988434** [comment]
nice modification, In practice we need to make sure that properties is less than 500 bytes when sending messages？

**Comment by ni-ze** [comment]
> nice modification, In practice we need to make sure that properties is less than 500 bytes when sending messages？

500 is a value which sendback message length large than normal message, It has nothing to do with the properties length of the message.

**Review by duhenglucky — COMMENTED** [review]
Are you willing to sort out all the system properties? And sort out the length and content of system properties under different scenarios and different interfaces. This seems to be a huge project, but we can complete it together with other developers in the community.

**Comment by ni-ze** [comment]
> 



> Are you willing to sort out all the system properties? And sort out the length and content of system properties under different scenarios and different interfaces. This seems to be a huge project, but we can complete it together with other developers in the community.

yes, It's my pleasure.

**Review by tianliuliu — APPROVED** [review]

**Pull request closed without merging**
