### PR TITLE
using take replace poll

### PR DESCRIPTION
**Pull request by kang-hl**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by tsunghanjacktsai — COMMENTED** [review]
Hi @kang-hl ,

Quick question, From my understanding, wouldn't this make it hang for a while if there's nothing in the queue? Or could you pls explain why you chose take() over poll() in this scenario?

**Comment by kang-hl** [comment]
less cpu use

**Comment by kang-hl** [comment]
use less cpu

**Comment by guyinyou** [comment]
org/apache/rocketmq/namesrv/routeinfo/BatchUnRegisterService.java:63
`while (!this.isStopped()) {`

use poll can make thread graceful stop. maybe this is the original intention

**Comment by kang-hl** [comment]
it may be more graceful to replace this.unRegisterService.shutdown(true) with this.unRegisterService.shutdown()

**Comment by kang-hl** [comment]
it may be more graceful to replace this.unRegisterService.shutdown(true) with this.unRegisterService.shutdown()

**Review by guyinyou — APPROVED** [review]
You are right, so whether to replace this.unRegisterService.shutdown() to achieve a more elegant effect or replace poll() to achieve lower cpu consumption?

**Comment by kang-hl** [comment]
replacing poll() is better than replacing this.unRegisterService.shutdown() because the queue is empty most of the time

**Review by lizhiboo — APPROVED** [review]
LGTM

**Review by Oliverwqcwrw — APPROVED** [review]
Agree with , use less  cpu

**Review by lizhimins — DISMISSED** [review]
agree

**Comment by lizhanhui** [comment]
@kang-hl Please rebase to the latest `develop` branch to trigger CI checks that are required to merge this pull request.

**Review by tianliuliu — DISMISSED** [review]
LGTM

**Review by lizhanhui — APPROVED** [review]

**Pull request merged**
