### PR TITLE
[ISSUE #6873] Not update controller address list when the resolved result is empty

### PR DESCRIPTION
**Pull request by weihubeats**
https://github.com/apache/rocketmq/issues/6873

### CODE REVIEW

**Review by TheR1sing3un — APPROVED** [review]
LGTM~

**Comment by xdkxlk** [comment]
I think we should differentiate between whether it throws an exception or actually returns null. And `dnsLookupAddressByDomain` is also used by `updateNameServerAddressListByDnsLookup` in `BrokerOuterAPI` .

**Comment by weihubeats** [comment]
I think even if the actual is null, it should not be updated to null, because the actual is null is also abnormal.
Exceptions or actual null can be distinguished by logging

**Review by RongtongJin — COMMENTED** [review]
If the parsing fails, it should be printed in the log. What are the benefits of setting it to null here?

**Comment by ferrirW** [comment]
If parsing fails, the api will return the empty list, not null

you refered case can be provide more information for repetition ？

**Pull request closed without merging**
