### PR TITLE
[ISSUE #8486]Add more test coverage for BrokerMetricsManager

### LINKED ISSUE #8486: [Enhancement] Add more test coverage for BrokerMetricsManager
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add more test coverage for BrokerMetricsManager

### Motivation

add more tests

### Describe the Solution You'd Like

add more tests

### Describe Alternatives You've Considered

add more tests

### Additional Context

before
Pasted Graphic 2

after
Pasted Graphic 1

### PR DESCRIPTION
**Pull request by ziiyee**
### Which Issue(s) This PR Fixes

Fixes #8486  

### Brief Description

Add more test coverage.

Before:
Pasted Graphic 2

After:
Pasted Graphic 1

### How Did You Test This Change?

All tests passed.

image

PS: TONGYI Lingma provided code generation and programming support.
通义灵码使用-如何使用测试覆盖率插件

### CODE REVIEW

**Comment by ziiyee** [comment]
for soc in #8262

**Review by TheR1sing3un — APPROVED** [review]
LGTM~
Thanks for your contributions!

**Comment by ziiyee** [comment]
Thank you~
I'm a newcomer  to open source development, should I fix the bazel-compile build errors to get this PR merged?
@TheR1sing3un

**Review by ShannonDing — APPROVED** [review]

**Comment by TheR1sing3un** [comment]
> Thank you~ I'm a newcomer to open source development, should I fix the bazel-compile build errors to get this PR merged? @TheR1sing3un

Bazel-complie check isn't required for pr merging, but u can try to fix it in a new pr.

**Comment by ShannonDing** [comment]
@ziiyee A reminder from the Tianchi platform: it‘s better to submit your results to the [official website](https://tianchi.aliyun.com/competition/entrance/532215/information) asap.

**Review by ShannonDing — APPROVED** [review]
LGTM

**Pull request merged**
