### PR TITLE
[ISSUE 7313]  Enhancement Optimization Method name

### LINKED ISSUE #7313: [Enhancement]  Optimization Method Name
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary
**path:** org.apache.rocketmq.tieredstore.provider.TieredStoreTopicBlackListFilter

The method addTopicToWhiteList of this TieredStoreTopicBlackListFilter class should be renamed to addTopicToBlackList
image

### Motivation

I found that the method name does not match the actual logic of the method

### Describe the Solution You'd Like

Modify Method Name

### Describe Alternatives You've Considered

Modify Method Name

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by shriVATSA54**
###  issue=> #7313 

 https://github.com/apache/rocketmq/issues/7313    This is link for my issue.

Fixes #7313

open1

### Brief Description

There was an Enhancement change needed to change method name from  addTopicToWhiteList of this TieredStoreTopicBlackListFilter class should be renamed to addTopicToBlackList .
 In three places it was required to change the name which I have done.

**Note: This was my first ever contributions if you need some changes or if I committed mistake please do say and give feedback**
### How Did You Test This Change?

I have tried running the file and are running.

### CODE REVIEW

**Review by joeCarf — COMMENTED** [review]
you can change the title like `[ISSUE #xxxx]xxxxx`

**Comment by shriVATSA54** [comment]
> you can change the title like `[ISSUE #xxxx]xxxxx`

As per your request I have made changes in Title.
Thank you.

**Comment by joeCarf** [comment]
截屏2023-10-02 14 02 28

**Review by joeCarf — COMMENTED** [review]
for your reference, the title should be like the pic I paste above

**Comment by shriVATSA54** [comment]
> for your reference, the title should be like the pic I paste above

Oh Sorry!

Made changes once again.
(Thank you My first ever Contribution)

**Review by joeCarf — APPROVED** [review]
LGTM

**Review by mxsm — APPROVED** [review]
LGTM

**Comment by shriVATSA54** [comment]
> LGTM

Will it be merged ??

Should I keep contributing to some other issues too?

**Comment by mxsm** [comment]
> > LGTM
> 
> Will it be merged ??
> 
> Should I keep contributing to some other issues too?



> > LGTM
> 
> Will it be merged ??
> 
> Should I keep contributing to some other issues too?

Wait for a committer or PMC to merge the code

**Review by RongtongJin — APPROVED** [review]

**Pull request merged**
