### PR TITLE
[ISSUE #6879] ConcurrentHashMapUtils fails to solve the loop bug in JDK8

### LINKED ISSUE #6879: [Bug] ConcurrentHashMapUtils fails to solve the loop bug in JDK8.
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Mac  OS 13.0

### RocketMQ version

branch: (develop|tag 5.1.1) version: 5.1.1

### JDK Version

jdk8

### Describe the Bug

[ConcurrentHashMapUtils](https://github.com/apache/rocketmq/blob/develop/common/src/main/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtils.java) 中提供的computeIfAbsent方法没有解决jdk8的循环问题，复现代码如下

```
@Test
    public void computeIfAbsent() {
        ConcurrentHashMap<String, String> map = new ConcurrentHashMap<>();
//        map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->"42"));
        ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key -> map.computeIfAbsent("BBBB", key2 -> "42"));
    }
```

### PR DESCRIPTION
**Pull request by leeyiyu**
### Which Issue(s) This PR Fixes

Fixes #6879

### How Did You Test This Change?

Test Case
```
@Test
    public void computeIfAbsent() {

        ConcurrentHashMap<String, String> map = new ConcurrentHashMap<>();
//        map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->"42"));
        ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key -> map.computeIfAbsent("BBBB", key2 -> "42"));
    }

```

Solution
```
public static <K, V> V computeIfAbsent(ConcurrentMap<K, V> map, K key, Function<? super K, ? extends V> func) {
        Objects.requireNonNull(func);
        if (isJdk8) {
            V v = map.get(key);
            if (null == v) {
                // v = map.computeIfAbsent(key, func);

                // this bug fix methods maybe cause `func.apply` multiple calls.
                v = func.apply(key);
                if (null == v) {
                    return null;
                }
                final V res = map.putIfAbsent(key, v);
                if (null != res) {
                    // if pre value present, means other thread put value already, and putIfAbsent not effect
                    // return exist value
                    return res;
                }
            }
            return v;
        } else {
            return map.computeIfAbsent(key, func);
        }
    }
```

### CODE REVIEW

**Comment by xiaoyifang** [comment]
check this ,https://juejin.cn/post/7094561581631012878

**Comment by leeyiyu** [comment]
> 



> 



> check this ,https://juejin.cn/post/7094561581631012878
> 
> IMO, The original code has no problem.

You can run this Case,CPU utilization will be 100%

```
@Test
    public void computeIfAbsent() {

        ConcurrentHashMap<String, String> map = new ConcurrentHashMap<>();
        ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key -> map.computeIfAbsent("BBBB", key2 -> "42"));
    }
```

**Comment by Codeprh** [comment]
Reference dubbo link：https://github.com/apache/dubbo/pull/11987

**Comment by xiaoyifang** [comment]
> ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key -> map.computeIfAbsent("BBBB", key2 -> "42"));

This has caused a deadlock.  I think This should left for the user to avoid .

the above code is similar like 
```
synchronized(obj){
    synchronized(obj){
           //logic
    }

}
```

**Comment by ferrirW** [comment]
> check this ,https://juejin.cn/post/7094561581631012878
> 
> IMO, The original code has no problem.

It doesn't seem to be same bug. The blog mentions is https://bugs.openjdk.org/browse/JDK-8161372

I think @leeyiyu fixed is: https://bugs.openjdk.org/browse/JDK-8062841

**Review by caigy — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Pull request merged**
