### PR TITLE
[ISSUE #7143] Add topic config tools search

### LINKED ISSUE #7143: [Feature] Add admin tool to query topic config
### Is Your Feature Request Related to a Problem?

Add a get topic config command in mqadmin.

### Describe the Solution You'd Like

.

### Describe Alternatives You've Considered

.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Ceilzcx**
### Which Issue(s) This PR Fixes

Fixes #7143

### CODE REVIEW

**Review by mxsm — COMMENTED** [review]
@Ceilzcx  Hi please link this pr to related issue

**Comment by Ceilzcx** [comment]
> @Ceilzcx Hi please link this pr to related issue

done it

**Comment by Ziy1-Tan** [comment]
you can refer to `GetConsumerConfigSubCommand`.

**Comment by Ceilzcx** [comment]
> 

thank you for you comment，like this?
image

**Comment by Ceilzcx** [comment]
Is there anything else you need to add?

**Review by joeCarf — COMMENTED** [review]
changes LGTM, but there are test failures, please check out :)
图片

**Comment by Ceilzcx** [comment]
> changes LGTM, but there are test failures, please check out :) 图片

sorry, I'm not understand, I didn't change the code about rocketmq-store module, and I can pass the test in local, i don't know how to fix it

**Comment by Ceilzcx** [comment]
> > 
> 
> > > changes LGTM, but there are test failures, please check out :) 图片
> > 
> > 
> > sorry, I'm not understand, I didn't change the code about rocketmq-store module, and I can pass the test in local, i don't know how to fix it
> 
> retry？

well, the first when I pr has no failures

**Comment by Ceilzcx** [comment]
you see re-run the jobs? I don't have permission.

**Comment by joeCarf** [comment]
try `git rebase master` and push commits, it will re-trigger the ci flow

**Comment by Ceilzcx** [comment]
> try `git rebase master` and push commits, it will re-trigger the ci flow

done it

**Comment by joeCarf** [comment]
seems that you need approval to trigger ci flow; I don't have the permission: )

**Comment by dyrnq** [comment]
@Ceilzcx @mxsm

how about this? continue?

**Comment by dyrnq** [comment]
Can we reactivate this PR? @Ziy1-Tan

**Pull request closed without merging**
