### PR TITLE
[ISSUE #7213] Fix the interval typo

### LINKED ISSUE #7213: [Enhancement] Typo about interval
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

typo about interval

### Motivation

fix typo 

### Describe the Solution You'd Like

fix typo

### Describe Alternatives You've Considered

no

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zhiliatom**
### Which Issue(s) This PR Fixes

Fixes #7213

### CODE REVIEW

**Review by joeCarf — COMMENTED** [review]
ArrayIndexOutOfBoundsException occurred in ut, please fix it :)

**Comment by zhiliatom** [comment]
@joeCarf @RongtongJin Help review this patch please :)

**Review by joeCarf — APPROVED** [review]
LGTM

**Review by caigy — CHANGES_REQUESTED** [review]
Please add a new variable instead of replacing it. Always keep in mind the compatibility.

**Comment by zhiliatom** [comment]
> Please add a new variable instead of replacing it. Always keep in mind the compatibility.

should we Preserve a wrong Configuration? I prefer to modify it in this SNAPSHOT version

**Pull request closed without merging**
