### PR TITLE
[ISSUE #3692] docs: Modify the title content about the message query documentation.

### PR DESCRIPTION
**Pull request by XiaoyiPeng**
**Make sure set the target branch to `develop`**

## What is the purpose of the change
 For issue #3692 

## Brief changelog

Modify the title content about the message query documentation.

### CODE REVIEW

**Review by panzhi33 — APPROVED** [review]

**Review by vongosling — APPROVED** [review]

**Comment by vongosling** [comment]
Thanks @XiaoyiPeng . 

The community still has a lot of design, code including the documentation is not perfect, look forward to your more participation. If you were willing, I'll pay more attention to you and help you get more involved in the community:-)

**Comment by XiaoyiPeng** [comment]
> Thanks @XiaoyiPeng .
> 
> The community still has a lot of design, code including the documentation is not perfect, look forward to your more participation. If you were willing, I'll pay more attention to you and help you get more involved in the community:-)

Thank you very much, that's my honour, sir.

I'm very interested in [RIP-19](https://github.com/apache/rocketmq/wiki/%5BRIP-19%5D-Server-side-rebalance,--lightweight-consumer-client-support) and other **RIPs**, looking forward to participating, including document writing, feature development, unit test etc.

**Comment by vongosling** [comment]
Actually, RIP-19  is our first serverless step. I noticed you have addressed in our another task. https://github.com/apache/rocketmq-externals/issues/568. IMO, we could resolve the millions of the dynamic queue, broker, including node level scale-out in production env. No messaging solutions could resolve it perfectly now, we could have a try.

**Comment by XiaoyiPeng** [comment]
> 

I Get it, very much looking forward to it!

**Pull request merged**
