### PR TITLE
[ISSUE #2476] Fix HaClient Infinite loop

### PR DESCRIPTION
**Pull request by crazywen**
try to fix epollwait no block, trash selector, regen it!

## What is the purpose of the change

fix epollwait no block
[https://github.com/apache/rocketmq/issues/2487](url)

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by dongeforever** [comment]
@crazywen  The original reason is that the HAClient.READ_MAX_BUFFER_SIZE muse be equal or larger than the haTransferBatchSize.

Otherwise, the slave HAClient cannot read all the data to byteBufferRead as it has been full already, and the reallocation will take no effect, the new buffer will still be full.

image

**Comment by dongeforever** [comment]
@crazywen It is not a good way to fix the BUFFER SIZE.  You could introduce another config(for example haBufferReadSize) to control the HAClient read buffer size, which is now fixed to 4M by READ_MAX_BUFFER_SIZE.
And then make sure the haTransferBatchSize is equal or smaller than haBufferReadSize.

**Comment by crazywen** [comment]
> @crazywen The original reason is that the HAClient.READ_MAX_BUFFER_SIZE muse be equal or larger than the haTransferBatchSize.
> 
> Otherwise, the slave HAClient cannot read all the data to byteBufferRead as it has been full already, and the reallocation will take no effect, the new buffer will still be full.
> 
> image

**Comment by crazywen** [comment]
> @crazywen It is not a good way to fix the BUFFER SIZE. You could introduce another config(for example haReceiveBatchSize) to control the HAClient read buffer size, which is now fixed to 4M by READ_MAX_BUFFER_SIZE.
> And then make sure the haTransferBatchSize is equal or smaller than haReceiveBatchSize.

**Comment by crazywen** [comment]
> @crazywen It is not a good way to fix the BUFFER SIZE. You could introduce another config(for example haReceiveBatchSize) to control the HAClient read buffer size, which is now fixed to 4M by READ_MAX_BUFFER_SIZE.
> And then make sure the haTransferBatchSize is equal or smaller than haReceiveBatchSize.

haReceiveBatchSize also should have the max size, and the property is valid in slave, and haTransferBatchSize is valid in master, if like what you suggest, the master property should depend on the salve ?

**Comment by dongeforever** [comment]
@crazywen Usually, the config of each node should keep the same in the same cluster(or at least for pair of master-slave which has the same broker name).
If so, just make sure haTransferBatchSize is equal or smaller than haReceiveBatchSize in the config file.

**Pull request closed without merging**
