### PR TITLE
[ROCKETMQ-317] Take advantage of Linux native libaio

### PR DESCRIPTION
**Pull request by lizhanhui**
## What is the purpose of the change

This PR is to make use of the Linux native libaio interfaces in cases where mmap commit log files are no longer in main memory.  Two desired changes, in theory, will be brought about: 1) GC overhead is relieved as data is no longer passed through Java heap; 2) We can continue to use zero-copy.

Discussions are welcome.

The following literature may be informative:

https://activemq.apache.org/artemis/docs/latest/libaio.html
https://www.ibm.com/developerworks/library/l-async/
https://access.redhat.com/documentation/en-us/jboss_enterprise_application_platform/5/html/hornetq_user_guide/libaio
https://stackoverflow.com/questions/8768083/difference-between-posix-aio-and-libaio-on-linux

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/ROCKETMQ/issues/) filed for the change (usually before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ROCKETMQ-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [ ] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by lizhanhui** [comment]
@zhouxinyu @dongeforever @vintagewang

**Comment by zhouxinyu** [comment]
Thanks, this PR really make sense, looking forward to the test result, and we could start code review after that~ 😄

**Comment by githublaohu** [comment]
sorry, English is not good, can only be described in Chinese.

目前使用的 linux aio，解决mmap 映射页面不在，mmap使用直io，造成netty io线程阻塞请求超时。
如果请求的数据在映射页面，那么 linux aio的执行速度，低于 mmap
如果用户使用linux，那么除了最后一个commitLog之外，其他的mmap的文件，没有意义了？

**Comment by lizhanhui** [comment]
@githublaohu 没看懂你的问题, 你再描述下你的疑问?

**Comment by githublaohu** [comment]
@lizhanhui 
读取 mmap的数据，有两种情况，
第一种是 读取的数据，被mmap映射到内存空间了，那么从内存读取
第二种是 读取的数据，的内存空间被刷下了。从而从磁盘读，mmap默认是读取4K，

1. netty io线程阻塞是因为 第二种情况造成的。引入linux aio是解决第二种情况，致使netty io线程阻塞，造成响应慢的情况。
但是也屏蔽掉了第一种情况，数据被mmap映射到内存中的读取速度 比linux aio的读取数据块太多了，

2. ，linux aio 不使用内存，mmap会把数据映射到内存中，而使用大量的内存，在某些情况下，会占用大量的内存，而不使用。

**Comment by vongosling** [comment]
This is an awesome improvement, how are things going?

**Comment by vongosling** [comment]
ping @lizhanhui

**Pull request closed without merging**
