### PR TITLE
changed variables with irregular names

### PR DESCRIPTION
**Pull request by manan1979**
Changed Variables with irregular names and also some other misspelled variables names now changed.

### CODE REVIEW

**Review by mxsm — COMMENTED** [review]
Hi @manan1979  you can create issue first and link this pr to the issue, how to do this you can read this docment:https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue. 
And CI not pass, please check it

**Comment by manan1979** [comment]
okay

**Comment by manan1979** [comment]
got it!

**Comment by tsunghanjacktsai** [comment]
Hey @manan1979 , welcome to the RocketMQ community. We appreciate your first contribution. Don't forget to fix the corresponding code references while making the variable/class name changes. We need to make sure that every PR to be merged passes the CI, where you could find out the workflow details in the list at the bottom of this page.

**Review by caigy — CHANGES_REQUESTED** [review]
Please do be careful to fix 'typo' in configuration keys, as they have been published to users so they can't be changed easily, just like APIs.

This pr is not compatible to older versions. Users will find some configurations are 'lost' or 'rewrite' by unexpected values, after they upgrade from old versions.

**Pull request closed without merging**
