### PR TITLE
[ROCKETMQ-248] make ConsumeFromWhere work right

### PR DESCRIPTION
**Pull request by evthoriz**
JIRA: https://issues.apache.org/jira/browse/ROCKETMQ-248

### CODE REVIEW

**Comment by shroman** [comment]
@evthoriz Thank you. Do you have a test for this?

**Comment by vongosling** [comment]
@evthoriz we usually need some measure to verify our correction, no matter what you do. IMO, unit test is a effective practice when we coding. Looking forward to hear from you again :-)

**Comment by evthoriz** [comment]
@shroman @vongosling It seems that plenty of tests are associated with this modification, I will resubmit a patch when I complete the relevant integration test.

**Comment by vongosling** [comment]
@evthoriz Thanks, looking forward to your patch :-)

**Comment by vongosling** [comment]
@evthoriz  I will close the pr, if you happened to the same question, please let me know.

**Pull request closed without merging**
