### PR TITLE
[ROCKETMQ-334] spinlock performance improvement

### PR DESCRIPTION
**Pull request by fucongchan**
## What is the purpose of the change

spin lock performance improvement

## Brief changelog

CLH spinlock

## Verifying this change

unit-test pass

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/ROCKETMQ/issues/) filed for the change (usually before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ROCKETMQ-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by fucongchan** [comment]
@zhouxinyu @dongeforever @lizhanhui,  Please take a look

**Comment by vsair** [comment]
Hi, could you please show some performance report about this improvement?

**Comment by fucongchan** [comment]
@vsair 
old version
old_version

new version
new_version

Thanks to http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/test/loops/SimpleMutexLoops.java?revision=1.1&view=markup , just replace Mutux to PutMessageSpinLock and make performance test.

**Comment by vongosling** [comment]
@fucongchan Excellent job, we will check your pr soon :-)

**Comment by fucongchan** [comment]
@vongosling and then?

**Comment by zhouxinyu** [comment]
Hi @fucongchan , the performance test is cool, and we need some unit tests for this basic tool~

**Comment by fucongchan** [comment]
@zhouxinyu Well, I will add necessary unit-test soon :)

**Pull request closed without merging**
