### PR TITLE
[ISSUE #1576] Fix logic in select MessageQueue

### LINKED ISSUE #1576: Bug in select MessageQueue
When SendLatencyFaultEnable is enabled and the currently selection is available, you need to make sure that the currently selected broker is not the last selected.
But this judgment is wrong for now:
```java
// MQFaultStrategy#selectOneMessageQueue
MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
    // this judgment shuold be change to if(!mq.getBrokerName().equals(lastBrokerName))
    if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
        return mq;
}
```

### PR DESCRIPTION
**Pull request by ShadowySpirits**
fix #1576

### CODE REVIEW

**Comment by xiangwangcheng** [comment]
LGTM.

**Comment by xiangwangcheng** [comment]
@zongtanghu @duhenglucky 
I also have some confusion about this code. What do u think?

**Comment by ShannonDing** [comment]
link #1593

**Comment by ShannonDing** [comment]
It seems duplicate with #1593

**Pull request closed without merging**
