### PR TITLE
[ISSUE #6943] fix docs typo in docs/cn/controller/design.md #6943

### PR DESCRIPTION
**Pull request by yao-wenbin**
The word ‘falgs’ in [docs/cn/controller/design.md] is wrong.So change it to 'falgs'.

### CODE REVIEW

**Comment by RongtongJin** [comment]
Hi @yao-wenbin Plz create an issue releated the pull request.

**Comment by yao-wenbin** [comment]
This pull request fixes #6943.

**Comment by yao-wenbin** [comment]
> Hi @yao-wenbin Plz create an issue releated the pull request.

Thanks for you comment. I already create a issue #6943 related the pull request.

**Review by yuz10 — APPROVED** [review]

**Review by mxsm — COMMENTED** [review]
@yao-wenbin  Please use fix #xxxx link issue

**Review by TheR1sing3un — APPROVED** [review]

**Pull request merged**
