### PR TITLE
[ISSUE #6525]Make ConsumeQueueInterface extends from FileQueueLifeCycle

### LINKED ISSUE #6525: Make ConsumeQueueInterface extends from FileQueueLifeCycle
The issue tracker is used for bug reporting purposes **ONLY** whereas feature request needs to follow the [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal). To avoid unnecessary duplication, please check whether there is a previous issue before filing a new one.

It is recommended to start a discussion thread in the [mailing lists](http://rocketmq.apache.org/about/contact/) or [github discussions](https://github.com/apache/rocketmq/discussions) in cases of discussing your deployment plan, API clarification, and other non-bug-reporting issues.
We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and self-contained. Otherwise, it would take additional rounds of communication, thus more time, to understand the problem itself.

Generally, fixing an issue goes through the following steps:
1. Understand the issue reported;
1. Reproduce the unexpected behavior locally;
1. Perform root cause analysis to identify the underlying problem;
1. Create test cases to cover the identified problem;
1. Work out a solution to rectify the behavior and make the newly created test cases pass;
1. Make a pull request and go through peer review;

As a result, it would be very helpful yet challenging if you could provide an isolated project reproducing your reported issue. Anyway, please ensure your issue report is informative enough for the community to pick up. At a minimum, include the following hints:

**BUG REPORT**

1. Please describe the issue you observed:

 ConsumeQueue BatchConsumeQueue and SparseConsumeQueue implement interface FileQueueLifeCycle and FileQueueLifeCycle, so the fellow convert will not throw ClassCastException. However, It better to prevent from grammatical level.
image

```java
public interface ConsumeQueueInterface extends FileQueueLifeCycle{
...
}
```

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

### PR DESCRIPTION
**Pull request by Abhijeetmishr**
**Make sure set the target branch to `develop`**

## What is the purpose of the change
close #6525
we are typecasting here
```
 private FileQueueLifeCycle getLifeCycle(String topic, int queueId) {
        return (FileQueueLifeCycle) findOrCreateConsumeQueue(topic, queueId);
    }
```
but interface is not extending FileQueueLifeCycle.
So it will throw typecast error.

### CODE REVIEW

**Comment by ni-ze** [comment]
1. ConsumeQueue also need to modify;
2. The forced convert need to remove.

**Comment by Abhijeetmishr** [comment]
> 1. ConsumeQueue also need to modify;
> 2. The forced convert need to remove.

@ni-ze okay got it.

**Comment by lizhimins** [comment]
赞，我之前也想改这里来着！

**Comment by Abhijeetmishr** [comment]
> Praise, I also wanted to change here before!

@lizhimins didn't get you ?

**Comment by Abhijeetmishr** [comment]
hey @ni-ze I can see some build failures, how do I resolve them any hint/help is appreciated ?

**Comment by ni-ze** [comment]
> 

The build is almost pass, plz check the review suggestion and resolve it.

**Comment by Abhijeetmishr** [comment]
> * ConsumeQueue also need to modify;
> * The forced convert need to remove.

1. ConsumeQueue also need to modify; - checking on this 
1. The forced convert need to remove. - this is done already

**Comment by ni-ze** [comment]
> > * ConsumeQueue also need to modify;
> > * The forced convert need to remove.
> 
> 1. ConsumeQueue also need to modify; - checking on this
> 2. The forced convert need to remove. - this is done already

--------------------
There is another force convert in ConsumeQueueStore.

**Comment by ni-ze** [comment]
@Abhijeetmishr Merge develop into your branch, and then submit pr again, checks will be success.

**Comment by Abhijeetmishr** [comment]
> 

@ni-ze Merge develop into your branch :- you mean to say that take pull from develop branch and to my branch?

**Review by ni-ze — APPROVED** [review]

**Pull request merged**
