### PR TITLE
[idea] Add rocketmq icon to idea.

### PR DESCRIPTION
**Pull request by GOODBOY008**
[idea] Add rocketmq icon to idea.

### CODE REVIEW

**Comment by GOODBOY008** [comment]
I cann't find icon like this.
8Y1W2LGYZ~N(ED8{ ZK4%_F

**Comment by lizhanhui** [comment]
@GOODBOY008 This design looks is from Aliyun commercial product... I am wondering if we will have a copyright issue using it directly.

**Review by lizhanhui — CHANGES_REQUESTED** [review]
Discuss if the copyright of the design is violated

**Comment by GOODBOY008** [comment]
> Discuss if the copyright of the design is violated

Thanks for your remind , We should care about copyright.

**Pull request closed without merging**
