### PR TITLE
[ROCKETMQ-332] fix concurrent bug in MappedFileQueue#findMappedFileByOffset, which m…

### PR DESCRIPTION
**Pull request by Jason918**
## What is the purpose of the change

fix concurrent bug in MappedFileQueue#findMappedFileByOffset, which may cause message loss.

## Brief changelog

The origin bug only occurs when the mappedFileQueue is deleting mappedFiles from the head of the queue. So the main idea of this bug fix is to check if the firstMappedFile in the queue is changed. If it changed, we may get the wrong mappedFile, and we handle this by doing retries. 

Finally, If it failed after 3 times, we will try to find the mappedFile by iterating through all the mappedFiles in the queue to ensure returning the right result (solution from zhouxinyu).

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/ROCKETMQ/issues/) filed for the change (usually before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ROCKETMQ-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by Jason918** [comment]
@zhouxinyu hi~ Sorry for the delay. This is my fix for this bug in our production environment, please check this out. It's been so far so good. :)

**Comment by Jason918** [comment]
@zhouxinyu @dongeforever The continuous-integration failed in the rocketmq-remoting module, which is not modified in this PR. There seem to be some TLS related error. Any ideas ?

**Comment by mark800** [comment]
Yes, the source code on master branch can't pass unit test
It seems the cert files need to be renewed

**Comment by zhouxinyu** [comment]
Please open PR based on the `develop` branch

**Comment by Jason918** [comment]
@zhouxinyu The `master` branch has fixed the cert problem and I have merged the commit into this PR.  Is it OK that i'm still using this PR？

**Comment by lizhanhui** [comment]
@Jason918 Pull requests should be created against the `develop` branch instead of master.

**Comment by lizhanhui** [comment]
After reviewing the solution , I find the proposing fix is kind of cumbersome. Can we simply introducting a read-write lock to guard the `mappedFiles` list?  The collection is definitely read-intensive and should not bring about much overhead when guarded with a read-write lock.

**Comment by vongosling** [comment]
I will close the pr, if you happened to the same question, please let me know.

**Pull request closed without merging**
