### PR TITLE
[ISSUE #7567] transactionProducer get the topic route before sending the message

### PR DESCRIPTION
**Pull request by panzhi33**
### Which Issue(s) This PR Fixes

Fixes #issue_id

### CODE REVIEW

**Review by joeCarf — APPROVED** [review]
LGTM

**Review by joeCarf — COMMENTED** [review]
you may link this PR to your issue

**Comment by panzhi33** [comment]
> you may link this PR to your issue



> you may link this PR to your issue

#7567

**Review by lizhanhui — APPROVED** [review]
Looks good

**Pull request merged**
