### PR TITLE
[ISSUE #2986] Support for multiple ACL files in a fixed directory

### PR DESCRIPTION
**Pull request by sunxi92**
Support for multiple ACL files in a fixed directory
#2986

### CODE REVIEW

**Comment by sunxi92** [comment]
please ignore the branch named acl temp

**Comment by sunxi92** [comment]
@zongtanghu  I don't know if UT has been passed, could you help me confirm it，thx.

**Comment by zhangjidi2016** [comment]
@sunxi92 Please set the target branch to develop

**Comment by duhenglucky** [comment]
@sunxi92 Would you like to resolve conflicts first?

**Comment by sunxi92** [comment]
> conflicts
Done!

**Comment by sunxi92** [comment]
> @sunxi92 Would you like to resolve conflicts first?

Done!

**Comment by Aaron-He** [comment]
Good job. But this PR includes too many code style modifications, it will be better to  import the rmq_codeStyle.xml to your IDE

**Comment by ShannonDing** [comment]
close due to new PR

**Comment by duhenglucky** [comment]
new PR：_https://github.com/apache/rocketmq/pull/3761_

**Pull request closed without merging**
