### PR TITLE
[ISSUE #3785] MQClientAPIImpl improvement

### PR DESCRIPTION
**Pull request by Kvicii**
For this class, I see a lot of switch...case blocks, and it's not necessary.Code clutter caused by excessive nesting.
So I merged all the code,but here is another problem,exceptions thrown in switch...case are not the same, so I think if further abstraction is needed.

### CODE REVIEW

**Comment by Kvicii** [comment]
@duhenglucky hi, I modify this class, As I marked in the commit, do we need to further abstract a top-level exception class and a general checkXXX method

**Comment by Kvicii** [comment]
Can anyone help me review the code?
thx

**Comment by dongeforever** [comment]
@Kvicii  It is better to keep the same code style in MQClientAPIImpl.
Of course, the switch style has disadvantages such as excessive nesting, but it also has advantages. For the RPC layer, the switch style is more readable to handle different kinds of response code and easy to extend further codes.

**Comment by dongeforever** [comment]
@Kvicii The exceptions are a true problem.
It is better to provide a unified exception definition for all the APIs. 
If you are interested, you could collect all the exception types, and introduce a new definition.
The HTTP error code could be a reference, 4xx for client error, 5xx for broker error.

**Comment by Kvicii** [comment]
@dongeforever 
thx
First of all, I think that too many cases cause the code to be unreadable and confusing. If only one of the states needs to be judged, I think redundant judgments can be avoided.
Secondly, is the exception design only for client-related APIs?

**Comment by dongeforever** [comment]
@Kvicii Currently the community is developing the 5.0. Changing the basic exception mechanism may cause bugs and conflicts. It's better to hold on for the moment.

How about involving in the 5.0 rips(if it is at your convenience)

https://github.com/apache/rocketmq/blob/5.0.0-alpha/docs/cn/statictopic/RocketMQ_Static_Topic_Logic_Queue_%E8%AE%BE%E8%AE%A1.md

**Comment by Kvicii** [comment]
Of course.

**Pull request closed without merging**
