### PR TITLE
[ISSUE #7552] Fix local mode by making ext-headers remoting protocol compliant

### LINKED ISSUE #7552: [Bug] Local Mode cannot work properly without necessary remoting ext-headers accessible
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

N/A

### RocketMQ version

N/A

### JDK Version

N/A

### Describe the Bug

N/A

### Steps to Reproduce

Run the following integration test src/test/java/org/apache/rocketmq/test/grpc/v2/LocalGrpcIT

### What Did You Expect to See?

Test should pass 

### What Did You See Instead?

Test failed

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lizhanhui**
fix #7552 

fixed LocalGrpcIT

### CODE REVIEW

**Review by joeCarf — APPROVED** [review]
LGTM

**Review by joeCarf — COMMENTED** [review]
seems that this pr can be closed now

**Comment by drpmma** [comment]
LGTM

**Comment by lizhanhui** [comment]
> seems that this pr can be closed now

**Pull request closed without merging**
