### PR TITLE
Fix Error architecture image with error content

### PR DESCRIPTION
**Pull request by fyeeme**
Fix error draw on architecture image 

The detail is on #2686

### CODE REVIEW

**Comment by fyeeme** [comment]
#2686 Can be closed after this or is merged
@ShannonDing

**Comment by fyeeme** [comment]
diff of the pic 
image

**Comment by duhenglucky** [comment]
good catch！

**Review by duhenglucky — APPROVED** [review]

**Review by ShannonDing — APPROVED** [review]
LGTM

**Pull request merged**
