### PR TITLE
skip encode null value property as string "null"

### PR DESCRIPTION
**Pull request by carlvine500**
skip encode null value property as string "null"

## What is the purpose of the change

send msg property(x=null), but receive msg property(x="null")

### CODE REVIEW

**Comment by vongosling** [comment]
@carlvine500  It would be helpful to verify this problem if you could add test case :-) I am willing to help you merge this pr.

**Comment by carlvine500** [comment]
@vongosling there is a new test case for MessageDecoder now

**Comment by ShannonDing** [comment]
link #1899

**Comment by ShannonDing** [comment]
closed due to #1899

**Pull request closed without merging**
