### PR TITLE
[ISSUE #7267]fix : Failed to obtain semaphore before sending request and threw an error exception

### PR DESCRIPTION
**Pull request by CLFutureX**
### Which Issue(s) This PR Fixes
[issue](https://github.com/apache/rocketmq/issues/7267)

Fixes #issue_id

### CODE REVIEW

**Review by mxsm — COMMENTED** [review]
@jimjag Please link this pr to issue

**Comment by RapperCL** [comment]
> @jimjag Please link this pr to issue

Okay

**Review by joeCarf — COMMENTED** [review]
IMO, the `timeoutMillis` stands for the time-limit, there should be timeoutException only when time-limit is above 0; if the time limit is 0, it is not a timeout. So i think the original way has no problem

**Comment by RapperCL** [comment]
> IMO, the `timeoutMillis` stands for the time-limit, there should be timeoutException only when time-limit is above 0; if the time limit is 0, it is not a timeout. So i think the original way has no problem

However, in the current context semantics, timeout represents the remaining time of the current operation. Moreover, the underlying timeout time is usually mandatory and should not be less than 0, unless in higher application layers, we can set it as follows: when the timeout is less than 0, we set a default timeout time.

**Comment by joeCarf** [comment]
`timeout represents the remaining time of the current operation` only when `acquired` is false, which means too many request comes in and over the limit

**Comment by RapperCL** [comment]
> `timeout represents the remaining time of the current operation` only when `acquired` is false, which means too many request comes in and over the limit

When timeoutMillis is greater than 0, if tryAcquire fails, does it not mean that requests are more frequent at this time？

**Comment by RapperCL** [comment]
> `timeout represents the remaining time of the current operation` only when `acquired` is false, which means too many request comes in and over the limit

I want to throw a timeout exception when timeout<=0, considering that the previous operation consumed too much time, resulting in a direct interruption after obtaining the semaphore failed

**Pull request closed without merging**
