### PR TITLE
remove no need code while init Hashmap

### PR DESCRIPTION
**Pull request by zhenxianyimeng**
## What is the purpose of the change

remove no need code while init Hashmap

## Brief changelog
remove String, HashMap<String, String> in Hashmap init         new HashMap<String, HashMap<String, String>>();

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [1] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by liuruiyiyang** [comment]
Please merge to develop branch :)

**Comment by moveaxebx** [comment]
Diamond types are not supported at jdk1.6

**Comment by ahuazhu** [comment]
> Diamond types are not supported at jdk1.6

RocketMQ required jdk1.8  in the root pom.xml.

```
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
```

Furthermore, how about declare the type of field `configTable`  as `Map`?

Change 
```
private final HashMap<String/* Namespace */, HashMap<String/* Key */, String/* Value */>> configTable =	    private final HashMap<String/* Namespace */, HashMap<String/* Key */, String/* Value */>> configTable =
        new HashMap<String, HashMap<String, String>>()
```

To 

```
configTable =	    private final Map<String/* Namespace */, HashMap<String/* Key */, String/* Value */>> configTable =
        new HashMap<>();
```

**Comment by moveaxebx** [comment]
I agree with u ，and you could try to communicate with the community commiter

**Comment by zhenxianyimeng** [comment]
> Please merge to develop branch :)

ok i will make a new pr

**Pull request closed without merging**
