### PR TITLE
[ISSUE #8476] Add test cases for org.apache.rocketmq.common.attribute

### LINKED ISSUE #8476: [Enhancement] Add test cases for org.apache.rocketmq.common.attribute
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add test cases for org.apache.rocketmq.common.attribute

### Motivation

for issue https://github.com/apache/rocketmq/issues/8262 , add test cases for common module

### Describe the Solution You'd Like

create new test case by using tongyilingma and add comments.

### Describe Alternatives You've Considered

NULL

### Additional Context

With the ability of Tongyi Lingcode, the code test coverage of all modules of the supplementary project reached more than 50%.

### PR DESCRIPTION
**Pull request by TeFuirnever**
### Which Issue(s) This PR Fixes

[Enhancement] Add test cases for org.apache.rocketmq.common.attribute #8476

Fixes #8476

### Brief Description

Add more test coverage for Add test cases for org.apache.rocketmq.common.attribute.

### How Did You Test This Change?

run test case successfull.
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by TeFuirnever** [comment]
for soc in https://github.com/apache/rocketmq/issues/8262 .

**Review by TheR1sing3un — APPROVED** [review]

**Review by ShannonDing — APPROVED** [review]

**Comment by TeFuirnever** [comment]
Hello, is there something wrong with this test item（Build and Run Tests by Bazel / bazel-compile (ubuntu-latest) (pull_request)）?
image

**Comment by TeFuirnever** [comment]
> Hello, is there something wrong with this test item（Build and Run Tests by Bazel / bazel-compile (ubuntu-latest) (pull_request)）? image

I've seen what appears to be a lot of people having this problem.

**Comment by TeFuirnever** [comment]
I see a lot of people having this problem, what can be done to fix it?

**Comment by TheR1sing3un** [comment]
> I see a lot of people having this problem, what can be done to fix it?

This bazel-build check isn't 'required' for pr merging, but u can try to fix these flaky tests if you are interested in this question.

**Comment by TeFuirnever** [comment]
> > I see a lot of people having this problem, what can be done to fix it?
> 
> This bazel-build check isn't 'required' for pr merging, but u can try to fix these flaky tests if you are interested in this question.

Got it, thanks a lot!!!

**Comment by ShannonDing** [comment]
@TeFuirnever A reminder from the Tianchi platform: it‘s better to submit your results to the [official website](https://tianchi.aliyun.com/competition/entrance/532215/information) asap.

**Comment by TeFuirnever** [comment]
> @TeFuirnever A reminder from the Tianchi platform: it‘s better to submit your results to the [official website](https://tianchi.aliyun.com/competition/entrance/532215/information) asap.

Got it, thanks so much! It was a great event!

**Comment by TeFuirnever** [comment]
Hello, how about merged the code, I'm going to move on to other UT tests.
@ShannonDing

**Review by ShannonDing — APPROVED** [review]
LGTM

**Pull request merged**
