### PR TITLE
[ISSUE #4265] Fix query message get wrong result when tls enabled

### PR DESCRIPTION
**Pull request by zhanxuefeng**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Fix query message get the wrong result when tls enabled

## Brief changelog

Correct the return value of WritableByteChannel's write method in FileRegionEncoder

### CODE REVIEW

**Comment by hzh0425** [comment]
Can you create an issue to describe this?

**Comment by zhanxuefeng** [comment]
@hzh0425
The same logs mentioned in [ISSUE #4265](https://github.com/apache/rocketmq/issues/4265)

### FileRegionEncoder
image

I search the same msg mentioned in [ISSUE #4265](https://github.com/apache/rocketmq/issues/4265)
image
Header is 193 bytes and transferred 193 bytes, the 1st msg is 378 bytes and transferred 378 bytes, the 2nd msg is 450 bytes and transferred 450 bytes, total 1021 bytes transferred. 
image
NettyDecoder get 1021 bytes and show the sub trace and pub trace.

**Comment by MatrixHB** [comment]
Good catch for this issue. 

However, this bug involves `QueryMessageProcessor`, which is core function for RocketMQ. I wonder why this bug has never been found. Does it only occur when TLS enabled?

Your code change in `FileRegionEncoder` is very underlying. Could you assess the impact on other upper layer functions？

**Comment by MatrixHB** [comment]
Good catch for this issue. 

> ByteBuffer's capacity is always greater than it's readable bytes

However, this bug involves `QueryMessageProcessor`, which is core function for RocketMQ. I wonder why this bug has never been found. Does it only occur when TLS enabled ?

Your code change in `FileRegionEncoder` is very underlying. Does it affect other upper layer functions？

**Comment by zhanxuefeng** [comment]
@MatrixHB
Yes, the bug only occur when tls enabled, `FIleRegionEncoder` will be add to `NettyRemotingServer`'s ChannelPipline only when tlsModel is enforcing.

### HandshakeHandler
image


`ManyMessageTransfer`, `OneMessageTransfer` and `QueryMessageTransfer` are extend from `FileRegion` in RocketMQ

`OneMessageTransfer` may not occur because it has a header and only one ByteBuffer.

But `ManyMessageTransfer` has the problem too, which involves `PullMessageProcessor`, I'll show the test later.

**Comment by zhanxuefeng** [comment]
Test `ManyMessageTransfer`

RocketMQ version: 4.9.3
tls.server.mode: enforcing
transferMsgByHeap=false   this is very important

The topic I created has 1 writeQueueNums and 1 readQueueNums, and I send 2 msgs to the topic.


I add some logs.
### PullMessageProcessor
image
### ManyMessageProcessor
image

### A simple pull consumer
image

### Console log
image
### Consume log
image

Similar to [ISSUE #4265](https://github.com/apache/rocketmq/issues/4265)
610 bytes and 2 msgs was found, but only transferred 413(216 header + 197 1st msg) bytes, because 768(256 capacity + 512 capacity) > 610, so the 2nd msg will not be transferred.
The consume get 413 but 610(4 length + 606 data) needed, so not msg received.

**Comment by zhanxuefeng** [comment]
Prove `ManyMessageProcessor`

With my code changed in `FileRegionEncoder`
image
### Console log
image
### Consumer log
image

One header and 2 msgs were transferred, and consumer received 610 bytes, decode to 2 msgs.

**Review by tsunghanjacktsai — APPROVED** [review]

**Pull request closed without merging**
