### PR TITLE
Disscuss about hash algorithm in message queue selector ,dev

### PR DESCRIPTION
**Pull request by xiaobing395845388**
## What is the purpose of the change

hash algorithm with hashmap of Java 8 is better, algorithm is hashcode ^ (hashcode >>> 16)

## Brief changelog

hash algorithm with hashmap of Java 8 is better, algorithm is hashcode ^ (hashcode >>> 16)

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by xiaobing395845388** [comment]
Can this be merged?

**Comment by ShannonDing** [comment]
Link #1267

**Comment by xiaobing395845388** [comment]
> It would be nice if you can give more verification about this pr, and it may cause compatibility issues during the upgrade process, causing order messages to be out of order.

closed？causing order messages to be out of order？

**Comment by duhenglucky** [comment]
@xiaobing395845388 Thanks for your contribution, and last comment means that it would be nice if you can provide more verification, not only in the performance but also make sure that there's no compatibility (maybe lead to hashed another queue after upgraded to this new version client) issue, and I will reopen this pr for convenient.

**Comment by xiaobing395845388** [comment]
> @xiaobing395845388 Thanks for your contribution, and last comment means that it would be nice if you can provide more verification, not only in the performance but also make sure that there's no compatibility (maybe lead to hashed another queue after upgraded to this new version client) issue, and I will reopen this pr for convenient.

I had accepted what you are worrying about.  About history message before and new message using this algorithm.  

 But the  algorithm before, for example  config queues of topic 32 ,then config 128
example code
 indexForQueue(32, "a283c3d1616d4de39424da4a47e4b620")  return    5
 indexForQueue(128, "a283c3d1616d4de39424da4a47e4b620")  return   69

this cased same key select different queue

but by the algorithm i commited, same key always be sended to the  same queue

Can this both selector be lived and client choose one to use in different sence?

**Pull request closed without merging**
