### PR TITLE
[ISSUE #7406] UtilAllTest#testCalculateFileSizeInPath can't delete testfile #…

### LINKED ISSUE #7406: [Bug] UtilAllTest#testCalculateFileSizeInPath can't delete testfile
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

MacOS12

### RocketMQ version

develop

### JDK Version

jdk8

### Describe the Bug

UtilAllTest#testCalculateFileSizeInPath
can't pass test

Because the file was not deleted when the method ended

image

### Steps to Reproduce

just run 

### What Did You Expect to See?

.

### What Did You See Instead?

.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by shirenchuang**
…7406

### Which Issue(s) This PR Fixes

Fixes #7406

### CODE REVIEW

**Review by joeCarf — COMMENTED** [review]
suggest naming this pr as `[ISSUE #xxxx] xxxxx`

**Comment by lizhimins** [comment]
https://github.com/apache/rocketmq/pull/7419 这个是不是更好

**Comment by shirenchuang** [comment]
> #7419 这个是不是更好

都行。那个合并了的话，那就关闭这个

**Comment by lizhanhui** [comment]
Close as #7419 is already merged

**Comment by lizhanhui** [comment]
Close as #7419 is already merged

**Pull request closed without merging**
