### PR TITLE
[ISSUE #3229] check running status when schedule new DeliveryMessageTimerTask.

### PR DESCRIPTION
**Pull request by WJL3333**
when ScheduleMessageService stoped. the timer canceled. and new schedule task will cause exception.
then show "ScheduleMessageService, messageTimeup execute error, drop it. msgExt" in log.

### CODE REVIEW

**Review by panzhi33 — APPROVED** [review]

**Comment by ltamber** [comment]
+1

**Comment by Git-Yang** [comment]
Can you resolve the conflict？

**Comment by ShannonDing** [comment]
file conflicted now, it is better to resolve it first.

**Review by ShannonDing — COMMENTED** [review]
The optimization here is very good, but the code conflict problem needs to be solved first.

**Pull request closed without merging**
