### PR TITLE
[ISSUE#5331] Fix windows can't move file when mmapped.

### PR DESCRIPTION
**Pull request by echooymxq**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Link https://github.com/apache/rocketmq/issues/5331

```
Failed tests: 
  CompactionLogTest.testReplaceFiles:259->lambda$testReplaceFiles$3:260
```
https://github.com/apache/rocketmq/actions/runs/3335676387/jobs/5520208604
## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by lizhanhui** [comment]
Looks like we cannot verify the fix in CI as it keeps failing...

**Comment by lizhanhui** [comment]
@echooymxq  Let's work it out this way: [PR5345](https://github.com/apache/rocketmq/pull/5345) makes all pipelines pass through conditionally skipping test cases that are not compatible with Windows at the present. Let's merge that pull request first, then rebase this pull request, which essentially fixes some failing cases.

**Comment by lizhanhui** [comment]
> > Looks like we cannot verify the fix in CI as it keeps failing...
> 
> The ci failed because of other unstable tests, i will fixing in other prs, you can verify it if you use windows. But this change point is notable, it will cause jvm crash when use the mmaped buffer if has cleaned, so i remapped here. @lizhanhui @ltamber Can help reveiw it?

This pull request itself is good and helpful. As I just replied, let's merge it after pull-request 5345

**Comment by echooymxq** [comment]
Got it.

**Review by lizhanhui — APPROVED** [review]

**Pull request merged**
