### PR TITLE
[ISSUE #3786] fix: The length of properties value should be checked before converting them to short.

### PR DESCRIPTION
**Pull request by XiaoyiPeng**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

For issue #3786

### CODE REVIEW

**Review by dongeforever — APPROVED** [review]

**Comment by dongeforever** [comment]
Great Catch.
The check was done for a single message, but not for the batch mode.

**Review by duhenglucky — APPROVED** [review]

**Comment by XiaoyiPeng** [comment]
> Great Catch. The check was done for a single message, but not for the batch mode.

Yes, thanks for your review.

**Comment by tianliuliu** [comment]
Whether to add more information to the RuntimeException message, such as the current prop length, limit length...

**Comment by XiaoyiPeng** [comment]
> Whether to add more information to the RuntimeException message, such as the current prop length, limit length...

Thanks for your advice, I've corrected it.

For commit in class `CommitLog`, in order to keep the **code style consistent**, the properties length limit is only recorded in the log, and the exception message is consistent with the code style below: 

image

**Review by panzhi33 — APPROVED** [review]

**Review by duhenglucky — APPROVED** [review]

**Pull request merged**
