### PR TITLE
[ISSUE #8970] Remove redundant heartbeats

### PR DESCRIPTION
**Pull request by weihubeats**
https://github.com/apache/rocketmq/issues/8970

### CODE REVIEW

**Review by RongtongJin — DISMISSED** [review]

**Comment by RongtongJin** [comment]
LGTM

**Comment by qianye1001** [comment]
it is used to make sure any proxy can receive heartbeat request before receive send or pull request when some proxy services share LB

**Review by lizhimins — CHANGES_REQUESTED** [review]
Please look the previous comment

**Comment by weihubeats** [comment]
> it is used to make sure any proxy can receive heartbeat request before receive send or pull request when some proxy services share LB

Can you give me an example?

**Comment by qianye1001** [comment]
> > it is used to make sure any proxy can receive heartbeat request before receive send or pull request when some proxy services share LB
> 
> Can you give me an example?

you can see how GO_AWAY works in remoting protocol to make proxy shutdown gracefully
[https://github.com/apache/rocketmq/issues/8599](https://github.com/apache/rocketmq/issues/8599)

when client receive GO_AWAY from proxy, client will reconnect proxy and send heartbeat first.

**Comment by weihubeats** [comment]
@qianye1001 How does this sit with you

**Comment by RongtongJin** [comment]
> LGTM

Sorry, I didn't realize it would affect the lossless release code

**Comment by weihubeats** [comment]
> Heartbeats are sent to the broker during client start, rebalancing, scheduled tasks, and Channel creation. A locking is used to prevent duplicate heartbeat transmissions. This is a reasonable solution. Add more complex logic to ensure no additional heartbeats are sent would lead to difficulties in understanding and increased maintenance costs.
> 
> if only need prevent warning log, it is more recommended to ignore locking failure or check lock stats before send Heartbeat when Channel creation.

I have added a strictLockMode parameter to the sendHeartbeatToBroker method to control whether to log lock acquisition failures. When strictLockMode is true, the system will log lock acquisition failures; when false, these failures will be silently ignored.

**Review by qianye1001 — APPROVED** [review]
LGTM

**Comment by qianye1001** [comment]
@lizhimins

**Comment by weihubeats** [comment]
@lizhimins

**Comment by weihubeats** [comment]
@lizhimins Can you help me review this merge request

**Pull request merged**
