### PR TITLE
[ISSUE apache#4858] add consumer type check for message direct push

### PR DESCRIPTION
**Pull request by YangJodie**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

#4858 Add consumer type check when call consumeMessageDirectly

## Brief changelog

1. Add check for QueryMsgByUniqueKeySubCommand and QueryMsgByIdSubCommand.
2. Add type checking when call the org.apache.rocketmq.client.impl.factory.MQClientInstance#consumeMessageDirectly.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by tsunghanjacktsai — APPROVED** [review]

**Review by lizhanhui — COMMENTED** [review]
Having this validation on the broker side might be a better alternative... https://github.com/apache/rocketmq/issues/4858#issuecomment-1221706786

**Review by ShannonDing — COMMENTED** [review]
it's better to to update the test case in QueryMsgByUniqueKeySubCommandTest.

**Comment by zhouxinyu** [comment]
> 

IMO, this PR can avoid type cast exception, we can merge it and add the validation on the server side in the next PR.

**Review by zhouxinyu — APPROVED** [review]

**Comment by RongtongJin** [comment]
Tests in error: 
  QueryMsgByUniqueKeySubCommandTest.testExecute:242 » SubCommand QueryMsgByUniqu...

Hi @YangJodie the CI needs to pass.

**Pull request merged**
