### PR TITLE
[ROCKETMQ-255] Fix offsetStore being null after consumers start()

### PR DESCRIPTION
**Pull request by lizhanhui**
Associated JIRA ticket is: https://issues.apache.org/jira/browse/ROCKETMQ-255

### CODE REVIEW

**Comment by vongosling** [comment]
I created this thread just to address some unit test naming problem. Do we need normalize here ? naming are various nowadays, IMO, methodTest_condition or testMethond_condition may be a good practice, thoughts?

**Comment by lizhanhui** [comment]
Normalize the naming is surely good to have. I'd update the naming soon.

**Comment by dongeforever** [comment]
LGTM @zhouxinyu @vsair @Jaskey please help do a review?

**Comment by Jaskey** [comment]
+1 
Thanks!

**Comment by dongeforever** [comment]
@lizhanhui This  PR has been merged. You could close it now.

**Pull request closed without merging**
