### PR TITLE
#fix spelling mistakes about 'unknown'

### PR DESCRIPTION
**Pull request by chunyizanchi**
“UNKNOWN”  in LocalTransactionState spell error

### CODE REVIEW

**Comment by chunyizanchi** [comment]
1334 line in DefaultMQProducerImpl   also need to be corrected

**Comment by ni-ze** [comment]
ResponseCode,MQClientAPIImpl,DefaultMQPullConsumerImpl also need to be corrected.

**Comment by lwclover** [comment]
The precise coder.

**Review by yuz10 — DISMISSED** [review]

**Review by caigy — APPROVED** [review]

**Review by tianliuliu — DISMISSED** [review]
LGTM

**Review by Oliverwqcwrw — APPROVED** [review]

**Pull request closed without merging**
