### PR TITLE
[ISSUE #4755] Some improvement about branch management

### LINKED ISSUE #4755: Some suggestions about branch management
Some suggestions about the branch management.

1. Protect the `master` and `develop` branch to prevent force push.
2. Disable the merge button of each pull request, `git rebase` should be preferred.

### PR DESCRIPTION
**Pull request by aaron-ai**
Fixes #4755

### CODE REVIEW

**Comment by lizhanhui** [comment]
Looks good. 
+1

**Review by lizhanhui — APPROVED** [review]

**Review by duhenglucky — APPROVED** [review]
LGTM~, Maybe more labels can be attached to RocketMQ, Messaging, Streaming, Eventing, CloudNative, etc.

**Comment by aaron-ai** [comment]
> LGTM~, Maybe more labels can be attached to RocketMQ, Messaging, Streaming, Eventing, CloudNative, etc.

done.

**Comment by vintagewang** [comment]
I was wondering if this "required_approving_review_count" would be more appropriate to set up to 2 and wanted to hear from other people.

**Comment by lizhanhui** [comment]
@vintagewang 

Actually, 2 is practically the number Google takes internally. Here is reason they give

> In practice, most code reviews that require more than one approval usually go through a two-step process: gaining an LGTM from a peer engineer, and then seeking approval from appropriate code owner/readability reviewer(s). This allows the two roles to focus on different aspects of the code review and saves review time. The primary reviewer can focus on code correctness and the general validity of the code change; the code owner can focus on whether this change is appropriate for their part of the codebase without having to focus on the details of each line of code. An approver is often looking for something different than a peer reviewer, in other words. After all, someone is trying to check in code to their project/directory. They are more concerned with questions such as: “Will this code be easy or difficult to maintain?” “Does it add to my technical debt?” “Do we have the expertise to maintain it within our team?”

> If all three of these types of reviews can be handled by one reviewer, why not just have those types of reviewers handle all code reviews? The short answer is scale. Separating the three roles adds flexibility to the code review process. If you are working with a peer on a new function within a utility library, you can get someone on your team to review the code for code correctness and comprehension. After several rounds (perhaps over several days), your code satisfies your peer reviewer and you get an LGTM. Now, you need only get an owner of the library (and owners often have appropriate readability) to approve the change. 

See https://abseil.io/resources/swe-book/html/ch09.html#code_review-id00002

**Pull request merged**
