### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by fusiming**
## What is the purpose of the change

RocketMQ Developer Guide doc

## Brief changelog

Add the file named BestPractice.md 

## Verifying this change

no functional change
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by fusiming** [comment]
Add the file BestPractice.md

**Comment by dongeforever** [comment]
@fusiming Please polish the name to describe the purpose of this PR

**Comment by duhenglucky** [comment]
@hutu92 it would be very nice if you could rebase first and make sure this PR only contains your commits history.

**Comment by hutu92** [comment]
> @hutu92 it would be very nice if you could rebase first and make sure this PR only contains your commits history. and please pull this PR to develop branch.

What do you mean, what do you need me to do? I don't know.

**Pull request closed without merging**
