### PR TITLE
[ISSUE #3998] Enable Github Action for CI Build

### LINKED ISSUE #3998: Move CI/CD to GitHub Actions.
GitHub Actions may be a better CI/CD tools, which gets good practice in [rocketmq-client-cpp](https://github.com/apache/rocketmq-client-cpp/tree/main), and it is simpler for java.

### PR DESCRIPTION
**Pull request by aaron-ai**
Fixes #3998

### CODE REVIEW

**Review by tsunghanjacktsai — COMMENTED** [review]
Hi @aaron-ai ,

Sounds good to replace Travis CI with GitHub Actions. Hope we could have more discussions about this within the community.

**Comment by aaron-ai** [comment]
Aha, I agree with that. This pull request is just an initial attempt of the whole CI pipeline.

**Comment by aaron-ai** [comment]
> 

Aha, I agree with that. This pull request is just an initial attempt of the whole CI pipeline. @tsunghanjacktsai

**Comment by lizhanhui** [comment]
The infrastructure of RocketMQ needs improvement urgently. Continuous Integration takes almost an hour to feedback, which is too slow, without counting queuing time.

**Review by lizhanhui — APPROVED** [review]

**Comment by lizhanhui** [comment]
Can we have these two CI pipeline working at the same time during transition phase?

**Review by caigy — APPROVED** [review]

**Pull request merged**
