### PR TITLE
[ISSUE #7848] Fix exception when pop messages with multiple LMQ indexes

### LINKED ISSUE #7848: [Bug] Exception when pop messages with multiple LMQ indexes
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

all

### RocketMQ version

develop

### JDK Version

_No response_

### Describe the Bug

NumberFormatException is thrown when pop messages with multiple LMQ indexes.

image

### Steps to Reproduce

/

### What Did You Expect to See?

/

### What Did You See Instead?

/

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by redlsz**
### Which Issue(s) This PR Fixes

Fixes #7848 

### Brief Description

Parse property PROPERTY_INNER_MULTI_DISPATCH and property PROPERTY_INNER_MULTI_QUEUE_OFFSET.

### How Did You Test This Change?

unit test

### CODE REVIEW

**Comment by leizhiyuan** [comment]
DefaultMQPushConsumerTest failed, but it seems due to GitHub environment issues, need to rerun

**Review by leizhiyuan — APPROVED** [review]

**Review by HScarb — APPROVED** [review]
LGTM

**Review by cserwen — APPROVED** [review]

**Review by lizhimins — APPROVED** [review]

**Comment by HScarb** [comment]
@redlsz could you please re-run the CI tasks?

**Comment by redlsz** [comment]
> @redlsz could you please re-run the CI tasks?

Sure.

**Comment by redlsz** [comment]
> @redlsz could you please re-run the CI tasks?

https://github.com/apache/rocketmq/actions/runs/8750479357/job/24014103256?pr=7863

**Comment by HScarb** [comment]
> > @redlsz could you please re-run the CI tasks?
> 
> https://github.com/apache/rocketmq/actions/runs/8750479357/job/24014103256?pr=7863 image
> 
> @HScarb Still failed. It seems to be related to the macos version.

I fixed CI tasks, you can rebase on develop branch and force push to your branch to trigger CI tasks again

**Review by caigy — APPROVED** [review]

**Pull request merged**
