### PR TITLE
bugfix SelectMessageQueueByRandom.java

### PR DESCRIPTION
**Pull request by swwlqw**
1)`random.nextInt()` may return `Integer.MIN_VALUE`, while `Math.abs(Integer.MIN_VALUE)=Integer.MIN_VALUE` is also negative.
2) fix spelling mistake.

### CODE REVIEW

**Comment by dongeforever** [comment]
@swwlqw Thanks for your contribution. It will be nice if following the PR style of https://rocketmq.apache.org/docs/pull-request/#check-list-for-a-pr.

**Comment by dongeforever** [comment]
@swwlqw I want to merge this PR. Could you please polish the PR style described  in https://rocketmq.apache.org/docs/pull-request/#check-list-for-a-pr?

**Comment by dongeforever** [comment]
@swwlqw If you want to polish the merge_rocketmq_pr.py, please submit another PR.
BTW,  it seems that you haven't done the check-list for a PR according to  https://rocketmq.apache.org/docs/pull-request/#check-list-for-a-pr ?

**Comment by zhouxinyu** [comment]
I changed the base branch of this PR, please @swwlqw help squash commits.

**Comment by zhouxinyu** [comment]
merged!

**Pull request closed without merging**
