### PR TITLE
[ISSUE #3684] change client jdk version to 1.6

### PR DESCRIPTION
**Pull request by duhenglucky**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by panzhi33 — APPROVED** [review]

**Review by HScarb — APPROVED** [review]

**Review by Git-Yang — APPROVED** [review]

**Review by caigy — APPROVED** [review]

**Comment by vongosling** [comment]
What is this? For traditional cloud customers, you could create a release branch. Or say, you cancel JDK8 some special semantics, release two packages, one of them is backporting 1.6.

**Review by dongeforever — APPROVED** [review]

**Comment by dongeforever** [comment]
If there is no other significant reason, it is better to keep 1.6 for the client, to be compatible with traditional enterprise users.

**Comment by vongosling** [comment]
You can calculate the percentage of traditional enterprises in your customers？ If you could learn more life-cycle governance about production, you could not insist on this solution. I have given you another backport way to support and educate enterprise customers. I think we have many of these customers in ours. Pls remember, Open source doesn't kidnap by our business. You can support innovation and smooth upgrades in a more collaborative way.

**Comment by dongeforever** [comment]
@vongosling I insist on it unless there is a significant reason.

If it doesn't gain too much value in the upgrading of the client version,  why should we do that?  Why not give more convenience to users?

If you want to change the version, please show the use cases and explain the values.

**Review by odbozhou — APPROVED** [review]

**Pull request merged**
