### PR TITLE
[ISSUE #5471] Fix AutoSwitchRoleIntegrationTest still experience random failures

### LINKED ISSUE #5471: AutoSwitchRoleIntegrationTest still experience random failures
AutoSwitchRoleIntegrationTest.testChangeMaster:171->AutoSwitchRoleBase.checkMessage:188 » ConditionTimeout

See https://github.com/apache/rocketmq/actions/runs/3399844807/jobs/5653863234

### PR DESCRIPTION
**Pull request by RongtongJin**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Close #5471 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by lizhanhui** [comment]
@RongtongJin Is this pull-request still work-in-progress? Its title contains WIP while it remains inactive for some time

**Review by hzh0425 — DISMISSED** [review]

**Comment by hzh0425** [comment]
LGTM @RongtongJin

**Comment by RongtongJin** [comment]
> @RongtongJin Is this pull-request still work-in-progress? Its title contains WIP while it remains inactive for some time

@lizhanhui Yes, I have been busy recently, but I will continue to fix it until it is stable.

**Comment by RongtongJin** [comment]
Hi, @lizhanhui I have found some reasons, mainly because the previous test did not clean up the resources. It has been repaired, and the same error has not yet occurred. So I suggest merging this PR and continuing to observe.

**Review by hzh0425 — APPROVED** [review]
LGTM

**Comment by lizhanhui** [comment]
> Hi, @lizhanhui I have found some reasons, mainly because the previous test did not clean up the resources. It has been fixed, and the same error has not yet occurred. So I suggest merging this PR and continuing to observe.

Good job! Let's merge it and see

**Pull request merged**
