### PR TITLE
Validators.checkMessage() is used twice.

### PR DESCRIPTION
**Pull request by BingCoke**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

The other check is used in sendDefaultImpl
so there is no need to chekMessage in this

### CODE REVIEW

**Review by yuz10 — APPROVED** [review]

**Review by RongtongJin — APPROVED** [review]

**Comment by RongtongJin** [comment]
Is there a related issue that can be associated with this pull request? @BingCoke

**Comment by BingCoke** [comment]
> Is there a related issue that can be associated with this pull request? @BingCoke

no

**Comment by Git-Yang** [comment]
> > Is there a related issue that can be associated with this pull request? @BingCoke
> 
> no

You can create an ISSUE to associate with this pr.

**Review by duhenglucky — APPROVED** [review]

**Comment by BingCoke** [comment]
> > > Is there a related issue that can be associated with this pull request? @BingCoke
> > 
> > 
> > no
> 
> You can create an ISSUE to associate with this pr.

Okay, I get it,i can not edit it now,i will do that next time!

**Comment by ferrirW** [comment]
image

This check is used to avoid NPE?

I think better way to check and set topic with namespace is that move all checkMessage & msg.setTopic to defaultMQProducerImpl.send().

**Pull request merged**
