### PR TITLE
[ISSUE #237] CLH spinlock

### PR DESCRIPTION
**Pull request by pifuant**
Please do not create a Pull Request without creating an issue first. 

## What is the purpose of the change

Spinlock performance improvement

## Brief changelog

CLH spinlock refer to AbstractQueuedSynchronizer.

## Verifying this change

run spinlock unit-test.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by pifuant** [comment]
old version
old

new version
new


Thanks to http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/test/loops/SimpleMutexLoops.java?revision=1.1&view=markup , just replace Mutux to PutMessageSpinLock and make performance test.

**Comment by iamzhoug37** [comment]
@pifuant why use a queue can improve the performance? Can you make a simple description

**Comment by pifuant** [comment]
@iamzhoug37 
Because the compareAndSet call forces other processors to discard their own cached copies of the lock, so every spinning thread encounters a cache miss almost every time, and must fetch the new, but 
unchanged value.

Using CLH queue, a release thread just wakes up next spinning thread than all.

**Comment by iamzhoug37** [comment]
thank you @pifuant

**Pull request closed without merging**
