### PR TITLE
[ROCKETMQ-256] Clean commit log files manually to specified disk usage watermark

### PR DESCRIPTION
**Pull request by lizhanhui**
Associated JIRA ticket is: https://issues.apache.org/jira/browse/ROCKETMQ-256

### CODE REVIEW

**Comment by lindzh** [comment]
Thanks for contribution. As force delete may cause message lost,how about add a warnning in command help? And also add a monitor disk usage tool command for check.

**Comment by lizhanhui** [comment]
1. "As force delete may cause message lost,how about add a warnning in command help?"--->Added.
2. "And also add a monitor disk usage tool command for check." --> I do not follow this comment, could you please  articulate it more specifically?

**Comment by lizhanhui** [comment]
@zhouxinyu @dongeforever please help review this PR.

**Comment by dongeforever** [comment]
@lizhanhui This purge is not be safe for scheduled message.

**Comment by vongosling** [comment]
I will close the pr, if you happened to the same question, please let me know.

**Pull request closed without merging**
