### PR TITLE
[Just for preview, Please not merge yet]Add schema test for api protocol

### PR DESCRIPTION
**Pull request by dongeforever**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

add static tests for API/protocol modifications.

## Brief changelog

- [x] 1. add schema for API/protocols
- [ ] 2. add tests for these schemas'

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by dongeforever** [comment]
@duhengforever Help a review.
If the schema is backup in the test module,  it could be easy to add the API/schema changes to new version release notes.

**Comment by duhenglucky** [comment]
Strongly recommended to add this check to all interfaces to avoid compatibility problems caused by interface changes.

**Comment by lizhanhui** [comment]
Is it a good idea to freeze all interface contracts? According to widely accepted [SemVer](https://semver.org/)

> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards compatible manner, and
> 3. PATCH version when you make backwards compatible bug fixes.

Will this pull request become a burden when the community is having a major release?

**Comment by dongeforever** [comment]
@lizhanhui This is not a burden. This is a tool to trace and check the changes in API/Protocol. Also, it is a notice for the contributors that they should not change the API/Protocol arbitrarily without discussion.

In the future release, each version needs to identify the API/Protocol changes explicitly, otherwise, it may not be approved during the voting thread.

**Comment by lizhanhui** [comment]
OK. Sounds kind of reasonable

**Review by duhenglucky — APPROVED** [review]

**Pull request merged**
