### PR TITLE
[ISSUE #6572] MQAdmin support getKvConfig command

### LINKED ISSUE #6572: MQAdmin tools does not support the getKvConfig command
I think getKvConfig command should be supported
image

### PR DESCRIPTION
**Pull request by ferrirW**
## What is the purpose of the change

fix #6572 

## Brief changelog

add getKvConfig command in MQAdminStartup

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by RongtongJin — APPROVED** [review]

**Review by guyinyou — APPROVED** [review]
lgtm

**Comment by lizhanhui** [comment]
> IMO, we should rethink the KV ability which makes the NameServer component stateful. Actually, it's not recommended to use this feature in the production environment.

I agree. Name servers are not a good place to store till they aggregate consensus into their core. Otherwise, troubleshooting will be very challenging in production.

**Comment by ferrirW** [comment]
> IMO, we should rethink the KV ability which makes the NameServer component stateful. Actually, it's not recommended to use this feature in the production environment.

Yes, I understand your concern, but consider current situation:
1. The defaultMQAdminExt provided KV-related interface currently. Theoretically, users can use this capabilities anyway;
2. The MQAdmin tools provided update and delete capabilities, users like me may just need a convenient way to check if the updateKVConfig operation is effective

So I think we should remove all the associated interfaces **after** we decide that namesrv will no longer play the role of kv.

**Review by hzh0425 — APPROVED** [review]

**Review by mxsm — APPROVED** [review]
LGTM~

**Review by tsunghanjacktsai — APPROVED** [review]

**Review by cserwen — APPROVED** [review]

**Pull request closed without merging**
