### PR TITLE
[ISSUE #3339] (doc)fix typo in update operation.md

### PR DESCRIPTION
**Pull request by WuHang1**
修改中英文档中的笔误

### CODE REVIEW

**Review by ifplusor — APPROVED** [review]
LGTM

**Review by odbozhou — APPROVED** [review]

**Comment by odbozhou** [comment]
please summit  issue first .

**Review by odbozhou — COMMENTED** [review]
please summit issue first .

**Comment by WuHang1** [comment]
> please summit issue first .
Thanks for your attention
I summit a issue https://github.com/apache/rocketmq/issues/3341
but i can't link it to this pr

**Review by ShannonDing — APPROVED** [review]

**Comment by ShannonDing** [comment]
LGTM

**Pull request merged**
