### PR TITLE
[ISSUE #8366] Eliminate deadlocks during the client shutdown process.

### LINKED ISSUE #8366: [Bug] Multiple deadlocks were detected during the client shutdown process.
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

4.19.90-23-42.v2101.ky10.x86_64

### RocketMQ version

5.2.0

### JDK Version

openjdk 1.8

### Describe the Bug

During the client shutdown process, deadlocks were detected, which resolved after a period of time. 
This phenomenon was observed using jvisualvm and jconsole. 
The deadlock occurred between the client shutdown thread and the Netty worker threads.
Code analysis: 

1. `NettyRemotingClient` holds the `lockChannelTables` lock, which is responsible for guarding access to `channelTables`. `channelTables` caches all channels encapsulated in `ChannelWrapper`.
2. The inner class ChannelWrapper within NettyRemotingClient` holds a read-write lock `lock`, responsible for concurrent access to the channel.
3. The inner class `NettyConnectManageHandler` in `NettyRemotingClient` is responsible for handling events like close, connect, and channelInactive. When a channel becomes unavailable, it executes the `close` or `channelInactive` methods to remove the channel from `channelTables`.

截屏2024-07-05 14 11 28
截屏2024-07-05 14 15 06
截屏2024-07-05 14 19 16
截屏2024-07-05 14 26 54
The execution path where deadlock occurs.

截屏2024-07-05 15 38 50

### Steps to Reproduce

WechatIMG49
1.Creating multiple consumer clients and shutting them down one by one. The more clients are created, the more likely a deadlock will be triggered.
2.Open jconsole and continuously click on deadlock detection.[](url)

### What Did You Expect to See?

WechatIMG49
deadlocks were detected.

### What Did You See Instead?

deadlocks were detected.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by YanYunyang**
… a channel, no longer acquire a read lock.

### Which Issue(s) This PR Fixes

Fixes #8366 

### Brief Description
截屏2024-07-05 15 38 50

`ChannelWrapper.getChannel()` needs to hold the read lock. When determining if `ChannelWrapper` is the wrapper for a channel, no longer acquire a read lock.

### CODE REVIEW

**Comment by drpmma** [comment]
https://github.com/apache/rocketmq/blob/32f0e8481d1f5672b8d494de7607fe5b846ffa51/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java#L479-L484

**Review by drpmma — CHANGES_REQUESTED** [review]
There are two closeChannel method.

This piece of code also needs modification.

https://github.com/apache/rocketmq/blob/32f0e8481d1f5672b8d494de7607fe5b846ffa51/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java#L424-L428

**Comment by YanYunyang** [comment]
> https://github.com/apache/rocketmq/blob/32f0e8481d1f5672b8d494de7607fe5b846ffa51/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java#L479-L484
> 
> It seems that this piece of code also may lead to deadlock.

Here is the same channelWrapper. The lock in channelWrapper is reentrant.

**Comment by YanYunyang** [comment]
> There are two closeChannel method.
> 
> This piece of code also needs modification.
> 
> https://github.com/apache/rocketmq/blob/32f0e8481d1f5672b8d494de7607fe5b846ffa51/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java#L424-L428

Here it needs to be changed to `isWrapperOf` to match the meaning. Thank you.

**Comment by drpmma** [comment]
> https://github.com/apache/rocketmq/blob/32f0e8481d1f5672b8d494de7607fe5b846ffa51/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java#L479-L484
> 
> It seems that this piece of code also may lead to deadlock.

how about tryClose method which contains lock.readLock().lock(), it also may lead to deadlock.

**Review by drpmma — APPROVED** [review]
LGTM

**Review by caigy — APPROVED** [review]
LGTM

**Review by RongtongJin — APPROVED** [review]

**Pull request merged**
