### PR TITLE
fix ：#3434

### PR DESCRIPTION
**Pull request by Cczzzz**
I don’t understand why there are changes. I didn’t change the style at all.

### CODE REVIEW

**Comment by Cczzzz** [comment]
> I don’t understand why there are changes. I didn’t change the style at all.
Solved by importing rmq_codeStyle.xml

**Comment by duhenglucky** [comment]
@Cczzzz Would you like to change this PR target branch to develop?

**Comment by Cczzzz** [comment]
> @Cczzzz Would you like to change this PR target branch to develop?

to dev？

**Comment by Cczzzz** [comment]
build fail @duhenglucky ,can you help me ? .

**Comment by Git-Yang** [comment]
> build fail @duhenglucky ,can you help me ? .

[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default-cli) on project rocketmq-client: Too many files with unapproved license: 1 See RAT report in: /home/travis/build/apache/rocketmq/client/target/rat.txt -> [Help 1]

**Comment by Cczzzz** [comment]
I add  license  to client/src/test/java/org/apache/rocketmq/client/consumer/HeartbeatServiceTest .but client/src/main/java/org/apache/rocketmq/client/impl/consumer/HeartbeatService Have it already

**Comment by Cczzzz** [comment]
checks fail ， How do i fix it。

**Comment by Cczzzz** [comment]
Who can help me

**Comment by duhenglucky** [comment]
> Who can help me

CI check passed now

**Comment by Cczzzz** [comment]
why closed

**Comment by Cczzzz** [comment]
> why closed

@vongosling

**Pull request closed without merging**
