### PR TITLE
[ISSUE #7464] Polish the pop logger format

### LINKED ISSUE #7464: [Enhancement] Polish the pop logger format
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Polish the pop logger format
image

### Motivation

Polish the pop logger format

### Describe the Solution You'd Like

Polish the pop logger format

### Describe Alternatives You've Considered

No

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by joeCarf**
### Which Issue(s) This PR Fixes

Fixes #7464

### CODE REVIEW

**Comment by joeCarf** [comment]
@RongtongJin hi~, PTAL

**Review by RongtongJin — COMMENTED** [review]
There are similar issues in other parts of this class. Could you help us modify them together?

**Comment by joeCarf** [comment]
> There are similar issues in other parts of this class. Could you help us modify them together?

of course

**Comment by joeCarf** [comment]
> There are similar issues in other parts of this class. Could you help us modify them together?

done! PTAL

**Pull request merged**
