### PR TITLE
[ISSUE #5963]  Remove the useless exception class: MQRedirectException

### LINKED ISSUE #5963: Remove the useless exception class: MQRedirectException
The exception class MQRedirectException defined in the client package is not used and can be removed.

path：org.apache.rocketmq.client.exception.MQRedirectException

### PR DESCRIPTION
**Pull request by socutes**
The exception class MQRedirectException defined in the client package is not used and can be removed.
path：org.apache.rocketmq.client.exception.MQRedirectException

Fix #5963

### CODE REVIEW

**Comment by socutes** [comment]
@zhouxinyu PTAL

**Comment by mxsm** [comment]
Hey @socutes  you can see this [document ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) how to link issue. You can link a pull request or branch to an issue to show that a fix is in progress and to automatically close the issue when the pull request or branch is merged.

**Comment by socutes** [comment]
> link

Ok，Thanks

**Comment by zhouxinyu** [comment]
LGTM, @aaron-ai Please help check if we have used this class in any runtime env or other repo.

**Review by zhouxinyu — APPROVED** [review]

**Review by RongtongJin — APPROVED** [review]

**Comment by aaron-ai** [comment]
> LGTM, @aaron-ai Please help check if we have used this class in any runtime env or other repo.

it is redundant seemingly.

**Pull request merged**
