### PR TITLE
[ISSUE #6822] Memory lock support Windows Platform

### LINKED ISSUE #6822: [Bug] Memory locking does not support Windows
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

os: windows10

### RocketMQ version

devlop

### JDK Version

1.8

### Describe the Bug

Memory locking does not support Windows

### Steps to Reproduce

1. invoke LibC.mlock() method in windows Platform

### What Did You Expect to See?

Memory locked

### What Did You See Instead?

memory not locked

### Additional Context

_No response_

### LINKED ISSUE #6836: [Feature]  Windows Api not has mlock function, but can Using VirtualLock to Lock Memory
### Describe the Solution You'd Like

Calling the `VirtualLock` function through `jna` in Windows OS

### PR DESCRIPTION
**Pull request by haiyanghan**
Fixes #6836

Implementation of calling the `VirtualLock` function

### CODE REVIEW

**Comment by haiyanghan** [comment]
link issue #4232 
in the issue, @zhouxinyu  proposed the`VirtualLock` function in `Windows OS.`
I found that the `VirtualLock` function also exists in elasticsearch

**Comment by haiyanghan** [comment]
In ES, this code is located at `org/lastcsearch/bootstrap/JNANationals.java`
```java
    static void tryVirtualLock() {
        JNAKernel32Library kernel = JNAKernel32Library.getInstance();
        Pointer process = null;
        try {
            process = kernel.GetCurrentProcess();
            // By default, Windows limits the number of pages that can be locked.
            // Thus, we need to first increase the working set size of the JVM by
            // the amount of memory we wish to lock, plus a small overhead (1MB).
            SizeT size = new SizeT(JvmInfo.jvmInfo().getMem().getHeapInit().getBytes() + (1024 * 1024));
            if (kernel.SetProcessWorkingSetSize(process, size, size) == false) {
                logger.warn("Unable to lock JVM memory. Failed to set working set size. Error code {}", Native.getLastError());
            } else {
                JNAKernel32Library.MemoryBasicInformation memInfo = new JNAKernel32Library.MemoryBasicInformation();
                long address = 0;
                while (kernel.VirtualQueryEx(process, new Pointer(address), memInfo, memInfo.size()) != 0) {
                    boolean lockable = memInfo.State.longValue() == JNAKernel32Library.MEM_COMMIT
                        && (memInfo.Protect.longValue() & JNAKernel32Library.PAGE_NOACCESS) != JNAKernel32Library.PAGE_NOACCESS
                        && (memInfo.Protect.longValue() & JNAKernel32Library.PAGE_GUARD) != JNAKernel32Library.PAGE_GUARD;
                    if (lockable) {
                        kernel.VirtualLock(memInfo.BaseAddress, new SizeT(memInfo.RegionSize.longValue()));
                    }
                    // Move to the next region
                    address += memInfo.RegionSize.longValue();
                }
                LOCAL_MLOCKALL = true;
            }
        } catch (UnsatisfiedLinkError e) {
            // this will have already been logged by Kernel32Library, no need to repeat it
        } finally {
            if (process != null) {
                kernel.CloseHandle(process);
            }
        }
    }
```

**Comment by haiyanghan** [comment]
@zk-drizzle A conflict occurred during the merge process and has now been resolved

**Comment by lizhimins** [comment]
Interesting modifications, but I am not familiar with the mechanisms of Windows

**Pull request closed without merging**
