### PR TITLE
[ISSUE 3585] [Part J] Use MappedByteBuffer instead of FileChannel to …

### PR DESCRIPTION
**Pull request by areyouok**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

speed up reput performance (relative to consumer tps) .

## Brief changelog

 Use MappedByteBuffer instead of FileChannel to write consume queue and slave commitlog.

## Verifying this change

This commit improve reput performance and speed up consume qps greatly. In our test, produce about 200,000 tps.

72 queue consume qps: from about 70,000 to 200,000

600 queue consume qps: from about 70,000 to 110,000

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by areyouok** [comment]
before:

before

after:

after

**Review by caigy — APPROVED** [review]

**Review by panzhi33 — APPROVED** [review]

**Review by yuz10 — APPROVED** [review]

**Review by Git-Yang — APPROVED** [review]

**Review by duhenglucky — APPROVED** [review]

**Review by RongtongJin — APPROVED** [review]

**Comment by kimmking** [comment]
Actually, mmap is better than fileChannel in small size message case. In large scale size message, fileChannel is more better.
There could be an option to switch mmap/fileChannel.
See https://www.jianshu.com/p/d0b4ac90dbcb

**Comment by kimmking** [comment]
As another effect, we found after upgrade to 4.9.4, mmap avoid many swap usage rather than older version with fileChannel.
See https://stackoverflow.com/questions/49996217/filechannel-vs-mappedbytebuffer-in-random-access

**Comment by kimmking** [comment]
As another effect, we found after upgrade to 4.9.4, mmap avoid many swap usage rather than older version with fileChannel.
See https://stackoverflow.com/questions/49996217/filechannel-vs-mappedbytebuffer-in-random-access

**Pull request merged**
