### PR TITLE
[ISSUE #8500] Add more test coverage for RocksDBLmqConsumerOffsetManager

### LINKED ISSUE #8500: [Enhancement] Add more test coverage for RocksDBLmqConsumerOffsetManager
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add more test coverage for RocksDBLmqConsumerOffsetManager

### Motivation

add more test coverage

### Describe the Solution You'd Like

add more test coverage

### Describe Alternatives You've Considered

add more test coverage

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by StudentGu**
### Which Issue(s) This PR Fixes
[Enhancement] Add more test coverage for RocksDBLmqConsumerOffsetManager
Fixes #8500

### Brief Description
Add more test coverage for RocksDBLmqConsumerOffsetManager

### How Did You Test This Change?
run test case successfull.
test

PS: TONGYI Lingma provided code generation and programming support.
通义灵码使用截图

### CODE REVIEW

**Comment by StudentGu** [comment]
@ShannonDing PTAL（Please Take A Look）

**Comment by StudentGu** [comment]
@TeFuirnever PTAL（Please Take A Look）

**Comment by ShannonDing** [comment]
link #8262

**Comment by StudentGu** [comment]
@ShannonDing why calculate-coverage fail?

**Comment by ShannonDing** [comment]
> @ShannonDing why calculate-coverage fail?
welcome to fixing it. 
see more info about it:
https://github.com/apache/rocketmq/issues/8499

**Review by ShannonDing — APPROVED** [review]

**Pull request merged**
