### PR TITLE
MQFaultStrategy optimize

### PR DESCRIPTION
**Pull request by alaric27**
## What is the purpose of the change

selectOneMessageQueue logical optimization
I find this logic useless. When find available MessageQueue can just return

## Brief changelog

delete code if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by ShannonDing** [comment]
Why should this code be moved? IMO, if the message was sent to the message queue failed or timeout, it is better to send the message to another message queue, otherwise, there's a big possibility to send the message to the queue failed again.

**Comment by alaric27** [comment]
> Why should this code be moved? IMO, if the message was sent to the message queue failed or timeout, it is better to send the message to another message queue, otherwise, there's a big possibility to send the message to the queue failed again.

 if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
     if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
         return mq;
 }
这段代码的逻辑是：如果之前没有失败过lastBrokerName为空，或则当前选择MessageQueue的brokerName等于上次失败的brokerName，则返回当前MessageQueue。
这逻辑是有问题的，我认为如果选择的MessageQueue的broker是可用的就可以直接返回。
而且根据notBestBroker选择MessageQueue，这段处理逻辑是否有必要？我认为如果循环messageQueueList没有找到可用的MessageQueue，直接调用tpInfo.selectOneMessageQueue(lastBrokerName) 返回一个MessageQueue即可。

**Comment by BeiKeJieDeLiuLangMao** [comment]
@alaric27 
我分析了一下，不知道对不对。
```
public MessageQueue selectOneMessageQueue(final TopicPublishInfo tpInfo, /*通常情况下，指上次请求失败时用到的节点*/final String lastBrokerName) {
        if (this.sendLatencyFaultEnable) {
            try {
                // 外层轮询，下次请求时会选择下一个队列
                int index = tpInfo.getSendWhichQueue().getAndIncrement();
                for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
                    // index用于内层轮询，从而排除不可用的节点
                    int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
                    if (pos < 0)
                        pos = 0;
                    MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
                    // 验证可用性，latencyFaultTolerance存储了各个Broker发送消息的耗时，已经预估的下次可用时间点
                    if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
                        // 如果是第一次请求，并且可用，则直接返回
                        // 如果是重试请求，则只使用brokerName等于lastBrokerName相同的，这点大家肯定有疑问：为啥要使用上次失败的，其实这里的lastBrokerName不单单指上次发送失败的节点，
                        // 它还能蕴含推荐节点的信息，本函数的后半段中会看到如何将推荐节点的信息传递到lastBrokerName
                        // 但是我觉得这样写的一个弊端是：当前可用节点，如果和上次失败时所用的节点不一致时，就会被排除掉，这也会影响效率
                        if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
                            return mq;
                    }
                }
                // 走到这一步，代表所有节点都不可用（首次请求）或者上一次失败时用到的节点仍然不可用（重试请求）
                // 随后，将所有不可用的节点，按照潜在可用性（当前可用与否>上次使用该节点时的调用耗时>预估的下次可使用时间），进行了排序，然后选择最优的结果
                // 这里不用担心，连续重试时pickOneAtLeast每次都选择了相同节点，因为其内部也是用了轮训机制，会从最优->次优的顺序给出下一次推荐的节点
                final String notBestBroker = latencyFaultTolerance.pickOneAtLeast();
                //getQueueIdByBroker这个函数名也是惊到我了，完全和其功能不匹配，本行代码意在得到推荐节点是否仍然存在可写队列，如果存在，得出队列数
                int writeQueueNums = tpInfo.getQueueIdByBroker(notBestBroker);
                // 我们得到的推荐节点存在可写队列
                if (writeQueueNums > 0) {
                    // 至此我们已经拿到了一个推荐节点，但是接下来代码的作者并没有简单地根据推荐节点来寻找队列，而是靠外层轮训找了下一个队列
                    // 如果在次重试过程中没有发生路由信息更新的话，该队列应该仍然是不可用的，并且很可能仍是最初失败的Broker节点的队列，
                    // 为什么这么说：假如消息队列为[BrokerA1,BrokerA2,BrokerA3,BrokerA4,BrokerB1,BrokerB2],只有当上一次轮训到BrokerA4时，这里才会跳过BrokerA而得到BrokerB的队列
                    // 而且，可能下次更新路由表时，该信息可能就会成为过期数据而被GC，我猜作者是觉得反正这个数据快没用了，不如把它替换成刚才得到的推荐节点信息，这样可以少new一个对象，还能增加下次查找时的效率
                    // 之所以说它能增加效率，是因为这个过程实质上是将一个很可能宕机的节点队列换成了最可能可用的节点信息，那么下次再轮训到这个节点时，实际上就跳过了寻找推荐节点的过程
                    final MessageQueue mq = tpInfo.selectOneMessageQueue();
                    if (notBestBroker != null) {
                        // 把得到的队列的BrokerName改成我们前面得到的推荐节点，这样如果再请求失败并且重试的时候，lastBrokerName其实存储的就是推荐节点的信息了，下次再执行本函数时就会优先使用推荐节点的其他队列
                        mq.setBrokerName(notBestBroker);
                        // 重新计算其队列编号，因为得到的这个队列数可能和推荐节点的队列数不一致，如果用了错误的队列序号，消息发送到Broker那时，肯定会报错
                        // 因此，这里基于外层轮询使用的index，对本次使用的队列编号进行了计算，我觉得这里最终达到的是随机选择的效果
                        mq.setQueueId(tpInfo.getSendWhichQueue().getAndIncrement() % writeQueueNums);
                    }
                    return mq;
                } else { // 推荐节点不存在可写队列了，说明该节点可能已经宕机，并且NameServer已经删除了其路由信息，并且已经同步过来了
                    // 这时候可以将该节点从延迟统计表中删除，不在考虑该节点
                    latencyFaultTolerance.remove(notBestBroker);
                }
            } catch (Exception e) {
                log.error("Error occurred when selecting message queue", e);
            }
            // 如果拿到的推荐节点已经不存在可写队列了，就随机选一个队列
            return tpInfo.selectOneMessageQueue();
        }
        // 默认策略
        return tpInfo.selectOneMessageQueue(lastBrokerName);
    }
```

**Comment by CoderLan0668** [comment]
@alaric27 你理解了这里为啥这样写吗？我在这里也很迷惑，跟你一开始的想法是一样的。

**Comment by CoderLan0668** [comment]
if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
return mq;
}

@ShannonDing   i still do not understand the purpose of the code above。

if latencyFaultTolerance.isAvailable(mq.getBrokerName() && null != lastBrokerName && ！mq.getBrokerName().equals(lastBrokerName)

the mq is good to be selected， is it right？

**Comment by CoderLan0668** [comment]
> @alaric27
> 我分析了一下，不知道对不对。
> 
> ```
> public MessageQueue selectOneMessageQueue(final TopicPublishInfo tpInfo, /*通常情况下，指上次请求失败时用到的节点*/final String lastBrokerName) {
>         if (this.sendLatencyFaultEnable) {
>             try {
>                 // 外层轮询，下次请求时会选择下一个队列
>                 int index = tpInfo.getSendWhichQueue().getAndIncrement();
>                 for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
>                     // index用于内层轮询，从而排除不可用的节点
>                     int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
>                     if (pos < 0)
>                         pos = 0;
>                     MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
>                     // 验证可用性，latencyFaultTolerance存储了各个Broker发送消息的耗时，已经预估的下次可用时间点
>                     if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
>                         // 如果是第一次请求，并且可用，则直接返回
>                         // 如果是重试请求，则只使用brokerName等于lastBrokerName相同的，这点大家肯定有疑问：为啥要使用上次失败的，其实这里的lastBrokerName不单单指上次发送失败的节点，
>                         // 它还能蕴含推荐节点的信息，本函数的后半段中会看到如何将推荐节点的信息传递到lastBrokerName
>                         // 但是我觉得这样写的一个弊端是：当前可用节点，如果和上次失败时所用的节点不一致时，就会被排除掉，这也会影响效率
>                         if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
>                             return mq;
>                     }
>                 }
>                 // 走到这一步，代表所有节点都不可用（首次请求）或者上一次失败时用到的节点仍然不可用（重试请求）
>                 // 随后，将所有不可用的节点，按照潜在可用性（当前可用与否>上次使用该节点时的调用耗时>预估的下次可使用时间），进行了排序，然后选择最优的结果
>                 // 这里不用担心，连续重试时pickOneAtLeast每次都选择了相同节点，因为其内部也是用了轮训机制，会从最优->次优的顺序给出下一次推荐的节点
>                 final String notBestBroker = latencyFaultTolerance.pickOneAtLeast();
>                 //getQueueIdByBroker这个函数名也是惊到我了，完全和其功能不匹配，本行代码意在得到推荐节点是否仍然存在可写队列，如果存在，得出队列数
>                 int writeQueueNums = tpInfo.getQueueIdByBroker(notBestBroker);
>                 // 我们得到的推荐节点存在可写队列
>                 if (writeQueueNums > 0) {
>                     // 至此我们已经拿到了一个推荐节点，但是接下来代码的作者并没有简单地根据推荐节点来寻找队列，而是靠外层轮训找了下一个队列
>                     // 如果在次重试过程中没有发生路由信息更新的话，该队列应该仍然是不可用的，并且很可能仍是最初失败的Broker节点的队列，
>                     // 为什么这么说：假如消息队列为[BrokerA1,BrokerA2,BrokerA3,BrokerA4,BrokerB1,BrokerB2],只有当上一次轮训到BrokerA4时，这里才会跳过BrokerA而得到BrokerB的队列
>                     // 而且，可能下次更新路由表时，该信息可能就会成为过期数据而被GC，我猜作者是觉得反正这个数据快没用了，不如把它替换成刚才得到的推荐节点信息，这样可以少new一个对象，还能增加下次查找时的效率
>                     // 之所以说它能增加效率，是因为这个过程实质上是将一个很可能宕机的节点队列换成了最可能可用的节点信息，那么下次再轮训到这个节点时，实际上就跳过了寻找推荐节点的过程
>                     final MessageQueue mq = tpInfo.selectOneMessageQueue();
>                     if (notBestBroker != null) {
>                         // 把得到的队列的BrokerName改成我们前面得到的推荐节点，这样如果再请求失败并且重试的时候，lastBrokerName其实存储的就是推荐节点的信息了，下次再执行本函数时就会优先使用推荐节点的其他队列
>                         mq.setBrokerName(notBestBroker);
>                         // 重新计算其队列编号，因为得到的这个队列数可能和推荐节点的队列数不一致，如果用了错误的队列序号，消息发送到Broker那时，肯定会报错
>                         // 因此，这里基于外层轮询使用的index，对本次使用的队列编号进行了计算，我觉得这里最终达到的是随机选择的效果
>                         mq.setQueueId(tpInfo.getSendWhichQueue().getAndIncrement() % writeQueueNums);
>                     }
>                     return mq;
>                 } else { // 推荐节点不存在可写队列了，说明该节点可能已经宕机，并且NameServer已经删除了其路由信息，并且已经同步过来了
>                     // 这时候可以将该节点从延迟统计表中删除，不在考虑该节点
>                     latencyFaultTolerance.remove(notBestBroker);
>                 }
>             } catch (Exception e) {
>                 log.error("Error occurred when selecting message queue", e);
>             }
>             // 如果拿到的推荐节点已经不存在可写队列了，就随机选一个队列
>             return tpInfo.selectOneMessageQueue();
>         }
>         // 默认策略
>         return tpInfo.selectOneMessageQueue(lastBrokerName);
>     }
> ```
--------------------------------------------------------------------------------------------

这里：

>                         // 把得到的队列的BrokerName改成我们前面得到的推荐节点，这样如果再请求失败并且重试的时候，lastBrokerName其实存储的就是推荐节点的信息了，下次再执行本函数时就会优先使用推荐节点的其他队列
>                         mq.setBrokerName(notBestBroker);


你的说法我完全不能理解，这里是选中了notBestBroker，如果再请求失败并且重试的时候，lastBrokerName就是这里的notBestBroker，不理解，为啥都失败了，还会优先使用notBestBroker。

**Comment by BeiKeJieDeLiuLangMao** [comment]
> > @alaric27
> > 我分析了一下，不知道对不对。
> > ```
> > public MessageQueue selectOneMessageQueue(final TopicPublishInfo tpInfo, /*通常情况下，指上次请求失败时用到的节点*/final String lastBrokerName) {
> >         if (this.sendLatencyFaultEnable) {
> >             try {
> >                 // 外层轮询，下次请求时会选择下一个队列
> >                 int index = tpInfo.getSendWhichQueue().getAndIncrement();
> >                 for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
> >                     // index用于内层轮询，从而排除不可用的节点
> >                     int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
> >                     if (pos < 0)
> >                         pos = 0;
> >                     MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
> >                     // 验证可用性，latencyFaultTolerance存储了各个Broker发送消息的耗时，已经预估的下次可用时间点
> >                     if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
> >                         // 如果是第一次请求，并且可用，则直接返回
> >                         // 如果是重试请求，则只使用brokerName等于lastBrokerName相同的，这点大家肯定有疑问：为啥要使用上次失败的，其实这里的lastBrokerName不单单指上次发送失败的节点，
> >                         // 它还能蕴含推荐节点的信息，本函数的后半段中会看到如何将推荐节点的信息传递到lastBrokerName
> >                         // 但是我觉得这样写的一个弊端是：当前可用节点，如果和上次失败时所用的节点不一致时，就会被排除掉，这也会影响效率
> >                         if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
> >                             return mq;
> >                     }
> >                 }
> >                 // 走到这一步，代表所有节点都不可用（首次请求）或者上一次失败时用到的节点仍然不可用（重试请求）
> >                 // 随后，将所有不可用的节点，按照潜在可用性（当前可用与否>上次使用该节点时的调用耗时>预估的下次可使用时间），进行了排序，然后选择最优的结果
> >                 // 这里不用担心，连续重试时pickOneAtLeast每次都选择了相同节点，因为其内部也是用了轮训机制，会从最优->次优的顺序给出下一次推荐的节点
> >                 final String notBestBroker = latencyFaultTolerance.pickOneAtLeast();
> >                 //getQueueIdByBroker这个函数名也是惊到我了，完全和其功能不匹配，本行代码意在得到推荐节点是否仍然存在可写队列，如果存在，得出队列数
> >                 int writeQueueNums = tpInfo.getQueueIdByBroker(notBestBroker);
> >                 // 我们得到的推荐节点存在可写队列
> >                 if (writeQueueNums > 0) {
> >                     // 至此我们已经拿到了一个推荐节点，但是接下来代码的作者并没有简单地根据推荐节点来寻找队列，而是靠外层轮训找了下一个队列
> >                     // 如果在次重试过程中没有发生路由信息更新的话，该队列应该仍然是不可用的，并且很可能仍是最初失败的Broker节点的队列，
> >                     // 为什么这么说：假如消息队列为[BrokerA1,BrokerA2,BrokerA3,BrokerA4,BrokerB1,BrokerB2],只有当上一次轮训到BrokerA4时，这里才会跳过BrokerA而得到BrokerB的队列
> >                     // 而且，可能下次更新路由表时，该信息可能就会成为过期数据而被GC，我猜作者是觉得反正这个数据快没用了，不如把它替换成刚才得到的推荐节点信息，这样可以少new一个对象，还能增加下次查找时的效率
> >                     // 之所以说它能增加效率，是因为这个过程实质上是将一个很可能宕机的节点队列换成了最可能可用的节点信息，那么下次再轮训到这个节点时，实际上就跳过了寻找推荐节点的过程
> >                     final MessageQueue mq = tpInfo.selectOneMessageQueue();
> >                     if (notBestBroker != null) {
> >                         // 把得到的队列的BrokerName改成我们前面得到的推荐节点，这样如果再请求失败并且重试的时候，lastBrokerName其实存储的就是推荐节点的信息了，下次再执行本函数时就会优先使用推荐节点的其他队列
> >                         mq.setBrokerName(notBestBroker);
> >                         // 重新计算其队列编号，因为得到的这个队列数可能和推荐节点的队列数不一致，如果用了错误的队列序号，消息发送到Broker那时，肯定会报错
> >                         // 因此，这里基于外层轮询使用的index，对本次使用的队列编号进行了计算，我觉得这里最终达到的是随机选择的效果
> >                         mq.setQueueId(tpInfo.getSendWhichQueue().getAndIncrement() % writeQueueNums);
> >                     }
> >                     return mq;
> >                 } else { // 推荐节点不存在可写队列了，说明该节点可能已经宕机，并且NameServer已经删除了其路由信息，并且已经同步过来了
> >                     // 这时候可以将该节点从延迟统计表中删除，不在考虑该节点
> >                     latencyFaultTolerance.remove(notBestBroker);
> >                 }
> >             } catch (Exception e) {
> >                 log.error("Error occurred when selecting message queue", e);
> >             }
> >             // 如果拿到的推荐节点已经不存在可写队列了，就随机选一个队列
> >             return tpInfo.selectOneMessageQueue();
> >         }
> >         // 默认策略
> >         return tpInfo.selectOneMessageQueue(lastBrokerName);
> >     }
> > ```
> 
> 这里：
> 
> > ```
> >                     // 把得到的队列的BrokerName改成我们前面得到的推荐节点，这样如果再请求失败并且重试的时候，lastBrokerName其实存储的就是推荐节点的信息了，下次再执行本函数时就会优先使用推荐节点的其他队列
> >                     mq.setBrokerName(notBestBroker);
> > ```
> 
> 你的说法我完全不能理解，这里是选中了notBestBroker，如果再请求失败并且重试的时候，lastBrokerName就是这里的notBestBroker，不理解，为啥都失败了，还会优先使用notBestBroker。

如果发送失败了，还会优先使用notBestBroker，因为它很可能仍然是最佳的，但是要清楚这里还有一个前提，就是notBestBroker的 mq 可用时才会使用，如果mq仍然不可用的话，它还会进入后半段，再选下一个notBestBroker。

**Comment by CoderLan0668** [comment]
> > > @alaric27
> > > 我分析了一下，不知道对不对。
> > > ```
> > > public MessageQueue selectOneMessageQueue(final TopicPublishInfo tpInfo, /*通常情况下，指上次请求失败时用到的节点*/final String lastBrokerName) {
> > >         if (this.sendLatencyFaultEnable) {
> > >             try {
> > >                 // 外层轮询，下次请求时会选择下一个队列
> > >                 int index = tpInfo.getSendWhichQueue().getAndIncrement();
> > >                 for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
> > >                     // index用于内层轮询，从而排除不可用的节点
> > >                     int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
> > >                     if (pos < 0)
> > >                         pos = 0;
> > >                     MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
> > >                     // 验证可用性，latencyFaultTolerance存储了各个Broker发送消息的耗时，已经预估的下次可用时间点
> > >                     if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
> > >                         // 如果是第一次请求，并且可用，则直接返回
> > >                         // 如果是重试请求，则只使用brokerName等于lastBrokerName相同的，这点大家肯定有疑问：为啥要使用上次失败的，其实这里的lastBrokerName不单单指上次发送失败的节点，
> > >                         // 它还能蕴含推荐节点的信息，本函数的后半段中会看到如何将推荐节点的信息传递到lastBrokerName
> > >                         // 但是我觉得这样写的一个弊端是：当前可用节点，如果和上次失败时所用的节点不一致时，就会被排除掉，这也会影响效率
> > >                         if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
> > >                             return mq;
> > >                     }
> > >                 }
> > >                 // 走到这一步，代表所有节点都不可用（首次请求）或者上一次失败时用到的节点仍然不可用（重试请求）
> > >                 // 随后，将所有不可用的节点，按照潜在可用性（当前可用与否>上次使用该节点时的调用耗时>预估的下次可使用时间），进行了排序，然后选择最优的结果
> > >                 // 这里不用担心，连续重试时pickOneAtLeast每次都选择了相同节点，因为其内部也是用了轮训机制，会从最优->次优的顺序给出下一次推荐的节点
> > >                 final String notBestBroker = latencyFaultTolerance.pickOneAtLeast();
> > >                 //getQueueIdByBroker这个函数名也是惊到我了，完全和其功能不匹配，本行代码意在得到推荐节点是否仍然存在可写队列，如果存在，得出队列数
> > >                 int writeQueueNums = tpInfo.getQueueIdByBroker(notBestBroker);
> > >                 // 我们得到的推荐节点存在可写队列
> > >                 if (writeQueueNums > 0) {
> > >                     // 至此我们已经拿到了一个推荐节点，但是接下来代码的作者并没有简单地根据推荐节点来寻找队列，而是靠外层轮训找了下一个队列
> > >                     // 如果在次重试过程中没有发生路由信息更新的话，该队列应该仍然是不可用的，并且很可能仍是最初失败的Broker节点的队列，
> > >                     // 为什么这么说：假如消息队列为[BrokerA1,BrokerA2,BrokerA3,BrokerA4,BrokerB1,BrokerB2],只有当上一次轮训到BrokerA4时，这里才会跳过BrokerA而得到BrokerB的队列
> > >                     // 而且，可能下次更新路由表时，该信息可能就会成为过期数据而被GC，我猜作者是觉得反正这个数据快没用了，不如把它替换成刚才得到的推荐节点信息，这样可以少new一个对象，还能增加下次查找时的效率
> > >                     // 之所以说它能增加效率，是因为这个过程实质上是将一个很可能宕机的节点队列换成了最可能可用的节点信息，那么下次再轮训到这个节点时，实际上就跳过了寻找推荐节点的过程
> > >                     final MessageQueue mq = tpInfo.selectOneMessageQueue();
> > >                     if (notBestBroker != null) {
> > >                         // 把得到的队列的BrokerName改成我们前面得到的推荐节点，这样如果再请求失败并且重试的时候，lastBrokerName其实存储的就是推荐节点的信息了，下次再执行本函数时就会优先使用推荐节点的其他队列
> > >                         mq.setBrokerName(notBestBroker);
> > >                         // 重新计算其队列编号，因为得到的这个队列数可能和推荐节点的队列数不一致，如果用了错误的队列序号，消息发送到Broker那时，肯定会报错
> > >                         // 因此，这里基于外层轮询使用的index，对本次使用的队列编号进行了计算，我觉得这里最终达到的是随机选择的效果
> > >                         mq.setQueueId(tpInfo.getSendWhichQueue().getAndIncrement() % writeQueueNums);
> > >                     }
> > >                     return mq;
> > >                 } else { // 推荐节点不存在可写队列了，说明该节点可能已经宕机，并且NameServer已经删除了其路由信息，并且已经同步过来了
> > >                     // 这时候可以将该节点从延迟统计表中删除，不在考虑该节点
> > >                     latencyFaultTolerance.remove(notBestBroker);
> > >                 }
> > >             } catch (Exception e) {
> > >                 log.error("Error occurred when selecting message queue", e);
> > >             }
> > >             // 如果拿到的推荐节点已经不存在可写队列了，就随机选一个队列
> > >             return tpInfo.selectOneMessageQueue();
> > >         }
> > >         // 默认策略
> > >         return tpInfo.selectOneMessageQueue(lastBrokerName);
> > >     }
> > > ```
> > 
> > 
> > 这里：
> > > ```
> > >                     // 把得到的队列的BrokerName改成我们前面得到的推荐节点，这样如果再请求失败并且重试的时候，lastBrokerName其实存储的就是推荐节点的信息了，下次再执行本函数时就会优先使用推荐节点的其他队列
> > >                     mq.setBrokerName(notBestBroker);
> > > ```
> > 
> > 
> > 你的说法我完全不能理解，这里是选中了notBestBroker，如果再请求失败并且重试的时候，lastBrokerName就是这里的notBestBroker，不理解，为啥都失败了，还会优先使用notBestBroker。
> 
> 如果发送失败了，还会优先使用notBestBroker，因为它很可能仍然是最佳的，但是要清楚这里还有一个前提，就是notBestBroker的 mq 可用时才会使用，如果mq仍然不可用的话，它还会进入后半段，再选下一个notBestBroker。

--------------------------------------------------------

嗯 但是理论上 latencyFaultTolerance.isAvailable(mq.getBrokerName()) 如果是可用的，不应该就选出来了吗？为啥还要进入后半段？ 经过latencyFaultTolerance.isAvailable(mq.getBrokerName())筛选之后，不管是不是等于lastBrokerName，都是可以用的吧？这里有点不理解

**Comment by BeiKeJieDeLiuLangMao** [comment]
> 是可以用的吧

我觉得这个循环在lastBrokerName为空时的效果是根据轮训找一个 mq 发送，如果 lastBrokerName 不为空，它的作用偏向于再确认一下这个 broker 是否现在变的可用了，如果可用就继续发，如果不可用去找个最优的发。我觉得它可以写成：
```java
if (null == lastBrokerName) {
             for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
                    int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
                    if (pos < 0)
                        pos = 0;
                    MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
                    if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
                            return mq;
                    }
                }
} else {
    if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {//官方没有这个，所以效率低了一些
              for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
                    int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
                    if (pos < 0)
                        pos = 0;
                    MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
                    if (latencyFaultTolerance.isAvailable(mq.getBrokerName()) && mq.getBrokerName().equals(lastBrokerName)) {
                            return mq;
                    }
                }
     }
}
// 后半段
```

**Comment by CoderLan0668** [comment]
@BeiKeJieDeLiuLangMao  感觉“再确认一下这个 broker 是否现在变的可用了”这个逻辑其实没啥必要性吧？ 增加这个策略的目的不就是尽可能实现高可用低延时吗？直接选一个最优的就行了吧（可用->延时两个维度）。

**Comment by BeiKeJieDeLiuLangMao** [comment]
> @BeiKeJieDeLiuLangMao 感觉“再确认一下这个 broker 是否现在变的可用了”这个逻辑其实没啥必要性吧？ 增加这个策略的目的不就是尽可能实现高可用低延时吗？直接选一个最优的就行了吧（可用->延时两个维度）。

失败通常伴随着一个较长的超时时间，在超时的这段时间里它也可能恢复了，它可能觉得为了这个潜在的可能性，进行一次判断，说不定能省略后面的步骤。

**Comment by BeiKeJieDeLiuLangMao** [comment]
@CoderLan0668 
他这个地方的代码写的确实不好，但是如果按这个 PR 提出的删除判断方案进行，就会变成所有 mq 不可用时才使用统计的延时信息，而之前的效果是，全部 mq 不可用或者之前发送的 broker 不可用时，挑一个最优 broker 的 mq。

**Comment by CoderLan0668** [comment]
@BeiKeJieDeLiuLangMao  嗯 是这样的 你很棒

**Comment by CoderLan0668** [comment]
@BeiKeJieDeLiuLangMao   后半段的选择最优逻辑你是怎么理解的？

    @Override
    public String pickOneAtLeast() {
        final Enumeration<FaultItem> elements = this.faultItemTable.elements();
        List<FaultItem> tmpList = new LinkedList<FaultItem>();
        while (elements.hasMoreElements()) {
            final FaultItem faultItem = elements.nextElement();
            tmpList.add(faultItem);
        }

        if (!tmpList.isEmpty()) {
            Collections.shuffle(tmpList);
            // 按照可用与否、时延、预测的正常时间这几个维度排序
            Collections.sort(tmpList);

            final int half = tmpList.size() / 2;
            if (half <= 0) {
                //只有一个的情况下，选第一个
                return tmpList.get(0).getName();
            } else {
               //这里选择了在列表的前半段轮转？
                final int i = this.whichItemWorst.getAndIncrement() % half;
                return tmpList.get(i).getName();
            }
        }

        return null;
    }


我不能理解这里为啥在broker列表的前半段进行轮转啊？ 这样就能选出最优的吗？

理论上：
            // 按照可用与否、时延、预测的正常时间这几个维度排序
            Collections.sort(tmpList);

排序之后，第一个不应该是最理想的吗？

**Comment by CoderLan0668** [comment]
public class ThreadLocalIndex {
    private final ThreadLocal<Integer> threadLocalIndex = new ThreadLocal<Integer>();
    private final Random random = new Random();

    public int getAndIncrement() {
        Integer index = this.threadLocalIndex.get();
        if (null == index) {
            index = Math.abs(random.nextInt());
            if (index < 0)
                index = 0;
            this.threadLocalIndex.set(index);
        }

        index = Math.abs(index + 1);
        if (index < 0)
            index = 0;

        this.threadLocalIndex.set(index);
        return index;
    }
}

可以看到whichItemWorst在第一次getAndIncrement的时候，也没保证一定是0.，而是随机的。意味着有可能选到一个统计视图上处理中间的broker，并不是最优的，至少从统计视图上不是最优的。

**Comment by BeiKeJieDeLiuLangMao** [comment]
> public class ThreadLocalIndex {
> private final ThreadLocal threadLocalIndex = new ThreadLocal();
> private final Random random = new Random();
> 
> ```
> public int getAndIncrement() {
>     Integer index = this.threadLocalIndex.get();
>     if (null == index) {
>         index = Math.abs(random.nextInt());
>         if (index < 0)
>             index = 0;
>         this.threadLocalIndex.set(index);
>     }
> 
>     index = Math.abs(index + 1);
>     if (index < 0)
>         index = 0;
> 
>     this.threadLocalIndex.set(index);
>     return index;
> }
> ```
> 
> }
> 
> 可以看到whichItemWorst在第一次getAndIncrement的时候，也没保证一定是0.，而是随机的。意味着有可能选到一个统计视图上处理中间的broker，并不是最优的，至少从统计视图上不是最优的。

我觉得它可能不是每次都追求一定要发给最优节点，就如图函数名一样它是 pickOneAtLeast 而不是 pickBestOne，你可以看到无论是 pickOneAtLeast 还是 whichItemWorst.getAndIncrement 都加入了很多的随机因素，他恐怕是怕如果发生网络问题后出现所有请求都打向单一节点（index0）的情况， 如果所有请求都打向同一个节点的话，可能会造成服务无法承受这么大压力，所以它用了很多随机因素来均衡这部分流量，但是他也不是完全随机，它多多少少参考了统计视图的结果。

**Pull request closed without merging**
