### PR TITLE
[ISSUE #3724]: Polish the unit test of class ConsumeMessageConcurrentlyService

### PR DESCRIPTION
**Pull request by XiaoyiPeng**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

For #3724 

## Brief changelog

Polish the unit test of class ConsumeMessageConcurrentlyService

## Verifying this change

image

### CODE REVIEW

**Review by yuz10 — APPROVED** [review]

**Review by panzhi33 — APPROVED** [review]

**Review by odbozhou — APPROVED** [review]

**Review by ni-ze — APPROVED** [review]

**Review by duhenglucky — COMMENTED** [review]
There are conflicts in this PR, would you like to resolve them first, we will merge this PR ASAP.

**Review by Git-Yang — APPROVED** [review]

**Comment by XiaoyiPeng** [comment]
> There are conflicts in this PR, would you like to resolve them first, we will merge this PR ASAP.

Hi, @duhenglucky 

I have resolved the conflict. 
Even though the code compiled and the unit tests passed,  but there is a small flaw in class ```ConsumeMessageConcurrentlyServiceTest```,  

https://github.com/apache/rocketmq/blob/e8cae430d4677db3d52af6f92e8d2aba2f8e5e0d/client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java#L181

Here used  method **LongAdder#sum()** which is defined in **jdk8**, but in **pom.xml** of `client module`, the compiler version is **1.6**, as shown below: 

image

**The IDE has a error tooltip over** `ConsumeMessageConcurrentlyServiceTest.java#L181.`

I think we should fix it.

**Comment by duhenglucky** [comment]
> 

IMO，4.9.3 may be the last version of rocketmq-client， but bump up JDK version need a vote in the community, so I think in this version, we'd better adapt to the 1.6 version of jdk

**Comment by XiaoyiPeng** [comment]
> > 
> 
> IMO，4.9.3 may be the last version of rocketmq-client with JDK 1.6， but bumping up the JDK version to 1.8 need a vote in the community, so I think in this version, we'd better adapt to the 1.6 version of jdk

Thanks, I got it.

**Pull request merged**
