### PR TITLE
Support build with Bazel

### PR DESCRIPTION
**Pull request by lizhanhui**
This is to achieve goals described in https://github.com/apache/rocketmq/issues/4864

### CODE REVIEW

**Comment by francisoliverlee** [comment]
hi li, why we need Bazel having Maven ?

**Comment by lizhanhui** [comment]
@francisoliverlee See the issue description.

**Comment by lizhanhui** [comment]
Merge to verify issue: https://issues.apache.org/jira/browse/INFRA-23612

**Review by ShannonDing — COMMENTED** [review]
some test cases are ignored, will you open them later?

**Comment by RongtongJin** [comment]
Hi @lizhanhui I think this is a good idea to support build with Bazel, but I found that many tests were ignored. I think some tests need to be repaired and things need to be informed before implementation. In addition, **DO NOT MERGE** your own PR without anyone's approval. I will revert this PR first.

**Comment by lizhanhui** [comment]
> some test cases are ignored, will you open them later?
Only one or two UNSTABLE cases are ignored for now. I plan to fix them in separate pr.

**Comment by lizhanhui** [comment]
@RongtongJin I think some tests need to be repaired and things need to be informed before implementation. In addition, DO NOT MERGE your own PR without anyone's approval. I will revert this PR first.

You are being excessively arrogant and rude. It's advisable not to be so. Inspect the changes, first. Things are not what you  claimed.

**Comment by zhouxinyu** [comment]
Currently, the CI costs too much time, I also think changing the build system is a good attempt. If our members think more discussions are needed, let's do it. @RongtongJin

Also, let's follow the community guidelines, merge after some approvals is the best practice, if we need a merge event to trigger the GitHub action in the test phase, consider using a new branch. @lizhanhui 

Unfortunately, I couldn't find the detailed guidelines about the merge conditions on our website, shall we discuss and clear it ASAP?

**Comment by duhenglucky** [comment]
> 

Actually, Here are some [specifications](https://github.com/apache/rocketmq/wiki/RIP-14-RocketMQ-Community-Operation-Conventions) on PR merging that have been voted by the community. I think it is better to follow these guidelines.

**Comment by lizhanhui** [comment]
@duhenglucky Given the status of the guideline itself being **DISCUSS**, it does not make sense to assume it is something of a consensus.

**Comment by RongtongJin** [comment]
> Currently, the CI costs too much time, I also think changing the build system is a good attempt. If our members think more discussions are needed, let's do it. @RongtongJin
> 
> Also, let's follow the community guidelines, merge after some approvals is the best practice, if we need a merge event to trigger the GitHub action in the test phase, consider using a new branch. @lizhanhui
> 
> Unfortunately, I couldn't find the detailed guidelines about the merge conditions on our website, shall we discuss and clear it ASAP?

Hi @zhouxinyu I agree with you that we need to reduce the time of CI and think it is necessary. But why did the author merge such a large PR by himself without any notice? In addition, he ignored some necessary tests.

**Comment by RongtongJin** [comment]
> Given the status of the guideline itself being **DISCUSS**, it does not make sense to assume it is something of a consensus.

This convention has been discussed on the mailing list. https://lists.apache.org/thread/7onbv6yrw7q4ytbhy3w3f2d0v4rtf4dl

**Comment by duhenglucky** [comment]
> @duhenglucky Given the status of the guideline itself being **DISCUSS**, it does not make sense to assume it is something of a consensus.

Sorry for my fault of forgot to update the status of this RIP, this is the link to vote at that time: https://lists.apache.org/thread/7onbv6yrw7q4ytbhy3w3f2d0v4rtf4dl, Now I have updated the status, thanks for the reminder ：）

**Comment by lizhanhui** [comment]
@RongtongJin First, it is not a large PR, only a few lines of changes to main source files. Most of the changes are Bazel build files and fixes to test cases that are not hermetic or unstable, or not capable of running in parallel.  Only a very few tests are temporarily disabled, which will be enabled in a separate PR.  The focus of this PR is to enable Bazel, helping us build and run tests in parallel.

Second, Infra team is waiting to confirm if they configured secrets correctly. 

As a member of the community, you, by no means, are supposed to revert contribution harshly, without even getting any response. This is not what a qualified PMC member should do, and can not make the community any way better in any perspecitve.

**Comment by lizhanhui** [comment]
> > @duhenglucky Given the status of the guideline itself being **DISCUSS**, it does not make sense to assume it is something of a consensus.
> 
> Sorry for my fault of forgetting to update the status of this RIP, this is the link to vote at that time: https://lists.apache.org/thread/7onbv6yrw7q4ytbhy3w3f2d0v4rtf4dl, Now I have updated the status, thanks for the reminder ：）

The RIP is obviously lack of thorough discussion. I suggest not to change it status in a haste. It's better to double review it since it would impact a lot in the community.

**Comment by RongtongJin** [comment]
> @RongtongJin First, it is not a large PR, only a few lines of changes to main source files. Most of the changes are Bazel build files and fixes to test cases that are not hermetic or unstable, or not capable of running in parallel. Only a very few tests are temporarily disabled, which will be enabled in a separate PR. The focus of this PR is to enable Bazel, helping us build and run tests in parallel.
> 
> Second, Infra team is waiting to confirm if they configured secrets correctly.
> 
> As a member of the community, you, by no means, are supposed to revert contribution harshly, without even getting any response. This is not what a qualified PMC member should do, and can not make the community any way better in any perspective.

I agree with your last paragraph. In addition, we should not **treat yourself leniently and be strict with others**

image

**Comment by RongtongJin** [comment]
> > > @duhenglucky Given the status of the guideline itself being **DISCUSS**, it does not make sense to assume it is something of a consensus.
> > 
> > 
> > Sorry for my fault of forgetting to update the status of this RIP, this is the link to vote at that time: https://lists.apache.org/thread/7onbv6yrw7q4ytbhy3w3f2d0v4rtf4dl, Now I have updated the status, thanks for the reminder ：）
> 
> The RIP is obviously lack of thorough discussion. I suggest not to change it status in a haste. It's better to double review it since it would impact a lot in the community.

So why didn't you participate in the discussion when I sent the discussion email?

**Comment by lizhanhui** [comment]
> > @RongtongJin First, it is not a large PR, only a few lines of changes to main source files. Most of the changes are Bazel build files and fixes to test cases that are not hermetic or unstable, or not capable of running in parallel. Only a very few tests are temporarily disabled, which will be enabled in a separate PR. The focus of this PR is to enable Bazel, helping us build and run tests in parallel.
> > Second, Infra team is waiting to confirm if they configured secrets correctly.
> > As a member of the community, you, by no means, are supposed to revert contribution harshly, without even getting any response. This is not what a qualified PMC member should do, and can not make the community any way better in any perspective.
> 
> I agree with your last paragraph. In addition, we should not **treat yourself leniently and be strict with others**
> 
> image

Read the context of that PR. You are purposely neglecting reviews, changing from one spell error to another. This is why the revert is necessary.

**Comment by lizhanhui** [comment]
> > > > @duhenglucky Given the status of the guideline itself being **DISCUSS**, it does not make sense to assume it is something of a consensus.
> > > 
> > > 
> > > Sorry for my fault of forgetting to update the status of this RIP, this is the link to vote at that time: https://lists.apache.org/thread/7onbv6yrw7q4ytbhy3w3f2d0v4rtf4dl, Now I have updated the status, thanks for the reminder ：）
> > 
> > 
> > The RIP is obviously lack of thorough discussion. I suggest not to change it status in a haste. It's better to double review it since it would impact a lot in the community.
> 
> So why didn't you participate in the discussion when I sent the discussion email?

This is not a normal RIP of specific features. If it would reflect continuous community consensus, it should be thoroughly reviewed and widely accepted.

**Comment by zhouxinyu** [comment]
Let's relax and focus on this PR, things should be moving forward, how about closing this issue in a new branch and then merging it to develop after every test case passed, I also want to be a volunteer to fix these unit tests. @lizhanhui 

As for the merge convention, the community had a consensus, but that does not prevent us from discussing and polishing it continuously. For example, the so-called `core contributor` and by module rules are confusing and difficult to practice. IMO, we could have more discussions on the mailing list and apply the rules to [.asf.yaml](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features) to reduce the labor burden once we have a new consensus.

**Comment by aaron-ai** [comment]
> Let's relax and focus on this PR, things should be moving forward, how about closing this issue in a new branch and then merging it to develop after every test case passed, I also want to be a volunteer to fix these unit tests. @lizhanhui
> 
> As for the merge convention, the community had a consensus, but that does not prevent us from discussing and polishing it continuously. For example, the so-called `core contributor` and by module rules are confusing and difficult to practice. IMO, we could have more discussions on the mailing list and apply the rules to [.asf.yaml](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features) to reduce the labor burden once we have a new consensus.

I agree with that, and we could discuss more details about mergeability in this issue #4870 .

**Comment by lizhanhui** [comment]
> how about closing this issue in a new branch and then merging it to develop after every test case passed, I also want to be a volunteer to fix these unit tests. 

This is the RocketMQ community it used to be and where the genuine Apache Way shines. It's okay to create a branch in the repository where we make every case pass and fix the rest flaky ones. 

> As for the merge convention, the community had a consensus, but that does not prevent us from discussing and polishing it continuously. For example, the so-called core contributor and by module rules are confusing and difficult to practice. IMO, we could have more discussions on the mailing list and apply the rules to [.asf.yaml](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features) to reduce the labor burden once we have a new consensus.

Exactly. RIPs are not something fixed, if not deprecated.  They are consensus that helps the community.

**Pull request merged**
