### PR TITLE
[bugfix]lmq offset sync master to slave

### PR DESCRIPTION
**Pull request by mongolhoo**
### Which Issue(s) This PR Fixes

Fixes #issue_id

### CODE REVIEW

**Comment by mongolhoo** [comment]
issue #8509

**Comment by mongolhoo** [comment]
@yx9o I have submitted a pull request for issue 8509。

**Comment by yx9o** [comment]
Thanks for your contribution, could you add unit tests for your changes?

**Comment by mongolhoo** [comment]
OK, do I need to resubmit the PR after adding the test case?

**Pull request closed without merging**
