### PR TITLE
[ROCKETMQ-226]Remove the code that is not useful in the loop

### PR DESCRIPTION
**Pull request by huangyiminghappy**
Remove the code that is not useful in the loop

### CODE REVIEW

**Comment by huangyiminghappy** [comment]
https://issues.apache.org/jira/browse/ROCKETMQ-226

**Comment by vongosling** [comment]
Could you follow standard PR（notice topic style） ? and squash your many commits ?

**Comment by huangyiminghappy** [comment]
the  code ## FOR_SEG   is not useful,It is not multiple loop,You do not need to jump to the specified loop,so i suggest remove the FOR_SEQ code
` public FindBrokerResult findBrokerAddressInAdmin(final String brokerName) {
        String brokerAddr = null;
        boolean slave = false;
        boolean found = false;

        HashMap<Long/* brokerId */, String/* address */> map = this.brokerAddrTable.get(brokerName);
        if (map != null && !map.isEmpty()) {
            FOR_SEG:
            for (Map.Entry<Long, String> entry : map.entrySet()) {
                Long id = entry.getKey();
                brokerAddr = entry.getValue();
                if (brokerAddr != null) {
                    found = true;
                    if (MixAll.MASTER_ID == id) {
                        slave = false;
                        break FOR_SEG;
                    } else {
                        slave = true;
                    }
                    break;

                }
            } // end of for
        }

        if (found) {
            return new FindBrokerResult(brokerAddr, slave);
        }

        return null;
    }`

**Comment by dongeforever** [comment]
LGTM @huangyiminghappy Thanks for your contribution.
@vongosling @zhouxinyu please help a review

**Pull request merged**
