### PR TITLE
[ISSUE #6968] fix grpc acl bug

### PR DESCRIPTION
**Pull request by lyx2000**
### Which Issue(s) This PR Fixes
Fixes https://github.com/apache/rocketmq/issues/6968

### Brief Description
As issue mentioned.

### How Did You Test This Change?
The failure examples mentioned in the issue have been successfully accessed, then I will add enough unit tests like remoting as soon as possible.

### CODE REVIEW

**Review by drpmma — COMMENTED** [review]
LGTM, but maybe adding some unit tests would be better.

**Comment by lyx2000** [comment]
> LGTM, but maybe adding some unit tests would be better.

ok I will add some necessary to prove this

**Review by yuz10 — DISMISSED** [review]

**Comment by yuz10** [comment]
@lyx2000 Some check not pass, can you rerun the tests?

**Comment by lyx2000** [comment]
> 

Ok, please wait for me for two days, I will add some unit tests that can reflect the problem.

**Comment by lyx2000** [comment]
> @lyx2000 Some check not pass, can you rerun the tests?

Ok, please wait for me for a few days, I will add some unit tests that can reflect the problem. 💪

**Review by mxsm — APPROVED** [review]
LGTM

**Comment by lyx2000** [comment]
When writing the unit tests, I found that there wasn't a test complete with a joint test from parsing the request to checking the permissions, so I added tests related to both protocol clients. These additional tests would not have passed before my fix.

**Review by mxsm — APPROVED** [review]

**Review by yuz10 — APPROVED** [review]

**Pull request merged**
