### PR TITLE
[ROCKETMQ-350] Add multiple Network Interface Cards support

### PR DESCRIPTION
**Pull request by mark800**
## What is the purpose of the change

It is becoming commonplace to have more than one Network Interface Card (NIC), usually one for local network communication, another for remote communication.
Supporting multiple Network Interface Cards support for “Broker Machine” could be very useful.

## Brief changelog

1 Broker will report multiple addresses to Name Server, the format is like the multiple nameServer addr: ip1;ip2;ip3:port

2 After consumer/producer get the route info from Name Server, there is a test or detect process, then store one accessible address for each broker.

3 All the changes are backward compatible. But if using the changed broker and old version client, the consumer/producer will get exception because fetched broker’s addr is not “ip:port”, it could be “ip1;ip2:port”.

4 add a configure Parameter in the broker to disable the new feature

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/ROCKETMQ/issues/) filed for the change (usually before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x ] Format the pull request title like `[ROCKETMQ-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x ] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by mark800** [comment]
@zhouxinyu could you please help to review this pr?

**Comment by zhouxinyu** [comment]
```
But if using the changed broker and old version client.....
```
We must operate with that, it's a very common deployment structure.

**Comment by mark800** [comment]
@zhouxinyu Added “isEnableMultipleNICSupport” option in brokerConfig

**Comment by vongosling** [comment]
@mark800 Could you resolve the conflicts, I will help to review your pr.

**Comment by duhengforever** [comment]
@mark800 Could you modify your code to make travis check pass?

**Comment by mark800** [comment]
@vongosling travis check passed, could you please review the pr?

**Comment by vongosling** [comment]
Could you tell us your real use case for your Multi Network Interface Cards, how do you choose if we have many ips?

**Pull request closed without merging**
