### PR TITLE
[ISSUE#4949] fix Address already in use

### PR DESCRIPTION
**Pull request by complone**
**Make sure set the target branch to `develop`**
## What is the purpose of the change

Related to [issue-4949](https://github.com/apache/rocketmq/issues/4949)

Fixed the port occupancy problem caused by the different order of shutdown calls
## Verifying this change

WeChat34a292217717a19ca08b5fab2b751e6c

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by lizhanhui** [comment]
Hi @complone , nextPort() can only fix the issue when unit tests are running in sequential order. It would be better if we ask the OS to pick up an available port. 
Aka, socket.listen(0).

**Comment by complone** [comment]
> 细节

Hi, do you mean to apply for a free available port as follows:
```
            ServerSocket serverSocket = new ServerSocket(0);
            int port = serverSocket.getLocalPort();
```

**Comment by aaron-ai** [comment]
> > 细节
> 
> Hi, do you mean to apply for a free available port as follows:
> 
> ```
>             ServerSocket serverSocket = new ServerSocket(0);
>             int port = serverSocket.getLocalPort();
> ```

Thank you for contributing!

It seems that the only way to find an available port is try to occupy a port using 0 and release it, but this approach is not thread-safe. You could get more information from the [deprecation of SocketUtils#findAvailableTcpPort](https://github.com/spring-projects/spring-framework/issues/28052)

**Comment by lizhanhui** [comment]
>  only way to find an available port is try to occupy a port using 0 and release it, but this approach is not thread-safe.

No, we should not use this approach. Modify the main source code to accept a configured listening port `0` and reflect/update the actual listening port in server-config objects. Use the config in test cases as we do in `RemotingServerTest`

**Comment by aaron-ai** [comment]
> > only way to find an available port is try to occupy a port using 0 and release it, but this approach is not thread-safe.
> 
> No, we should not use this approach. Modify the main source code to accept a configured listening port `0` and reflect/update the actual listening port in server-config objects. Use the config in test cases as we do in `RemotingServerTest`

I agree with that.

**Comment by complone** [comment]
> > only way to find an available port is try to occupy a port using 0 and release it, but this approach is not thread-safe.
> 
> No, we should not use this approach. Modify the main source code to accept a configured listening port `0` and reflect/update the actual listening port in server-config objects. Use the config in test cases as we do in `RemotingServerTest`
I think such [changes](https://github.com/apache/rocketmq/pull/5000/files#diff-ee85830d5ccf3051cea017b2ea12299dd9c282bade28bc50061490f963c5c1ffR77) are in line with expectations. In fact, the default value of nettyServerConfig.getListenPort is 0. We do not need to implement the method for netty port compatibility in NettyRemotingServer.

**Comment by complone** [comment]
As shown here, if the port of nettyserver is temporarily occupied by port 0, we need to add additional logic to release port 0 in NettyRemoteServer

https://github.com/complone/rocketmq/tree/fix-issue4949-port

**Comment by lizhanhui** [comment]
>  we need to add additional logic to release port 0 in NettyRemoteServer

Read https://www.baeldung.com/cs/binding-available-ports#different-ways-to-bind-a-port

> But I am worried that this method is too invasive because we need to interact based on the Remoting protocol, which will cause the thread timing to be out of order.

Actually, this is the standard way to run tests in parallelism. I've spent some time investigating the potential changes required, finding we indeed need a few changes to the current code and dledger dependency. I am OK with the current status of this PR now that there is no achievable solution with changes less than 10 lines

**Review by lizhanhui — APPROVED** [review]

**Pull request merged**
