### PR TITLE
[ISSUE #5365] [RIP 51] Add notification mechanism for pop orderly

### LINKED ISSUE #5365: [RIP 51] Task2: Add notification mechanism for pop orderly.
RIP Link: https://github.com/apache/rocketmq/wiki/RIP-51-Pop-orderly-improvement#add-notification-mechanism-for-pop-orderly

### PR DESCRIPTION
**Pull request by xdkxlk**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

close #5365 #5399

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by lizhanhui** [comment]
> We can use an in-memory timer to record the time at which the lock is released. When the time is up, check to see if there is a message that can be pulled and if so, wake up the pending long polling request.

I do not see the reason why an in-memory timer is required. Once a previous pop request that holds the lock completes, why not simply dispatch a task to check if there is an await pop request held in the chain... On the completion of on request, fire a second in consecutive.

**Comment by xdkxlk** [comment]
> 



> > We can use an in-memory timer to record the time at which the lock is released. When the time is up, check to see if there is a message that can be pulled and if so, wake up the pending long polling request.
> 
> I do not see the reason why an in-memory timer is required. Once a previous pop request that holds the lock completes, why not simply dispatch a task to check if there is an await pop request held in the chain... On the completion of on request, fire a second in consecutive.

For example:
If we pop one message orderly (invisible time is 5s) and not ack this message, we expect re-consume this message 5s later. Then we send a new pop request with the 30s long polling timeout. If wait this request timeout, the message will delay 25s to be re-consumed, so we need a timer to wake up this long polling request after 5s.

**Comment by lizhanhui** [comment]
> > 
> 
> > > We can use an in-memory timer to record the time at which the lock is released. When the time is up, check to see if there is a message that can be pulled and if so, wake up the pending long polling request.
> > 
> > 
> > I do not see the reason why an in-memory timer is required. Once a previous pop request that holds the lock completes, why not simply dispatch a task to check if there is an await pop request held in the chain... On the completion of on request, fire a second in consecutive.
> 
> For example: If we pop one message orderly (invisible time is 5s) and not ack this message, we expect re-consume this message 5s later. Then we send a new pop request with the 30s long polling timeout. If wait this request timeout, the message will delay 25s to be re-consumed, so we need a timer to wake up this long polling request after 5s.

I mean, in your given example, can the state change(timeout of the popped message) itself act as the trigger?

**Comment by xdkxlk** [comment]
> 



> > > 
> > 
> > 
> > > > We can use an in-memory timer to record the time at which the lock is released. When the time is up, check to see if there is a message that can be pulled and if so, wake up the pending long polling request.
> > > 
> > > 
> > > I do not see the reason why an in-memory timer is required. Once a previous pop request that holds the lock completes, why not simply dispatch a task to check if there is an await pop request held in the chain... On the completion of on request, fire a second in consecutive.
> > 
> > 
> > For example: If we pop one message orderly (invisible time is 5s) and not ack this message, we expect re-consume this message 5s later. Then we send a new pop request with the 30s long polling timeout. If wait this request timeout, the message will delay 25s to be re-consumed, so we need a timer to wake up this long polling request after 5s.
> 
> I mean, in your given example, can the state change(timeout of the popped message) itself act as the trigger?

Not like pop normally, there isn't a timed ck message for pop orderly
If we change the state of popped message to a timed message, we still need a in-memory buffer to prevent there are too many timed message needed put into store, like PopBufferMergeService
Meanwhile for pop orderly, the locking time is generally not very long, so the in-memory timer is enough

**Comment by lizhanhui** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > > > We can use an in-memory timer to record the time at which the lock is released. When the time is up, check to see if there is a message that can be pulled and if so, wake up the pending long polling request.
> > > > 
> > > > 
> > > > I do not see the reason why an in-memory timer is required. Once a previous pop request that holds the lock completes, why not simply dispatch a task to check if there is an await pop request held in the chain... On the completion of on request, fire a second in consecutive.
> > > 
> > > 
> > > For example: If we pop one message orderly (invisible time is 5s) and not ack this message, we expect re-consume this message 5s later. Then we send a new pop request with the 30s long polling timeout. If wait this request timeout, the message will delay 25s to be re-consumed, so we need a timer to wake up this long polling request after 5s.
> > 
> > 
> > I mean, in your given example, can the state change(timeout of the popped message) itself act as the trigger?
> 
> Not like pop normally, there isn't a timed ck message for pop orderly If we change the state of popped message to a timed message, we still need a in-memory buffer to prevent there are too many timed message needed put into store, like PopBufferMergeService Meanwhile for pop orderly, the locking time is generally not very long, so the in-memory timer is enough

OK, this clarifies my concerns.

**Review by lizhanhui — APPROVED** [review]

**Pull request merged**
