### PR TITLE
FIX: HmacSHA1 not found if JAVA_HOME set to JRE

### PR DESCRIPTION
**Pull request by boypt**
## What is the purpose of the change

when JAVA_HOME is set to JRE, errors throw out as below:
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
org.apache.rocketmq.tools.command.SubCommandException: ClusterListSubCommand command failed
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:93)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:135)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:86)
Caused by: org.apache.rocketmq.acl.common.AclException: [10015:signature-failed] unable to calculate a request signature. error=[10015:signaturerithm HmacSHA1 not available
	at org.apache.rocketmq.acl.common.AclSigner.signAndBase64Encode(AclSigner.java:84)
	at org.apache.rocketmq.acl.common.AclSigner.calSignature(AclSigner.java:73)
	at org.apache.rocketmq.acl.common.AclSigner.calSignature(AclSigner.java:68)
	at org.apache.rocketmq.acl.common.AclUtils.calSignature(AclUtils.java:58)
	at org.apache.rocketmq.acl.common.AclClientRPCHook.doBeforeRequest(AclClientRPCHook.java:44)
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.doBeforeRpcHooks(NettyRemotingAbstract.java:172)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:370)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterInfo(MQClientAPIImpl.java:1180)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterInfo(DefaultMQAdminExtImpl.java:275)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterInfo(DefaultMQAdminExt.java:222)
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.printClusterBaseInfo(ClusterListSubCommand.java:172)
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:88)
	... 2 more
Caused by: org.apache.rocketmq.acl.common.AclException: [10015:signature-failed] unable to calculate a request signature. error=Algorithm HmacSH
	at org.apache.rocketmq.acl.common.AclSigner.sign(AclSigner.java:63)
	at org.apache.rocketmq.acl.common.AclSigner.signAndBase64Encode(AclSigner.java:79)
	... 13 more
Caused by: java.security.NoSuchAlgorithmException: Algorithm HmacSHA1 not available
	at javax.crypto.Mac.getInstance(Mac.java:181)
	at org.apache.rocketmq.acl.common.AclSigner.sign(AclSigner.java:57)
	... 14 more
```

This is cause by `Djava.ext.dirs` pointing to a location without `sunjce_provider.jar`, which should be at `${JAVA_HOME}/lib/ext` in JRE.

## Brief changelog

Add correct ext dir for JRE

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by zongtanghu** [comment]
@boypt  Hi your pr shoud be committed to develop branch rather than master branch.Thanks.

**Comment by boypt** [comment]
> @boypt Hi your pr shoud be committed to develop branch rather than master branch.Thanks.

OK. I change the branch.

**Comment by zongtanghu** [comment]
> > @boypt Hi your pr shoud be committed to develop branch rather than master branch.Thanks.
> 
> OK. I change the branch.

And 

> > @boypt Hi your pr shoud be committed to develop branch rather than master branch.Thanks.
> 
> OK. I change the branch.

Okay,and please look at your commits which includes in your PR.Please rebase your code in your local enviroment firstly.

**Comment by zongtanghu** [comment]
> > > @boypt Hi your pr shoud be committed to develop branch rather than master branch.Thanks.
> > 
> > 
> > OK. I change the branch.
> 
> And
> 
> > > @boypt Hi your pr shoud be committed to develop branch rather than master branch.Thanks.
> > 
> > 
> > OK. I change the branch.
> 
> Okay,and please look at your commits which includes in your PR.Please rebase your code in your local enviroment firstly. @boypt

**Comment by boypt** [comment]
> > > > @boypt Hi your pr shoud be committed to develop branch rather than master branch.Thanks.
> > > 
> > > 
> > > OK. I change the branch.
> > 
> > 
> > And
> > > > @boypt Hi your pr shoud be committed to develop branch rather than master branch.Thanks.
> > > 
> > > 
> > > OK. I change the branch.
> > 
> > 
> > Okay,and please look at your commits which includes in your PR.Please rebase your code in your local enviroment firstly. @boypt

sorry I messed that up. I push another PR as #1140 , please review

**Pull request closed without merging**
