### PR TITLE
[ISSUE #4647] Update CommandLineOption secretKey to necessary

### LINKED ISSUE #4647: The admin tool updateAclConfig failed
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

when i exec `./bin/mqadmin updateAclConfig -n 192.168.137.73:9876 -c DefaultCluster -a test-acl  -w 192.168.137.73`

then return

> 
          org.apache.rocketmq.tools.command.SubCommandException: UpdateAccessConfigSubCommand command failed
              at org.apache.rocketmq.tools.command.acl.UpdateAccessConfigSubCommand.execute(UpdateAccessConfigSubCommand.java:180)
              at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:149)
              at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:100)
      Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 209  DESC: The accessKey=test-acl and secretKey=null cannot be null and length should longer than 6
      For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
              at org.apache.rocketmq.client.impl.MQClientAPIImpl.createPlainAccessConfig(MQClientAPIImpl.java:335)
              at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.createAndUpdatePlainAccessConfig(DefaultMQAdminExtImpl.java:206)
              at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.createAndUpdatePlainAccessConfig(DefaultMQAdminExt.java:176)
              at org.apache.rocketmq.tools.command.acl.UpdateAccessConfigSubCommand.execute(UpdateAccessConfigSubCommand.java:170)

I noticed secretKey is not necessary

> 
    opt = new Option("s", "secretKey", true, "set secretKey in acl config file");
        opt.setRequired(false);
        options.addOption(opt);

but In `org.apache.rocketmq.acl.plain.PlainPermissionManager#checkPlainAccessConfig` is checked

> 
    public void checkPlainAccessConfig(PlainAccessConfig plainAccessConfig) throws AclException {
        if (plainAccessConfig.getAccessKey() == null
            || plainAccessConfig.getSecretKey() == null
            || plainAccessConfig.getAccessKey().length() <= AclConstants.ACCESS_KEY_MIN_LENGTH
            || plainAccessConfig.getSecretKey().length() <= AclConstants.SECRET_KEY_MIN_LENGTH) {
            throw new AclException(String.format(
                "The accessKey=%s and secretKey=%s cannot be null and length should longer than 6",
                plainAccessConfig.getAccessKey(), plainAccessConfig.getSecretKey()));
        }
    }

- What is expected to see?

the two place is consistent

- What did you see instead?

is not consistent

2. Please tell us about your environment:

4.9.4

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

I suggest modify to below

> 
    opt = new Option("s", "secretKey", true, "set secretKey in acl config file");
        opt.setRequired(true);
        options.addOption(opt);

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Close #4647 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by hzh0425** [comment]
good point

**Review by hzh0425 — APPROVED** [review]

**Review by lizhiboo — APPROVED** [review]
LGTM

**Review by ni-ze — APPROVED** [review]
LGTM

**Review by tsunghanjacktsai — APPROVED** [review]

**Comment by zongtanghu** [comment]
LGTM

**Review by zongtanghu — APPROVED** [review]

**Pull request merged**
