### PR TITLE
[ISSUE #1665] Add more unit test for Validators

### PR DESCRIPTION
**Pull request by jamesxuhaozhe**
## What is the purpose of the change

Add more unit test for Validators

## Brief changelog

XX

## Verifying this change

UT passes

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by jamesxuhaozhe** [comment]
I'm not sure why some of the checks failed. But doesn't look they failed because of my change. Can someone kindly review this pr? Thanks!

**Comment by duhenglucky** [comment]
@jamesxuhaozhe the Travis failed because the coverage decreased, you can ignore this temporarily, or add more unit tests to improve coverage.

**Comment by jamesxuhaozhe** [comment]
> @jamesxuhaozhe the Travis failed because the coverage decreased, you can ignore this temporarily, or add more unit tests to improve coverage.

Thank you. However, I am still confused. Because if you take a look at the code change I made in this pr. The change did nothing but adding more unit tests. Ideally, the test coverage should increase a little bit. Let me know how should I fix this and if I am missing anything. Thanks a lot!

**Comment by jamesxuhaozhe** [comment]
@duhenglucky Not sure what is going on, I added even more unit tests like you suggested, but the coverage still dropped. Much appreciated if you can help to take a look at. Just trying to get this pr to merge. :)

**Comment by duhenglucky** [comment]
@jamesxuhaozhe Would you like resole conflicts first?

**Pull request closed without merging**
