### PR TITLE
[ISSUE #5138] Do not throw exception in order producer demo

### PR DESCRIPTION
**Pull request by alexcao2018**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Fixed bug https://github.com/apache/rocketmq/issues/5138 . For previous PR conflicts, I make a new PR.

## Brief changelog

Fixed bug https://github.com/apache/rocketmq/issues/5138 .

## Verifying this change

Fixed bug https://github.com/apache/rocketmq/issues/5138 .

### CODE REVIEW

**Comment by alexcao2018** [comment]
linked from https://github.com/apache/rocketmq/pull/5150

**Review by lizhanhui — CHANGES_REQUESTED** [review]
Why UnsupportedEncodingException is not OK while MQClientException is?

**Comment by lizhanhui** [comment]
It would make sense to catch all exceptions raised and translate them into human-friendly messages via standard error output.

**Comment by alexcao2018** [comment]
> Why UnsupportedEncodingException is not OK while MQClientException is?

Because previous version using the method of String getBytes(String) that throws UnsupportedEncodingException, I change to use getBytes(Charset) , overload, making code nice, It is none of business to MQClientException.

**Comment by lizhanhui** [comment]
@alexcao2018 
> Because previous version using the method of String getBytes(String) that throws UnsupportedEncodingException, I change to use getBytes(Charset) , overload, making code nice

No, you are not making the code nice, you are creating chances of introducing Silent Data Corruption. See the [Java doc here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#getBytes(java.nio.charset.Charset))

**This method always replaces malformed-input and unmappable-character sequences with this charset's default replacement byte array.**

This is not expected, should use CharsetEncoder to enhance the solution, as is elaborated in the Javadoc.

In terms of method signature on exception, 

> "It would make sense to catch all exceptions raised and translate them into human-friendly messages via standard error output." 

still holds.

**Comment by alexcao2018** [comment]
> Silent Data Corruption

I committed new code improvement for the issue mentioned before in a new branch issue_5138_alt2, and I also submitted a PR on it.

**Comment by alexcao2018** [comment]
Please close this PR.

**Comment by alexcao2018** [comment]
I already found this issue: getBytes(StandardCharsets.UTF_8); in a large number of code of example package. How to do them is my question.

**Comment by lizhanhui** [comment]
> How to do them is my question.

It would be a good pull request to fix them.

**Comment by lizhanhui** [comment]
> Please close this PR.

You do not have to create new pull requests... It would be fine to fix conflicts through rebasing and pushing to your forked branch

**Pull request closed without merging**
