### PR TITLE
[ISSUE #7131] Replace java.nio.ByteBuffer with class name

### LINKED ISSUE #7131: [Enhancement] Replace java.nio.ByteBuffer with class name
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

I have found many reference like `java.nio.ByteBuffer` in this repository, may be replace to shortly class name directly.

### Motivation

For better code readability and simplicity

### Describe the Solution You'd Like

Replace java.nio.ByteBuffer with class name

### Describe Alternatives You've Considered

Replace java.nio.ByteBuffer with class name

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zhiliatom**
Fixes #7131

### CODE REVIEW

**Review by lizhimins — APPROVED** [review]

**Review by mxsm — APPROVED** [review]
LGTM

**Comment by RongtongJin** [comment]
LGTM

**Review by joeCarf — COMMENTED** [review]
hi, there ci failures, please checkout :)

**Comment by zhiliatom** [comment]
> 

Hi, I've read the log but can't understand why it building fail, cause I havn't modify any code actually.

**Comment by zhiliatom** [comment]
@RongtongJin Pay attention to this patch, can it be merged?

**Review by joeCarf — APPROVED** [review]

**Pull request closed without merging**
