### PR TITLE
[ROCKETMQ-27]Add store commitlog path online

### PR DESCRIPTION
**Pull request by lizhanhui**
RocketMQ broker stores all messages before they are expired, which requires pretty much storage for a high load system. For now, the message store can be configured to use only one partition. Quite often, we find broker runs out of storage as business expands quickly. Online resizing a partition most of time is not possible(with absence of LVM) whilst attaching a new disk/partition in cloud environment is super easy.
It would be nice for RocketMQ to be capable of adding extra commit log store path online, allocating commit log files onto partitions based on free/available space.

### CODE REVIEW

**Comment by zhouxinyu** [comment]
Hi, @lizhanhui , Let's handle this PR in RocketMQ-4.1.0 as a new feature.

**Comment by lizhanhui** [comment]
OK.

**Comment by vongosling** [comment]
Cool, could we discuss this new feature in dev email list ? BTW, This branch has conflicts that must be resolved:-)

**Comment by Jaskey** [comment]
Cool enhancement for this. 

But just one thing to confirm, actually rocketmq will delete commit log when the disk space is ready to be full(85% by default) even though the commit log file is not expired,  won't it @lizhanhui

**Comment by vsair** [comment]
@Jaskey   yeah, it's true that rocketmq will delete commit logs  when disk is full, even though not expired.

**Comment by lizhanhui** [comment]
@Jaskey @vsair No, Broker only delete expired files.

**Comment by Jaskey** [comment]
As far as I know, rocketmq will clean the unexpired files as long as space is 85% full and cleanFileForciblyEnable=true(true by default)

Please refer to the code snippet 

```
    public int deleteExpiredFileByTime(final long expiredTime,
        final int deleteFilesInterval,
        final long intervalForcibly,
        final boolean cleanImmediately) {
        Object[] mfs = this.copyMappedFiles(0);

        if (null == mfs)
            return 0;

        int mfsLength = mfs.length - 1;
        int deleteCount = 0;
        List<MappedFile> files = new ArrayList<MappedFile>();
        if (null != mfs) {
            for (int i = 0; i < mfsLength; i++) {
                MappedFile mappedFile = (MappedFile) mfs[i];
                long liveMaxTimestamp = mappedFile.getLastModifiedTimestamp() + expiredTime;
                if (System.currentTimeMillis() >= liveMaxTimestamp || cleanImmediately) { // here , it will clean the non expire files as long as cleanImmediately=true
                    if (mappedFile.destroy(intervalForcibly)) {
                        files.add(mappedFile);
                        deleteCount++;

                        if (files.size() >= DELETE_FILES_BATCH_MAX) {
                            break;
                        }

                        if (deleteFilesInterval > 0 && (i + 1) < mfsLength) {
                            try {
                                Thread.sleep(deleteFilesInterval);
                            } catch (InterruptedException e) {
                            }
                        }
                    } else {
                        break;
                    }
                }
            }
        }

        deleteExpiredFile(files);

        return deleteCount;
    }

```

**Comment by dongeforever** [comment]
@lizhanhui LGTM. Version 4.2.0 is going  to be released now. It will be nice to contain this feature. Could you please add one IT Test to maintain the quality?

**Comment by vongosling** [comment]
@dongeforever Consider the coming 4.2 release time slot, we'd better postpone this feature. @lizhanhui Could you pick up this pr, and please let me know. when it is ready for release :-)

**Comment by vongosling** [comment]
@lizhanhui I close this pr. If you have free time to pick up this issue, we could continue to discuss it.

**Pull request closed without merging**
