### PR TITLE
[ISSUE #8691] Fix PR-CI errors

### LINKED ISSUE #8691: [Bug] Fix PR-CI errors
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Github Action

### RocketMQ version

develop

### JDK Version

_No response_

### Describe the Bug

image

### Steps to Reproduce

Run ci

### What Did You Expect to See?

ci runs successfully

### What Did You See Instead?

ci runs failed

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yx9o**
Fixes #8691 .

### CODE REVIEW

**Comment by francisoliverlee** [comment]
actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024, it suggests to use v4 on https://github.com/actions/upload-artifact
image

**Comment by yx9o** [comment]
Thanks for your review, can I upgrade all `actions/upload-artifact@v3` to `actions/upload-artifact@v4`?

**Comment by lizhimins** [comment]
Suggest use v4

**Comment by yx9o** [comment]
All have been upgraded to actions/upload-artifact@v4, please review, thank you.

**Review by RongtongJin — APPROVED** [review]

**Pull request merged**
